# coding=utf-8
from __future__ import unicode_literals
from ..es_ES import Provider as PersonProvider


class Provider(PersonProvider):
    """
    Adds popular Catalan names.
    https://www.idescat.cat/pub/?id=aec&n=946&lang=es&t=2018
    https://www.idescat.cat/pub/?id=aec&n=947&lang=es&t=2018
    """
    first_names_male = (
        'Adam',
        'Albert',
        'Aleix',
        'Àlex',
        'Álex',
        'Antonio',
        'Arnau',
        'Biel',
        'Bruno',
        'Carlos',
        'Daniel',
        'David',
        'Enzo',
        'Eric',
        'Èric',
        'Francisco',
        'Hugo',
        'Jan',
        'Javier',
        'Joan',
        'Jordi',
        'Jorge',
        'Josep',
        'José',
        'José Maria',
        'José María',
        'Juan',
        'Leo',
        'Lucas',
        'Manuel',
        'Marc',
        'Martí',
        'Max',
        'Miguel',
        'Nil',
        'Pau',
        'Pedro',
        'Pol',
        'Ramon',
        'Ramón',
        'Xavier')

    first_names_female = (
        'Abril',
        'Aina',
        'Ana',
        'Anna',
        'Antonia',
        'Antònia',
        'Arlet',
        'Carla',
        'Carmen',
        'Chloe',
        'Chlóe',
        'Claudia',
        'Clàudia',
        'Cristina',
        'Dolores',
        'Emma',
        'Francisca',
        'Isabel',
        'Jana',
        'Josefa',
        'Julia',
        'Júlia',
        'Laia',
        'Laura',
        'Lucia',
        'Maria',
        'Maria Dolores',
        'Maria Teresa',
        'Marta',
        'Martina',
        'María',
        'María Del Carmen',
        'María Dolores',
        'María Teresa',
        'Mia',
        'Montserrat',
        'Noa',
        'Nuria',
        'Núria',
        'Ona',
        'Paula',
        'Rosa',
        'Sara',
        'Silvia',
        'Sofia',
        'Sofía',
        'Sílvia',
        'Valeria',
        'Valèria')

    first_names = first_names_male + first_names_female
