# coding=utf-8
from __future__ import unicode_literals
from .. import Provider as BaseProvider


class Provider(BaseProvider):
    jobs = [
        "Account manager",
        "Agent celny",
        "Agent firmy inwestycyjnej",
        "Agent literacki",
        "Agent ubezpieczeniowy",
        "Agronom",
        "Aktor",
        "Aktor dziecięcy",
        "Aktor głosowy",
        "Aktuariusz",
        "Animator kultury",
        "Ankieter",
        "Antykwariusz",
        "Arborysta",
        "Archeolog",
        "Architekt krajobrazu",
        "Architekt wnętrz",
        "Archiwista",
        "Artysta-rezydent",
        "Astronom",
        "Audytor efektywności energetycznej",
        "Babcia klozetowa",
        "Bankowiec",
        "Barista",
        "Barman",
        "Bibliotekarz",
        "Bibliotekarz dyplomowany",
        "Biegły rewident",
        "Brakarz",
        "Broker",
        "Broker informacji",
        "Broker ubezpieczeniowy",
        "Budnicy",
        "Certyfikator energetyczny",
        "Cervesario",
        "Charakteryzator",
        "Chief marketing officer",
        "Chief security officer",
        "Choreologia",
        "Copywriter",
        "Detektyw",
        "Deweloper budowlany",
        "Diseuse",
        "Doker",
        "Doradca finansowy",
        "Doradca inwestycyjny",
        "Doradca podatkowy w Polsce",
        "Doradca ubezpieczeniowy",
        "Doula",
        "Dragoman",
        "Drwal",
        "Dubler",
        "Dyplomata",
        "Dyrektor artystyczny",
        "Dyrektor finansowy",
        "Dyrektor kreatywny",
        "Dziennikarz",
        "Dżokej",
        "Ebenista",
        "Ekonomista",
        "Ekwilibrystyka",
        "Elektromonter pomiarów",
        "Ergonomista",
        "Fasowacz",
        "Finansista",
        "Fotoreporter",
        "Freelancer",
        "Gabaj",
        "Gaucho",
        "Geodeta",
        "Geolog (zawód)",
        "Geometra",
        "Główny księgowy",
        "Grabarz",
        "Groomer",
        "Handlarz",
        "Headhunter",
        "Home staging",
        "Hostessa",
        "HR-owiec",
        "Hutnik",
        "Hycel",
        "Hydraulik",
        "Iluzjonista",
        "Inscenizator",
        "Instruktor",
        "Integrator automatyki",
        "Intendent",
        "Inżynier",
        "Inżynier budownictwa",
        "Kalfaktor",
        "Kalkulator (zawód)",
        "Kasjer biletowy",
        "Katecheta",
        "Kawalkator",
        "Kawiarka",
        "Kelner",
        "Kierowca",
        "Kiper",
        "Klechdarz",
        "Konferansjer",
        "Koniarze",
        "Konserwator zabytków",
        "Konsjerż",
        "Konstruktor (osoba)",
        "Konsultant",
        "Konsultant ślubny",
        "Kontroler biletów",
        "Kornak",
        "Kosmonauta",
        "Kostiumograf",
        "Kosztorysant",
        "Kowboj",
        "Krojczy",
        "Krupier",
        "Ksiądz",
        "Księgowy",
        "Kuk",
        "Kulis",
        "Kupiec",
        "Kurator sądowy",
        "Kurator sztuki",
        "Kurier (transport)",
        "Kurier rowerowy",
        "Lalkarz",
        "Leśniczy",
        "Liczmen",
        "Likwidator szkód",
        "Listonosz",
        "Łaźnik (ludność służebna)",
        "Łącznik (osoba)",
        "Makler giełd towarowych",
        "Makler morski",
        "Makler nadzorujący",
        "Makler papierów wartościowych",
        "Marketingowiec",
        "Markszajder",
        "Marszand",
        "Marynarz (zawód)",
        "Masztalerz",
        "Menedżer kultury",
        "Meteorolog",
        "Mim",
        "Model (zawód)",
        "Modelka dużych rozmiarów",
        "Motorniczy",
        "Mularz",
        "Nadleśniczy",
        "Nauczyciel",
        "Nauczyciel akademicki",
        "Naukowiec",
        "Niania",
        "Oceanonauta",
        "Ochroniarz",
        "Operator (pojazdy wolnobieżne)",
        "Osoba zaufania publicznego",
        "Pakowacz",
        "Palacz",
        "Perfumiarz",
        "Pisarz",
        "Plastyk",
        "Podleśniczy",
        "Poganiacz",
        "Pokojówka",
        "Politolog",
        "Polityk",
        "Portier",
        "Pośrednik finansowy",
        "Pośrednik ubezpieczeniowy",
        "Pośrednik w obrocie nieruchomościami",
        "Pracownicy uczelni w Polsce",
        "Pracownik socjalny",
        "Dzień Pracownika Socjalnego",
        "Prezenter",
        "Producent wykonawczy",
        "Projektant gier komputerowych",
        "Przedstawiciel handlowy",
        "Przewodnik turystyczny",
        "Psiarz",
        "Psycholog",
        "Pucybut",
        "QS",
        "Rachmistrz",
        "Ratownik",
        "Ratownik przedmedyczny",
        "Redaktor",
        "Redaktor merytoryczny",
        "Redaktor naukowy",
        "Redaktor techniczny",
        "Rekwizytor",
        "Reporter wojenny",
        "Reżyser",
        "Robotnik",
        "Rolnik",
        "Ruralista",
        "Rybak",
        "Rzecznik prasowy",
        "Rzeczoznawca",
        "Rzeczoznawca budowlany",
        "Rzeczoznawca majątkowy",
        "Rzeczoznawca samochodowy",
        "Salowa",
        "Satyryk",
        "Scenarzysta",
        "Scenograf",
        "Dzień Sekretarki",
        "Sekser",
        "Serwitor",
        "Skomorochy (aktorzy)",
        "Służący",
        "Sommelier",
        "Spin doctor",
        "Sprzątacz",
        "Sprzedawca",
        "Stajenny",
        "Stevie Starr",
        "Stockman",
        "Storyboardzista",
        "Strażak",
        "Studlancer",
        "Sufler",
        "Supermodelka",
        "Syndyk",
        "Syndyk licencjonowany",
        "Szatniarz",
        "Szczurołap",
        "Szlifierz",
        "Szmuklerz",
        "Sztauer",
        "Sztygar",
        "Świątnik",
        "Taksator",
        "Taksówkarz",
        "Team leader",
        "Technik awionik",
        "Technik budownictwa",
        "Technik elektronik",
        "Technik handlowiec",
        "Technik kelner",
        "Technik mechanik",
        "Technik mechanik lotniczy",
        "Technik mechanik okrętowy",
        "Technik nawigator morski",
        "Technik ochrony środowiska",
        "Technik technologii drewna",
        "Technik weterynarii",
        "Technik żywienia i gospodarstwa domowego",
        "Teksturator",
        "Terapeuta",
        "Terminolog",
        "Tłumacz",
        "Tłumacz literacki",
        "Tłumacz przysięgły",
        "Tokarz",
        "Traper",
        "Trener",
        "Trener personalny",
        "Urbanista",
        "Wardzak",
        "Wekslarz",
        "Lekarz weterynarii",
        "Węglarz (zawód)",
        "Wolny zawód",
        "Wydawca",
        "Zakrystian",
        "Zarządca nieruchomości",
        "Zawód regulowany",
        "Zoopsycholog",
        "Żołnierz",
        "Żongler (artysta cyrkowy)"
    ]
