from faker.providers import (BaseProvider)

localized = False


class Provider(BaseProvider):
    animals = (
        "Aardvark",
        "Albatross",
        "Alligator",
        "Alpaca",
        "Anole",
        "Ant",
        "Anteater",
        "Antelope",
        "Ape",
        "Armadillo",
        "Baboon",
        "Badger",
        "Barracuda",
        "Bat",
        "Bear",
        "Beaver",
        "Bee",
        "Binturong",
        "Bird",
        "Bison",
        "Bluebird",
        "Boar",
        "Bobcat",
        "Budgerigar",
        "Buffalo",
        "Butterfly",
        "Camel",
        "Capybara",
        "Caracal",
        "Caribou",
        "Cassowary",
        "Cat",
        "Caterpillar",
        "Cattle",
        "Chamois",
        "Cheetah",
        "Chicken",
        "Chimpanzee",
        "Chinchilla",
        "Chough",
        "Coati",
        "Cobra",
        "Cockroach",
        "Cod",
        "Cormorant",
        "Cougar",
        "Coyote",
        "Crab",
        "Crane",
        "Cricket",
        "Crocodile",
        "Crow",
        "Cuckoo",
        "Curlew",
        "Deer",
        "Dhole",
        "Dingo",
        "Dinosaur",
        "Dog",
        "Dogfish",
        "Dolphin",
        "Donkey",
        "Dove",
        "Dragonfly",
        "Duck",
        "Dugong",
        "Dunlin",
        "Eagle",
        "Echidna",
        "Eel",
        "Eland",
        "Elephant",
        "Elephant seal",
        "Elk",
        "Emu",
        "Falcon",
        "Ferret",
        "Finch",
        "Fish",
        "Fisher",
        "Flamingo",
        "Fly",
        "Flycatcher",
        "Fox",
        "Frog",
        "Guar",
        "Gazelle",
        "Gecko",
        "Genet",
        "Gerbil",
        "Giant panda",
        "Giraffe",
        "Gnat",
        "Gnu",
        "Goat",
        "Goldfinch",
        "Goosander",
        "Goose",
        "Gorilla",
        "Goshawk",
        "Grasshopper",
        "Grouse",
        "Guanaco",
        "Guinea fowl",
        "Guinea pig",
        "Gull",
        "Hamster",
        "Hare",
        "Hawk",
        "Hedgehog",
        "Hermit crab",
        "Heron",
        "Herring",
        "Hipppopotamus",
        "Hoatzin",
        "Hoopoe",
        "Hornet",
        "Horse",
        "Hummingbird",
        "Hyena",
        "Ibex",
        "Ibis",
        "Iguana",
        "Impala",
        "Jackal",
        "Jaguar",
        "Jay",
        "Jellyfish",
        "Jerboa",
        "Kangaroo",
        "Kingbird",
        "Kingfisher",
        "Kinkajou",
        "Kite",
        "Koala",
        "Kodkod",
        "Komodo dragon",
        "Kookaburra",
        "Kouprey",
        "Kudu",
        "Ladybug",
        "Langur",
        "Lapwing",
        "Lark",
        "Lechwe",
        "Lemur",
        "Leopard",
        "Lion",
        "Lizard",
        "Llama",
        "Lobster",
        "Locust",
        "Loris",
        "Louse",
        "Lynx",
        "Lyrebird",
        "Macaque",
        "Macaw",
        "Magpie",
        "Mallard",
        "Mammoth",
        "Manatee",
        "Mandrill",
        "Margay",
        "Marmoset",
        "Marmot",
        "Meerkat",
        "Mink",
        "Mole",
        "Mongoose",
        "Monkey",
        "Moose",
        "Mosquito",
        "Mouse",
        "Myna",
        "Narwhal",
        "Newt",
        "Nightingale",
        "Nilgai",
        "Ocelot",
        "Octopus",
        "Okapi",
        "Oncilla",
        "Opossum",
        "Orangutan",
        "Oryx",
        "Ostrich",
        "Otter",
        "Ox",
        "Owl",
        "Oyster",
        "Panther",
        "Parrot",
        "Panda",
        "Partridge",
        "Peafowl",
        "Penguin",
        "Pheasant",
        "Ping",
        "Pigeon",
        "Pika",
        "Polar bear",
        "Pony",
        "Porcupine",
        "Porpoise",
        "Prairie dog",
        "Pug",
        "Quail",
        "Quelea",
        "Quetzal",
        "Rabbit",
        "Raccoon",
        "Ram",
        "Rat",
        "Raven",
        "Red deer",
        "Red panda",
        "Reindeer",
        "Rhea",
        "Rhinoceros",
        "Rook",
        "Saki",
        "Salamander",
        "Salmon",
        "Sand dollar",
        "Sandpiper",
        "Sardine",
        "Sassaby",
        "Sea lion",
        "Seahorse",
        "Seal",
        "Serval",
        "Shark",
        "Sheep",
        "Shrew",
        "Shrike",
        "Siamang",
        "Skink",
        "Skipper",
        "Skunk",
        "Sloth",
        "Snail",
        "Snake",
        "Spider",
        "Spoonbill",
        "Squid",
        "Squirrel",
        "Starling",
        "Stilt",
        "Swan",
        "Tamarin",
        "Tapir",
        "Tarsier",
        "Termite",
        "Thrush",
        "Tiger",
        "Toad",
        "Topi",
        "Toucan",
        "Turaco",
        "Turkey",
        "Turtle",
        "Uakari",
        "Umbrellabird",
        "Unicornfish",
        "Urial",
        "Vicuña",
        "Vinegaroon",
        "Viper",
        "Viperfish",
        "Vireo",
        "Viscacha",
        "Vole",
        "Vulture",
        "Wallaby",
        "Walrus",
        "Wasp",
        "Water buffalo",
        "Waxwing",
        "Weasel",
        "Whale",
        "Wobbegong",
        "Wolf",
        "Wolverine",
        "Wombat",
        "Woodpecker",
        "Worm",
        "Wren",
        "Yak",
        "Zebra",
    )

    animals_latin = (
        "Orycteropus afer",
        "Phoebastria albatrus"
        "Crocodylus mississippiensis",
        "Vicugna pacos",
        "Dactyloidae",
        "Formicidae",
        "Myrmecophaga tridactyla",
        "Aepyceros melampus",
        "Hominoidea",
        "Dasypus novemcinctus",
        "Simia hamadryas",
        "Arctonyx albogularis",
        "Sphyraena arabiansis",
        "Craseonycteridae",
        "Ursus arctos",
        "Castor canadensis",
        "Tetragonula carbonaria",
        "Arctictis binturong",
        "Aptenodytes forsteri",
        "Bison bison",
        "Motacilla sialis",
        "Sus scrofa",
        "Lynx rufus",
        "Melopsittacus undulatus",
        "Syncerus caffer",
        "Lycaenidae",
        "Camelus bactrianus",
        "Hydrochoerus hydrochaeris",
        "Caracal caracal",
        "Rangifer tarandus",
        "Casuarius casuarius",
        "Felis catus",
        "Danaus plexippus",
        "Bos taurus",
        "Rupicapra rupicapra",
        "Acinonyx jubatus",
        "Gallus gallus domesticus",
        "Pan troglodytes",
        "Chinchilla lanigera",
        "Pyrrhocorax pyrrhocorax",
        "Nasua narica",
        "Naja naja",
        "Megaloblatta longipennis",
        "Parapercis colias",
        "Phalacrocorax carbo",
        "Puma concolor",
        "Canis latrans",
        "Dromia personata",
        "Antigone rubicunda",
        "Malgasiinae",
        "Crocodylus niloticus",
        "Corvus bennetti",
        "Cacomantis flabelliformis",
        "Numenius americanus",
        "Hyelaphus porcinus",
        "Cuon alpinus",
        "Canis lupus dingo",
        "Tyrannosaurus rex",
        "Canis lupus familiaris",
        "Cirrhigaleus asper",
        "Monodontidae",
        "Equus africanus asinus",
        "Leptotrygon veraguensis",
        "Sympetrum flaveolum",
        "Bucephala albeola",
        "Dugong dugon",
        "Calidris alpina",
        "Haliaeetus leucocephalus",
        "Tachyglossus aculeatus",
        "Anguilla japonica",
        "Taurotragus oryx",
        "Loxodonta africana",
        "Mirounga angustirostris",
        "Cervus canadensis nannodes",
        "Dromaius novaehollandiae",
        "Falco berigora",
        "Mustela furo",
        "Pyrrhula pyrrhula",
        "Epinephelus lanceolatus",
        "Pekania pennanti",
        "Phoenicoparrus jamesi",
        "Hydrophoria linogrisea",
        "Melaenornis fischeri",
        "Lycalopex culpaeus",
        "Mantella baroni",
        "Bos gaurus",
        "Gazella leptoceros",
        "Phelsuma laticauda",
        "Genetta genetta",
        "Meriones unguiculatus",
        "Ailuropoda melanoleuca",
        "Giraffa tippelskirchii",
        "Mycetobia asiatica ",
        "Connochaetes gnou",
        "Capra aegagrus hircus",
        "Carduelis carduelis",
        "Mergus merganser",
        "Anser anser",
        "Gorilla gorilla",
        "Accipiter trivirgatus",
        "Schistocerca americana",
        "Centrocercus urophasianus",
        "Lama guanicoe",
        "Numida meleagris",
        "Cavia porcellus",
        "Larus pacificus",
        "Mesocricetus auratus",
        "Lepus saxatilis",
        "Accipiter gentilis",
        "Erinaceus europaeus",
        "Dardanus calidus",
        "Ardea herodias",
        "Clupea harengus",
        "Hippopotamus amphibius",
        "Opisthocomus hoazin",
        "Upupa epops",
        "Vespa orientalis",
        "Equus ferus caballus",
        "Glaucis aeneus",
        "Crocuta crocuta",
        "Capra aegagrus aegagrus",
        "Threskiornis melanocephalus",
        "Iguana iguana",
        "Aepyceros melampus",
        "Canis aureus",
        "Panthera onca",
        "Garrulus glandarius",
        "Chrysaora fuscescens",
        "Allactaga tetradactyla",
        "Osphranter rufus",
        "Tyrannus tyrannus",
        "Ceyx azureus",
        "Potos flavus",
        "Milvus migrans",
        "Phascolarctos cinereus",
        "Leopardus guigna",
        "Varanus komodoensis",
        "Dacelo novaeguineae",
        "Bos sauveli",
        "Tragelaphus imberbis",
        "Coccinella magnifica",
        "Semnopithecus entellus",
        "Vanellus armatus",
        "Alauda arvensis",
        "Kobus leche",
        "Lemur catta",
        "Panthera pardus",
        "Panthera leo",
        "Chamaeleo calyptratus",
        "Lama glama",
        "Homarus gammarus",
        "Locusta migratoria",
        "Loris lydekkerianus",
        "Fahrenholzia pinnata",
        "Lynx canadensis",
        "Menura novaehollandiae",
        "Macaca radiata",
        "Ara ararauna",
        "Urocissa caerulea",
        "Anas platyrhynchos",
        "Mammuthus primigenius",
        "Trichechus manatus",
        "Mandrillus sphinx",
        "Leopardus wiedii",
        "Callithrix jacchus",
        "Marmota flaviventris",
        "Suricata suricatta",
        "Neogale vison",
        "Scalopus aquaticus",
        "Cynictis penicillata",
        "Pongo pygmaeus",
        "Alces alces",
        "Anopheles",
        "Mus musculus",
        "Leucopsar rothschildi",
        "Monodon monoceros",
        "Ichthyosaura alpestris",
        "Luscinia megarhynchos",
        "Boselaphus tragocamelus",
        "Leopardus pardalis",
        "Octopus vulgaris",
        "Okapia johnstoni",
        "Leopardus tigrinus",
        "Didelphis imperfecta",
        "Pongo abelii",
        "Oryx gazella",
        "Struthio camelus",
        "Lutra lutra",
        "Bos taurus indicus",
        "Bubo bubo",
        "Magallana gigas",
        "Nymphicus hollandicus",
        "Ailuropoda melanoleuca qinlingensis",
        "Rollulus rouloul",
        "Pavo cristatus",
        "Phasianus colchicus",
        "Sus scrofa domesticus",
        "Columba livia domestica",
        "Ochotona princeps",
        "Ursus maritimus",
        "Erethizon dorsatum",
        "Phocoena phocoena",
        "Cynomys gunnisoni",
        "Coturnix ypsilophora",
        "Quelea quelea",
        "Pharomachrus auriceps",
        "Oryctolagus cuniculus",
        "Procyon lotor",
        "Ovis aries",
        "Rattus norvegicus",
        "Corvus corax",
        "Cervus elaphus",
        "Ailurus fulgens",
        "Rhea americana",
        "Ceratotherium simum",
        "Corvus frugilegus",
        "Pithecia pithecia",
        "Ambystoma maculatum",
        "Salmo salar",
        "Clypeaster scutiforme",
        "Calidris alpina Numenius",
        "Sardinella brasiliensis",
        "Damaliscus lunatus",
        "Zalophus californianus",
        "Hippocampus hippocampus",
        "Odobenus rosmarus",
        "Leptailurus serval",
        "Pristiophorus japonicus",
        "Blarina carolinensis",
        "Lanius collurio",
        "Symphalangus syndactylus",
        "Tiliqua scincoides scincoides",
        "Mephitis mephitis",
        "Choloepus hoffmanni",
        "Helix pomatia",
        "Anomochilus",
        "Latrodectus apicalis",
        "Platalea ajaja",
        "Sepioteuthis sepioidea",
        "Callosciurus prevostii",
        "Lamprotornis hildebrandti",
        "Himantopus himantopus",
        "Cygnus olor",
        "Saguinus imperator",
        "Tapirus terrestris",
        "Carlito syrichta",
        "Coptotermes formosanus",
        "Turdus litsitsirupa",
        "Panthera tigris",
        "Bombina bombina",
        "Damaliscus korrigum jimela",
        "Aulacorhynchus caeruleogularis",
        "Tauraco persa",
        "Meleagris gallopavo",
        "Emydura subglobosa",
        "Cacajao calvus",
        "Cephalopterus penduliger",
        "Naso brevirostris",
        "Ovis vignei bochariensis",
        "Vicugna vicugna",
        "Mastigoproctus",
        "Vipera xanthina",
        "Chauliodus danae",
        "Vireo griseus",
        "Lagostomus maximus",
        "Myodes glareolus",
        "Aegypius monachus",
        "Macropus rufogriseus",
        "Phoca rosmarus",
        "Vespula germanica",
        "Bubalus bubalis",
        "Bombycilla garrulus",
        "Mustela nivalis",
        "Berardius bairdii",
        "Orectolobus maculatus",
        "Canis lupus lupus",
        "Gulo gulo",
        "Vombatus ursinus",
        "Melanerpes striatus",
        "Lumbricus terrestris",
        "Cistothorus palustris",
        "Bos grunniens",
        "Equus quagga",
    )

    def animal_name(self):
        return self.random_element(self.animals)

    def animal_scientific_name(self):
        return self.random_element((self.animals_latin))
