from ..de import Provider as AddressProvider


class Provider(AddressProvider):
    city_formats = ("{{city_name}}",)

    city_with_postcode_formats = ("{{postcode}} {{city}}",)

    street_name_formats = (
        "{{first_name}}-{{last_name}}-{{street_suffix_long}}",
        "{{last_name}}{{street_suffix_short}}",
    )
    street_address_formats = ("{{street_name}} {{building_number}}",)
    address_formats = ("{{street_address}}\n{{postcode}} {{city}}",)

    # NOTE: Zero itself can be a valid building number in rare cases e.g., Wilhelm-Wisser-Str. 0, Heidhörn
    # see: https://www.uniserv.com/wissen/magazin/article/besonderheiten-von-zustelladressen/
    building_number_formats = ("#", "%#", "%##", "%###", "%/%", "%#/%#", "%-%", "%#-%#")

    street_suffixes_long = (
        "Gasse",
        "Platz",
        "Ring",
        "Straße",
        "Weg",
        "Allee",
    )
    street_suffixes_short = (
        "gasse",
        "platz",
        "ring",
        "straße",
        "str.",
        "weg",
        "allee",
    )

    postcode_formats = ("#####",)

    cities = (
        "Aachen",
        "Ahaus",
        "Altentreptow",
        "Altötting",
        "Amberg",
        "Angermünde",
        "Anklam",
        "Ansbach",
        "Apolda",
        "Arnstadt",
        "Artern",
        "Aschaffenburg",
        "Aue",
        "Auerbach",
        "Augsburg",
        "Aurich",
        "Backnang",
        "Bad Brückenau",
        "Bad Freienwalde",
        "Bad Kissingen",
        "Bad Kreuznach",
        "Bad Langensalza",
        "Bad Liebenwerda",
        "Bad Mergentheim",
        "Badalzungen",
        "Badibling",
        "Badoberan",
        "Bamberg",
        "Bautzen",
        "Bayreuth",
        "Beeskow",
        "Beilngries",
        "Belzig",
        "Berchtesgaden",
        "Bergzabern",
        "Berlin",
        "Bernburg",
        "Bersenbrück",
        "Biedenkopf",
        "Bischofswerda",
        "Bitterfeld",
        "Bogen",
        "Borken",
        "Borna",
        "Brand",
        "Brandenburg",
        "Bremen",
        "Bremervörde",
        "Brilon",
        "Bruchsal",
        "Burg",
        "Burgdorf",
        "Burglengenfeld",
        "Böblingen",
        "Büsingen am Hochrhein",
        "Bützow",
        "Calau",
        "Calw",
        "Celle",
        "Chemnitz",
        "Cloppenburg",
        "Coburg",
        "Cottbus",
        "Crailsheim",
        "Cuxhaven",
        "Dachau",
        "Darmstadt",
        "Deggendorf",
        "Delitzsch",
        "Demmin",
        "Dessau",
        "Dieburg",
        "Diepholz",
        "Dinkelsbühl",
        "Dinslaken",
        "Donaueschingen",
        "Dresden",
        "Duderstadt",
        "Döbeln",
        "Düren",
        "Ebermannstadt",
        "Ebern",
        "Ebersberg",
        "Eberswalde",
        "Eckernförde",
        "Eggenfelden",
        "Eichstätt",
        "Eilenburg",
        "Einbeck",
        "Eisenach",
        "Eisenberg",
        "Eisenhüttenstadt",
        "Eisleben",
        "Emmendingen",
        "Erbisdorf",
        "Erding",
        "Erfurt",
        "Erkelenz",
        "Euskirchen",
        "Eutin",
        "Fallingbostel",
        "Feuchtwangen",
        "Finsterwalde",
        "Flöha",
        "Forchheim",
        "Forst",
        "Freising",
        "Freital",
        "Freudenstadt",
        "Fulda",
        "Fürstenfeldbruck",
        "Fürstenwalde",
        "Füssen",
        "Gadebusch",
        "Gardelegen",
        "Garmisch-Partenkirchen",
        "Geithain",
        "Geldern",
        "Gelnhausen",
        "Genthin",
        "Gera",
        "Germersheim",
        "Gerolzhofen",
        "Gießen",
        "Gifhorn",
        "Goslar",
        "Gotha",
        "Grafenau",
        "Gransee",
        "Greifswald",
        "Greiz",
        "Grevenbroich",
        "Grevesmühlen",
        "Griesbach Rottal",
        "Grimma",
        "Grimmen",
        "Groß-Gerau",
        "Großenhain",
        "Gräfenhainichen",
        "Guben",
        "Gunzenhausen",
        "Göppingen",
        "Görlitz",
        "Göttingen",
        "Günzburg",
        "Güstrow",
        "Gütersloh",
        "Hagenow",
        "Hainichen",
        "Halberstadt",
        "Haldensleben",
        "Hamburg",
        "Hammelburg",
        "Hannover",
        "Hannoversch Münden",
        "Hansestadttralsund",
        "Havelberg",
        "Hechingen",
        "Heiligenstadt",
        "Heinsberg",
        "Helmstedt",
        "Herford",
        "Hersbruck",
        "Herzberg",
        "Hettstedt",
        "Hildburghausen",
        "Hildesheim",
        "Hofgeismar",
        "Hohenmölsen",
        "Hohenstein-Ernstthal",
        "Holzminden",
        "Hoyerswerda",
        "Husum",
        "Höxter",
        "Hünfeld",
        "Illertissen",
        "Ilmenau",
        "Ingolstadt",
        "Iserlohn",
        "Jena",
        "Jessen",
        "Jülich",
        "Jüterbog",
        "Kaiserslautern",
        "Kamenz",
        "Karlsruhe",
        "Kassel",
        "Kehl",
        "Kelheim",
        "Kemnath",
        "Kitzingen",
        "Kleve",
        "Klötze",
        "Koblenz",
        "Konstanz",
        "Kronach",
        "Kulmbach",
        "Kusel",
        "Kyritz",
        "Königs Wusterhausen",
        "Kötzting",
        "Leipziger Land",
        "Lemgo",
        "Lichtenfels",
        "Lippstadt",
        "Lobenstein",
        "Luckau",
        "Luckenwalde",
        "Ludwigsburg",
        "Ludwigslust",
        "Lörrach",
        "Lübben",
        "Lübeck",
        "Lübz",
        "Lüdenscheid",
        "Lüdinghausen",
        "Lüneburg",
        "Magdeburg",
        "Main-Höchst",
        "Mainburg",
        "Malchin",
        "Mallersdorf",
        "Marienberg",
        "Marktheidenfeld",
        "Mayen",
        "Meiningen",
        "Meißen",
        "Melle",
        "Mellrichstadt",
        "Melsungen",
        "Meppen",
        "Merseburg",
        "Mettmann",
        "Miesbach",
        "Miltenberg",
        "Mittweida",
        "Moers",
        "Monschau",
        "Mühldorf am Inn",
        "Mühlhausen",
        "München",
        "Nabburg",
        "Naila",
        "Nauen",
        "Neu-Ulm",
        "Neubrandenburg",
        "Neunburg vorm Wald",
        "Neuruppin",
        "Neuss",
        "Neustadt am Rübenberge",
        "Neustadtner Waldnaab",
        "Neustrelitz",
        "Niesky",
        "Norden",
        "Nordhausen",
        "Northeim",
        "Nördlingen",
        "Nürtingen",
        "Oberviechtach",
        "Ochsenfurt",
        "Olpe",
        "Oranienburg",
        "Oschatz",
        "Osterburg",
        "Osterode am Harz",
        "Paderborn",
        "Parchim",
        "Parsberg",
        "Pasewalk",
        "Passau",
        "Pegnitz",
        "Peine",
        "Perleberg",
        "Pfaffenhofen an der Ilm",
        "Pinneberg",
        "Pirmasens",
        "Plauen",
        "Potsdam",
        "Prenzlau",
        "Pritzwalk",
        "Pößneck",
        "Quedlinburg",
        "Querfurt",
        "Rastatt",
        "Rathenow",
        "Ravensburg",
        "Recklinghausen",
        "Regen",
        "Regensburg",
        "Rehau",
        "Reutlingen",
        "Ribnitz-Damgarten",
        "Riesa",
        "Rochlitz",
        "Rockenhausen",
        "Roding",
        "Rosenheim",
        "Rostock",
        "Roth",
        "Rothenburg ob der Tauber",
        "Rottweil",
        "Rudolstadt",
        "Saarbrücken",
        "Saarlouis",
        "Sangerhausen",
        "Sankt Goar",
        "Sankt Goarshausen",
        "Saulgau",
        "Scheinfeld",
        "Schleiz",
        "Schlüchtern",
        "Schmölln",
        "Schongau",
        "Schrobenhausen",
        "Schwabmünchen",
        "Schwandorf",
        "Schwarzenberg",
        "Schweinfurt",
        "Schwerin",
        "Schwäbisch Gmünd",
        "Schwäbisch Hall",
        "Sebnitz",
        "Seelow",
        "Senftenberg",
        "Siegen",
        "Sigmaringen",
        "Soest",
        "Soltau",
        "Sondershausen",
        "Sonneberg",
        "Spremberg",
        "Stade",
        "Stadtroda",
        "Stadtsteinach",
        "Staffelstein",
        "Starnberg",
        "Staßfurt",
        "Steinfurt",
        "Stendal",
        "Sternberg",
        "Stollberg",
        "Strasburg",
        "Strausberg",
        "Stuttgart",
        "Suhl",
        "Sulzbach-Rosenberg",
        "Säckingen",
        "Sömmerda",
        "Tecklenburg",
        "Teterow",
        "Tirschenreuth",
        "Torgau",
        "Tuttlingen",
        "Tübingen",
        "Ueckermünde",
        "Uelzen",
        "Uffenheim",
        "Vechta",
        "Viechtach",
        "Viersen",
        "Vilsbiburg",
        "Vohenstrauß",
        "Waldmünchen",
        "Wanzleben",
        "Waren",
        "Warendorf",
        "Weimar",
        "Weißenfels",
        "Weißwasser",
        "Werdau",
        "Wernigerode",
        "Wertingen",
        "Wesel",
        "Wetzlar",
        "Wiedenbrück",
        "Wismar",
        "Wittenberg",
        "Wittmund",
        "Wittstock",
        "Witzenhausen",
        "Wolfach",
        "Wolfenbüttel",
        "Wolfratshausen",
        "Wolgast",
        "Wolmirstedt",
        "Worbis",
        "Wunsiedel",
        "Wurzen",
        "Zerbst",
        "Zeulenroda",
        "Zossen",
        "Zschopau",
    )

    states = (
        "Baden-Württemberg",
        "Bayern",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hessen",
        "Mecklenburg-Vorpommern",
        "Niedersachsen",
        "Nordrhein-Westfalen",
        "Rheinland-Pfalz",
        "Saarland",
        "Sachsen",
        "Sachsen-Anhalt",
        "Schleswig-Holstein",
        "Thüringen",
    )

    admin2_in_admin1 = {
        "Baden-Württemberg": [
            "Stuttgart",
            "Böblingen",
            "Esslingen",
            "Göppingen",
            "Ludwigsburg",
            "Rems-Murr-Kreis",
            "Heilbronn",
            "Heilbronn",
            "Hohenlohekreis",
            "Schwäbisch Hall",
            "Main-Tauber-Kreis",
            "Heidenheim",
            "Ostalbkreis",
            "Baden-Baden",
            "Karlsruhe",
            "Karlsruhe",
            "Rastatt",
            "Heidelberg",
            "Mannheim",
            "Neckar-Odenwald-Kreis",
            "Rhein-Neckar-Kreis",
            "Pforzheim",
            "Calw",
            "Enzkreis",
            "Freudenstadt",
            "Freiburg im Breisgau",
            "Breisgau-Hochschwarzwald",
            "Emmendingen",
            "Ortenaukreis",
            "Rottweil",
            "Schwarzwald-Baar-Kreis",
            "Tuttlingen",
            "Konstanz",
            "Lörrach",
            "Waldshut",
            "Reutlingen",
            "Tübingen",
            "Zollernalbkreis",
            "Ulm",
            "Alb-Donau-Kreis",
            "Biberach",
            "Bodenseekreis",
            "Ravensburg",
            "Sigmaringen",
        ],
        "Bayern": [
            "Ingolstadt",
            "Landkreis München",
            "Rosenheim",
            "Altötting",
            "Berchtesgadener Land",
            "Bad Tölz-Wolfratshausen",
            "Dachau",
            "Ebersberg",
            "Eichstätt",
            "Erding",
            "Freising",
            "Fürstenfeldbruck",
            "Garmisch-Partenkirchen",
            "Landsberg am Lech",
            "Miesbach",
            "Mühldorf a.Inn",
            "München",
            "Neuburg-Schrobenhausen",
            "Pfaffenhofen a.d.Ilm",
            "Rosenheim",
            "Starnberg",
            "Traunstein",
            "Weilheim-Schongau",
            "Landshut",
            "Passau",
            "Straubing",
            "Deggendorf",
            "Freyung-Grafenau",
            "Kelheim",
            "Landshut",
            "Passau",
            "Regen",
            "Rottal-Inn",
            "Straubing-Bogen",
            "Dingolfing-Landau",
            "Amberg",
            "Regensburg",
            "Weiden i.d.OPf.",
            "Amberg-Sulzbach",
            "Cham",
            "Neumarkt i.d.OPf.",
            "Neustadt a.d.Waldnaab",
            "Regensburg",
            "Schwandorf",
            "Tirschenreuth",
            "Bamberg",
            "Bayreuth",
            "Coburg",
            "Hof",
            "Bamberg",
            "Bayreuth",
            "Coburg",
            "Forchheim",
            "Hof",
            "Kronach",
            "Kulmbach",
            "Lichtenfels",
            "Wunsiedel i.Fichtelgebirge",
            "Ansbach",
            "Erlangen",
            "Fürth",
            "Nürnberg",
            "Schwabach",
            "Ansbach",
            "Erlangen-Höchstadt",
            "Fürth",
            "Nürnberger Land",
            "Neustadt a.d.Aisch-Bad Windsheim",
            "Roth",
            "Weißenburg-Gunzenhausen",
            "Aschaffenburg",
            "Schweinfurt",
            "Würzburg",
            "Aschaffenburg",
            "Bad Kissingen",
            "Rhön-Grabfeld",
            "Haßberge",
            "Kitzingen",
            "Miltenberg",
            "Main-Spessart",
            "Schweinfurt",
            "Würzburg",
            "Augsburg",
            "Kaufbeuren",
            "Kempten (Allgäu)",
            "Memmingen",
            "Aichach-Friedberg",
            "Augsburg",
            "Dillingen a.d.Donau",
            "Günzburg",
            "Neu-Ulm",
            "Lindau (Bodensee)",
            "Ostallgäu",
            "Unterallgäu",
            "Donau-Ries",
            "Oberallgäu",
        ],
        "Berlin": ["Berlin"],
        "Brandenburg": [
            "Brandenburg an der Havel",
            "Cottbus",
            "Frankfurt (Oder)",
            "Potsdam",
            "Barnim",
            "Dahme-Spreewald",
            "Elbe-Elster",
            "Havelland",
            "Märkisch-Oderland",
            "Oberhavel",
            "Oberspreewald-Lausitz",
            "Oder-Spree",
            "Ostprignitz-Ruppin",
            "Potsdam-Mittelmark",
            "Prignitz",
            "Spree-Neiße",
            "Teltow-Fläming",
            "Uckermark",
        ],
        "Bremen": ["Bremen", "Bremerhaven"],
        "Hamburg": ["Hamburg"],
        "Hessen": [
            "Darmstadt, Wissenschaftsstadt",
            "Frankfurt am Main",
            "Offenbach am Main",
            "Wiesbaden",
            "Bergstraße",
            "Darmstadt-Dieburg",
            "Groß-Gerau",
            "Hochtaunuskreis",
            "Main-Kinzig-Kreis",
            "Main-Taunus-Kreis",
            "Odenwaldkreis",
            "Offenbach",
            "Rheingau-Taunus-Kreis",
            "Wetteraukreis",
            "Gießen",
            "Lahn-Dill-Kreis",
            "Limburg-Weilburg",
            "Marburg-Biedenkopf",
            "Vogelsbergkreis",
            "Kassel",
            "Fulda",
            "Hersfeld-Rotenburg",
            "Kassel",
            "Schwalm-Eder-Kreis",
            "Waldeck-Frankenberg",
            "Werra-Meißner-Kreis",
        ],
        "Mecklenburg-Vorpommern": [
            "Rostock",
            "Schwerin",
            "Mecklenburgische Seenplatte",
            "Landkreis Rostock",
            "Vorpommern-Rügen",
            "Nordwestmecklenburg",
            "Vorpommern-Greifswald",
            "Ludwigslust-Parchim",
        ],
        "Niedersachsen": [
            "Braunschweig",
            "Salzgitter",
            "Wolfsburg",
            "Gifhorn",
            "Goslar",
            "Helmstedt",
            "Northeim",
            "Peine",
            "Wolfenbüttel",
            "Göttingen",
            "Region Hannover",
            "Diepholz",
            "Hameln-Pyrmont",
            "Hildesheim",
            "Holzminden",
            "Nienburg (Weser)",
            "Schaumburg",
            "Celle",
            "Cuxhaven",
            "Harburg",
            "Lüchow-Dannenberg",
            "Lüneburg",
            "Osterholz",
            "Rotenburg (Wümme)",
            "Heidekreis",
            "Stade",
            "Uelzen",
            "Verden",
            "Delmenhorst",
            "Emden",
            "Oldenburg (Oldenburg)",
            "Osnabrück",
            "Wilhelmshaven",
            "Ammerland",
            "Aurich",
            "Cloppenburg",
            "Emsland",
            "Friesland",
            "Grafschaft Bentheim",
            "Leer",
            "Oldenburg",
            "Osnabrück",
            "Vechta",
            "Wesermarsch",
            "Wittmund",
        ],
        "Nordrhein-Westfalen": [
            "Düsseldorf",
            "Duisburg",
            "Essen",
            "Krefeld",
            "Mönchengladbach",
            "Mülheim an der Ruhr",
            "Oberhausen",
            "Remscheid",
            "Solingen, Klingenstadt",
            "Wuppertal",
            "Kleve",
            "Mettmann",
            "Rhein-Kreis Neuss",
            "Viersen",
            "Wesel",
            "Bonn",
            "Köln",
            "Leverkusen",
            "Städteregion Aachen",
            "Düren",
            "Rhein-Erft-Kreis",
            "Euskirchen",
            "Heinsberg",
            "Oberbergischer Kreis",
            "Rheinisch-Bergischer Kreis",
            "Rhein-Sieg-Kreis",
            "Bottrop",
            "Gelsenkirchen",
            "Münster",
            "Borken",
            "Coesfeld",
            "Recklinghausen",
            "Steinfurt",
            "Warendorf",
            "Bielefeld",
            "Gütersloh",
            "Herford",
            "Höxter",
            "Lippe",
            "Minden-Lübbecke",
            "Paderborn",
            "Bochum",
            "Dortmund",
            "Hagen der FernUniversität",
            "Hamm",
            "Herne",
            "Ennepe-Ruhr-Kreis",
            "Hochsauerlandkreis",
            "Märkischer Kreis",
            "Olpe",
            "Siegen-Wittgenstein",
            "Soest",
            "Unna",
        ],
        "Rheinland-Pfalz": [
            "Koblenz",
            "Ahrweiler",
            "Altenkirchen (Westerwald)",
            "Bad Kreuznach",
            "Birkenfeld",
            "Cochem-Zell",
            "Mayen-Koblenz",
            "Neuwied",
            "Rhein-Hunsrück-Kreis",
            "Rhein-Lahn-Kreis",
            "Westerwaldkreis",
            "Trier",
            "Bernkastel-Wittlich",
            "Eifelkreis Bitburg-Prüm",
            "Vulkaneifel",
            "Trier-Saarburg",
            "Frankenthal (Pfalz)",
            "Kaiserslautern",
            "Landau in der Pfalz",
            "Ludwigshafen am Rhein",
            "Mainz",
            "Neustadt an der Weinstraße",
            "Pirmasens",
            "Speyer",
            "Worms",
            "Zweibrücken",
            "Alzey-Worms",
            "Bad Dürkheim",
            "Donnersbergkreis",
            "Germersheim",
            "Kaiserslautern",
            "Kusel",
            "Südliche Weinstraße",
            "Rhein-Pfalz-Kreis",
            "Mainz-Bingen",
            "Südwestpfalz",
        ],
        "Saarland": [
            "Regionalverband Saarbrücken",
            "Merzig-Wadern",
            "Neunkirchen",
            "Saarlouis",
            "Saarpfalz-Kreis",
            "St. Wendel",
        ],
        "Sachsen": [
            "Chemnitz",
            "Erzgebirgskreis",
            "Mittelsachsen",
            "Vogtlandkreis",
            "Zwickau",
            "Dresden",
            "Bautzen",
            "Görlitz",
            "Meißen",
            "Sächsische Schweiz-Osterzgebirge",
            "Leipzig",
            "Leipzig",
            "Nordsachsen",
        ],
        "Sachsen-Anhalt": [
            "Dessau-Roßlau",
            "Halle (Saale)",
            "Magdeburg",
            "Altmarkkreis Salzwedel",
            "Anhalt-Bitterfeld",
            "Börde",
            "Burgenlandkreis",
            "Harz",
            "Jerichower Land",
            "Mansfeld-Südharz",
            "Saalekreis",
            "Salzlandkreis",
            "Stendal",
            "Wittenberg",
        ],
        "Schleswig-Holstein": [
            "Flensburg",
            "Kiel",
            "Lübeck",
            "Neumünster",
            "Dithmarschen",
            "Herzogtum Lauenburg",
            "Nordfriesland",
            "Ostholstein",
            "Pinneberg",
            "Plön",
            "Rendsburg-Eckernförde",
            "Schleswig-Flensburg",
            "Segeberg",
            "Steinburg",
            "Stormarn",
        ],
        "Thüringen": [
            "Erfurt",
            "Gera",
            "Jena",
            "Suhl",
            "Weimar",
            "Eichsfeld",
            "Nordhausen",
            "Wartburgkreis",
            "Unstrut-Hainich-Kreis",
            "Kyffhäuserkreis",
            "Schmalkalden-Meiningen",
            "Gotha",
            "Sömmerda",
            "Hildburghausen",
            "Ilm-Kreis",
            "Weimarer Land",
            "Sonneberg",
            "Saalfeld-Rudolstadt",
            "Saale-Holzland-Kreis",
            "Saale-Orla-Kreis",
            "Greiz",
            "Altenburger Land",
        ],
    }

    def street_suffix_short(self) -> str:
        return self.random_element(self.street_suffixes_short)

    def street_suffix_long(self) -> str:
        return self.random_element(self.street_suffixes_long)

    def city_name(self) -> str:
        return self.random_element(self.cities)

    def administrative_unit(self) -> str:
        return self.random_element(self.states)

    state = administrative_unit
    admin1 = administrative_unit

    def admin2(self) -> str:
        return self.random_element(
            tuple(
                admin2
                for admin2s in self.admin2_in_admin1.values()
                for admin2 in admin2s
            )
        )

    def admin2_from_admin1(self, admin1: str) -> str:
        return self.random_element(self.admin2_in_admin1[admin1])

    def admin2_with_admin1(self) -> str:
        admin1 = self.admin1()
        admin2 = self.admin2_from_admin1(admin1)
        return f"{admin2} {admin1}"

    def admin2_w_admin1(self, admin1: str) -> str:
        admin2 = self.admin2_from_admin1(admin1)
        return f"{admin2} {admin1}"

    def city_with_postcode(self) -> str:
        pattern: str = self.random_element(self.city_with_postcode_formats)
        return self.generator.parse(pattern)
