from .. import BaseProvider

class Provider(BaseProvider):
	subjects=[
			{"Code":"ACCT", "Description":"Accounting"},
			{"Code":"ANTH", "Description":"Anthropology"},
			{"Code":"ART", 	"Description":"Art"},
			{"Code":"AST", 	"Description":"Astronomy"},
			{"Code":"ATTR", "Description":"Athletic Training"},
			{"Code":"BA", 	"Description":"Business Administration"},
			{"Code":"BCST", "Description":"Broadcasting"},
			{"Code":"BIOL", "Description":"Biology"},
			{"Code":"BK", 	"Description":"Birth/Kindergarten"},
			{"Code":"BKSE", "Description":"Birth/Kindergarten Special Edu"},
			{"Code":"CDFR", "Description":"Child Dev/Family Relations"},
			{"Code":"CDS", 	"Description":"Communication Sciences and Dis"},
			{"Code":"CFS", 	"Description":"Child and Family Studies"},
			{"Code":"CHEM", "Description":"Chemistry"},
			{"Code":"CHER", "Description":"Cherokee"},
			{"Code":"CHIN", "Description":"Chinese"},
			{"Code":"CIS", 	"Description":"Computer Information Systems"},
			{"Code":"CJ", 	"Description":"Criminal Justice"},
			{"Code":"CLS", 	"Description":"Clinical Laboratory Sciences"},
			{"Code":"CM", 	"Description":"Construction Management"},
			{"Code":"COMM", "Description":"Communications"},
			{"Code":"COUN", "Description":"Counseling"},
			{"Code":"CS", 	"Description":"Computer Science"},
			{"Code":"CSD", 	"Description":"Communication Science and Disorders"},
			{"Code":"CSP", 	"Description":"College Student Personnel"},
			{"Code":"CTM", 	"Description":"Clothing/Textiles/Merchandise"},
			{"Code":"DA", 	"Description":"Dance"},
			{"Code":"ECET", "Description":"Electrical & Computer Engineering"},
			{"Code":"ECON", "Description":"Economics"},
			{"Code":"EDAD", "Description":"Educational Administration"},
			{"Code":"EDCI", "Description":"Educational Curriculum & Instruction"},
			{"Code":"EDEL", "Description":"Elementary Education"},
			{"Code":"EDEM", "Description":"Educational Media"},
			{"Code":"EDGC", "Description":"Counseling"},
			{"Code":"EDHE", "Description":"Higher Education"},
			{"Code":"EDL", 	"Description":"Educational Leadership"},
			{"Code":"EDM", 	"Description":"Emergency and Disaster Mgt"},
			{"Code":"EDMG", "Description":"Education Middle Grades"},
			{"Code":"EDPY", "Description":"Education and Psychology"},
			{"Code":"EDRD", "Description":"Reading"},
			{"Code":"EDRS", "Description":"Educational Research"},
			{"Code":"EDSE", "Description":"Secondary Education"},
			{"Code":"EDSU", "Description":"Educational Supervision"},
			{"Code":"EE", 	"Description":"Electrical Engineering"},
			{"Code":"EET", 	"Description":"Electronic Engineering Tech"},
			{"Code":"ELEC", "Description":"Elective"},
			{"Code":"ELMG", "Description":"Elementary/Middle Grades"},
			{"Code":"EMC", 	"Description":"Emergency Medical Care"},
			{"Code":"EMGT", "Description":"Emergency Management"},
			{"Code":"ENGL", "Description":"English"},
			{"Code":"ENGR", "Description":"Engineering"},
			{"Code":"ENT", 	"Description":"Entrepreneurship"},
			{"Code":"ENVH", "Description":"Environmental Health"},
			{"Code":"ES", 	"Description":"Environmental Science"},
			{"Code":"ESI", 	"Description":"Earth Science"},
			{"Code":"ET", 	"Description":"Engineering Technology"},
			{"Code":"ETO", 	"Description":"Engineering Tech Operations"},
			{"Code":"FCS", 	"Description":"Family & Consumer Sciences"},
			{"Code":"FIN", 	"Description":"Finance"},
			{"Code":"FOR", 	"Description":"Forestry"},
			{"Code":"FREN", "Description":"French"},
			{"Code":"FS", 	"Description":"Forensic Science"},
			{"Code":"FSM", 	"Description":"Food Service Management"},
			{"Code":"FTP", 	"Description":"Film and Television Production"},
			{"Code":"GENL", "Description":"General Elective"},
			{"Code":"GEOG", "Description":"Geography"},
			{"Code":"GEOL", "Description":"Geology"},
			{"Code":"GER", 	"Description":"German"},
			{"Code":"GERN", "Description":"Gerontology"},
			{"Code":"GNED", "Description":"General Education"},
			{"Code":"H/PS", "Description":"History/Political Science"},
			{"Code":"HE", 	"Description":"Home Economics"},
			{"Code":"HEAL", "Description":"Health"},
			{"Code":"HESA", "Description":"Higher Ed in Student Affairs"},
			{"Code":"HIA", 	"Description":"Health Information Admin"},
			{"Code":"HIM", 	"Description":"Health Information Mgmt"},
			{"Code":"HIST", "Description":"History"},
			{"Code":"HM", 	"Description":"Hospitality Management"},
			{"Code":"HPE", 	"Description":"Health & Physical Education"},
			{"Code":"HR", 	"Description":"Human Resources"},
			{"Code":"HRD", 	"Description":"Human Resources Development"},
			{"Code":"HSCC", "Description":"Health Sciences/Core"},
			{"Code":"HSEH", "Description":"Health Sci/Env Health"},
			{"Code":"HSM", 	"Description":"Health Services Management"},
			{"Code":"HSMR", "Description":"Medical Record Administration"},
			{"Code":"HSMS", "Description":"Management and Supervision"},
			{"Code":"HSMT", "Description":"Medical Technology"},
			{"Code":"HT", 	"Description":"Hospitality and Tourism"},
			{"Code":"IBUS", "Description":"International Business"},
			{"Code":"ID", 	"Description":"Industrial Distribution"},
			{"Code":"IDES", "Description":"Interior Design"},
			{"Code":"IE", 	"Description":"Industrial Education"},
			{"Code":"IEP", 	"Description":"Intensive English Program"},
			{"Code":"IET", 	"Description":"Industrial & Engineering Tech"},
			{"Code":"INST", "Description":"International Studies"},
			{"Code":"IS", 	"Description":"Information Systems"},
			{"Code":"IT", 	"Description":"Industrial Technology"},
			{"Code":"ITAL", "Description":"Italian"},
			{"Code":"JOUR", "Description":"Journalism"},
			{"Code":"JPN", 	"Description":"Japanese"},
			{"Code":"LAT", 	"Description":"Latin"},
			{"Code":"LAW", 	"Description":"Business Law"},
			{"Code":"LC", 	"Description":"Learning Contract"},
			{"Code":"LEAD", "Description":"Leadership"},
			{"Code":"LS", 	"Description":"Liberal Studies"},
			{"Code":"MATH", "Description":"Mathematics"},
			{"Code":"MBA", 	"Description":"Master of Bus Administration"},
			{"Code":"ME", 	"Description":"Mechanical Engineering"},
			{"Code":"MET", 	"Description":"Manufacturing/Engineering Tech"},
			{"Code":"MFL", 	"Description":"Modern Foreign Language"},
			{"Code":"MGT", 	"Description":"Management"},
			{"Code":"MHS", 	"Description":"Health Sciences"},
			{"Code":"MKT", 	"Description":"Marketing"},
			{"Code":"MPTP", "Description":"Motion Picture & TV Production"},
			{"Code":"MS", 	"Description":"Military Science"},
			{"Code":"MUS", 	"Description":"Music"},
			{"Code":"NAS", 	"Description":"Native American Studies"},
			{"Code":"ND", 	"Description":"Nutrition and Dietetics"},
			{"Code":"NRM", 	"Description":"Natural Resource Management"},
			{"Code":"NSG", 	"Description":"Nursing"},
			{"Code":"OA", 	"Description":"Office Administration"},
			{"Code":"PA", 	"Description":"Public Affairs"},
			{"Code":"PAR", 	"Description":"Philosophy and Religion"},
			{"Code":"PE", 	"Description":"Physical Education"},
			{"Code":"PHIL", "Description":"Philosophy"},
			{"Code":"PHYS", "Description":"Physics"},
			{"Code":"PM", 	"Description":"Project Management"},
			{"Code":"PRM", 	"Description":"Parks and Recreation Mgmt"},
			{"Code":"PSC", 	"Description":"Political Science"},
			{"Code":"PSOC", "Description":"Political Science/Sociology"},
			{"Code":"PSSM", "Description":"Public Safety & Security Mgt"},
			{"Code":"PSY", 	"Description":"Psychology"},
			{"Code":"PT", 	"Description":"Physical Therapy"},
			{"Code":"QA", 	"Description":"Quantitative Analysis"},
			{"Code":"REL", 	"Description":"Religion"},
			{"Code":"RTH", 	"Description":"Recreational Therapy"},
			{"Code":"RTV", 	"Description":"Radio and Television"},
			{"Code":"RUSS", "Description":"Russian"},
			{"Code":"SAE", 	"Description":"Science & Entrepreneurship"},
			{"Code":"SCI", 	"Description":"Science"},
			{"Code":"SM", 	"Description":"Sport Management"},
			{"Code":"SOC", 	"Description":"Sociology"},
			{"Code":"SOCW", "Description":"Social Work"},
			{"Code":"SPAN", "Description":"Spanish"},
			{"Code":"SPED", "Description":"Special Education"},
			{"Code":"STA", 	"Description":"Speech and Theatre Arts"},
			{"Code":"TEL", 	"Description":"Telecommunications"},
			{"Code":"THEA", "Description":"Theatre"},
			{"Code":"TR", 	"Description":"Theraputic Recreation"},
			{"Code":"TRVL", "Description":"Travel"},
			{"Code":"UE", 	"Description":"University Experience"},
			{"Code":"USI", 	"Description":"University Studies Interdisc"},
			{"Code":"WLL", 	"Description":"World Languages & Literatures"}
	  ]
	
	grades=["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"]
	
	titles=["17th & 18th Century Art",
			"19th Century United States",
			"3D Solid Modeling",
			"Abstract Algebra",
			"Acting",
			"Adaptive Fly Fishing",
			"Addictions",
			"Advanced Loitering",
			"Advanced Topics in Tinker Toys",
			"Animal Behavior",
			"Band of Brothers",
			"Bar/Beverage Operations",
			"Biogeography",
			"Biostatistics",
			"Breaking into Places",
			"Budgetary Processes",
			"CAM Systems",
			"Child Warfare",
			"Class 101",
			"Club Management",
			"Coding & Class Systems",
			"Community Practice",
			"Computer Modeling",
			"Congress...",
			"Cplx Var Thry 4 Bgnrs",
			"Descriptive Anatomy",
			"Diagnostics",
			"Dinosaurs",
			"Dirty Pictures",
			"Dysphagia",
			"Ensemble",
			"Flipping Burgers for Fun and Profit", 
			"Fluvial Geomorphology",
			"Fluvial Germorphology",
			"Folklore",
			"Genomics",
			"Getting Dressed",
			"Going Green",
			"Graduate Weaving",
			"Handball",
			"History of Something",
			"How to Watch Television",
			"Integral Arts",
			"Internship",
			"Introduction to Basics",
			"Introductory Books",
			"Jogging",
			"Joy of Garbage",
			"Leadership in Politics... Hahahaha",
			"Learning!",
			"Makeup",
			"Manual Therapy",
			"Milton",
			"Modern History",
			"Mthd/Anal PE & Spt Mgt",
			"Optics",
			"Organization Admin",
			"Period Styles",
			"Petrology",
			"Philosophy and Star Trek",
			"Philosophy of the Simposons",
			"Portfolio",
			"Primates",
			"Rocket Surgery",
			"Rorschach Seminar",
			"Seminar",
			"Senior Project",
			"Sexual Transmited Diseases",
			"Sizzlin' Sixties",
			"Skills for College Life",
			"So You Want To Be Millionaire",
			"Social",
			"Space Planning",
			"Special Topics",
			"Strategy First",
			"Taphonomy",
			"The Art of Walking",
			"The Beatles",
			"The Practice of Government Planning... hahaha",
			"The Science of Superheroes",
			"The Strategy of Starcraft",
			"Theoretical Phys Ed",
			"Tree Climbing",
			"Underwater Basketweaving",
			"Weaving Problems",
			"You and Your Money"]

	@classmethod
	def course_subject(cls, subj_type=None):
		"""
		Returns a random subject.
		
		:param subj_type: Key of type to be returned. either 'Code' or 'Description'
		:returns: a dict object of the subject code and description or string of the subj_type key.
		"""
		lv_rtn = cls.random_element(cls.subjects)
		if subj_type not in lv_rtn:
			return lv_rtn
		return lv_rtn[subj_type]
	
	@classmethod
	def grade(cls):
		"""
		Returns a random letter grade, A thru F with '+' or '-'
		"""
		return cls.random_element(cls.grades)
		
	@classmethod
	def course_title(cls):
		"""
		Returns a random title for a course.
		"""
		return cls.random_element(cls.titles)