# job_provider_en_af.py  (English Afghanistan - en_AF)

from .. import Provider as BaseProvider


class Provider(BaseProvider):
    """Job provider for English Afghanistan locale."""

    jobs = [
        "Actor",
        "Ship Captain",
        "District Governor",
        "Tailor",
        "Herdsman",
        "Gardener",
        "Muezzin",
        "Camel Driver",
        "Cook",
        "Dentist",
        "Carpenter",
        "Shepherd",
        "Housewife",
        "Council Member",
        "Writer",
        "Waiter",
        "Professor",
        "Salesperson",
        "Glazier",
        "Manager",
        "House Painter",
        "Boatman",
        "Street Sweeper",
        "Minister",
        "Pilot",
        "Barber",
        "Cleric",
        "Specialist",
        "Football Player",
        "Butcher",
        "Watchmaker",
        "Grocer",
        "Telephone Operator",
        "Merchant",
        "Optician",
        "Calligrapher",
        "Forester",
        "Teacher",
        "Engineer",
        "Driver",
        "Decorator",
        "Military Officer",
        "Baker",
        "Governor",
        "Student",
        "University Student",
        "Mechanic",
        "Farmer",
        "Artist",
        "Deputy",
        "Banker",
        "Blacksmith",
        "President",
        "Brigadier",
        "Caretaker",
        "Employee",
        "Coach",
        "Colonel",
        "Diver",
        "Doctor",
        "Doorman",
        "Firefighter",
        "Fisherman",
        "Fruit Seller",
        "Guard",
        "Police Officer",
        "Judge",
        "Lawyer",
        "Worker",
        "Mayor",
        "Miner",
        "Nurse",
        "Officer",
        "Photographer",
        "Plumber",
        "Actor",
        "Porter",
        "President of the Republic",
        "Prime Minister",
        "Psychologist",
        "Journalist",
        "Retired",
        "Sculptor",
        "Sergeant",
        "Shopkeeper",
        "Singer",
        "Soldier",
        "Public Speaker",
        "Surgeon",
        "Potter",
        "Tourist",
        "Welder",
        "Eye Doctor",
        "Reporter",
        "Calligrapher",
    ]