# coding=utf-8
from __future__ import unicode_literals
from ..person import Provider as PersonProvider


class Provider(PersonProvider):
    formats = (
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}} {{last_name}}',
        '{{first_name}} {{last_name}}',
        '{{first_name}} {{prefix}} {{last_name}}',
        '{{first_name}} {{last_name}}-{{last_name}}',
        '{{first_name}} {{first_name}} {{last_name}} {{last_name}}',
    )

    first_names = (
        'Abel', 'Abraham', 'Abram', 'Ada', 'Adán', 'Adrián', 'Adriana', 'Alan', 'Alana',
        'Alejandra', 'Alejandro', 'Alex', 'Alexa', 'Alexandra', 'Alexandría', 'Alexia',
        'Alexis', 'Alexis', 'Alfredo', 'Alicia', 'Alina', 'Alonzo', 'Amanda', 'Amaya',
        'Amelia', 'América', 'Ana', 'Andrea', 'Andrés', 'Ángel', 'Ángela', 'Angélica',
        'Angelina', 'Antonio', 'Ariana', 'Armando', 'Arturo', 'Asia', 'Aurora',
        'Benjamín', 'Brenda', 'Camila', 'Carlos', 'Carmen', 'Carolina', 'Cecilia',
        'Celeste', 'César', 'Clara', 'Claudia', 'Daniel', 'Daniela', 'Daniella',
        'David', 'Diana', 'Diego', 'Dulce', 'Édgar', 'Eduardo', 'Elena', 'Eliana',
        'Elías', 'Elisa', 'Elsa', 'Emanuel', 'Emilia', 'Emiliano', 'Emilio', 'Enrique',
        'Ernesto', 'Esmeralda', 'Esteban', 'Estrella', 'Eva', 'Ezequiel', 'Fabián',
        'Fátima', 'Felipe', 'Fernanda', 'Fernando', 'Francisco', 'Gabriel', 'Gabriela',
        'Gerardo', 'Gloria', 'Guadalupe', 'Guillermo', 'Gustavo', 'Héctor', 'Hugo',
        'Iris', 'Isabel', 'Isabela', 'Israel', 'Iván', 'Jaime', 'Jairo' 'Javier',
        'Jazmín', 'Jesús', 'Jimena', 'Joaquín', 'Joel', 'Jorge', 'José', 'Josué',
        'Juan', 'Julia', 'Julián', 'Juliana', 'Julio', 'Laura', 'Leila', 'Leonardo',
        'Lía', 'Lila', 'Lilian', 'Liliana', 'Linda', 'Lola', 'Lorenzo', 'Lucas',
        'Lucía', 'Lucián', 'Luis', 'Manuel', 'Marco', 'Marcos', 'María', 'Mariana',
        'Marina', 'Mario', 'Marisol', 'Martín', 'Mateo', 'Matías', 'Mauricio', 'Max',
        'Maximiliano', 'Maya', 'Melina', 'Mercedes', 'Miguel', 'Miranda', 'Miriam',
        'Mónica', 'Isabella', 'Natalia', 'Nicolás', 'Noé', 'Nora', 'Óliver', 'Olivia',
        'Omar', 'Orlando', 'Óscar', 'Pablo', 'Paola', 'Patricia', 'Paúl', 'Pedro',
        'Penélope', 'Perla', 'Rafael', 'Ramón', 'Raquel', 'Raúl', 'Regina', 'Ricardo',
        'Roberto', 'Rodrigo', 'Román', 'Rosa', 'Rubén', 'Salvador', 'Samuel', 'Sandra',
        'Santiago', 'Sara', 'Saúl', 'Sebastián', 'Selena', 'Serena', 'Sergio', 'Simón',
        'Sofía', 'Talía', 'Tatiana', 'Tobías', 'Tomás', 'Valentina', 'Valeria',
        'Verónica', 'Víctor', 'Victoria', 'Virginia', 'Vivian', 'Viviana', 'Xavier',
        'Ximena'
    )


    last_names = (
        'Abad', 'Adadia', 'Abascal', 'Abella', 'Abellán', 'Abril', 'Acedo', 'Acevedo',
        'Acero', 'Acosta', 'Acuña', 'Adán', 'Aguado', 'Agudo', 'Águila', 'Aguilar',
        'Aguilera', 'Aguiló', 'Aguirre', 'Agullo', 'Agustí', 'Agustín', 'Álamo',
        'Alarcón', 'Alba', 'Alberdi', 'Albero', 'Alberola', 'Alberto', 'Alcalá',
        'Alcalde', 'Alcántara', 'Alcaraz', 'Alcázar', 'Alcolea', 'Alegre', 'Alegria',
        'Alemán', 'Alemany', 'Alfaro', 'Alfonso', 'Aliaga', 'Almagro', 'Almansa',
        'Almazán', 'Almeida', 'Alonso', 'Alsina', 'Alvarado', 'Álvarez', 'Álvaro',
        'Aller', 'Amador', 'Amat', 'Amaya', 'Amigó', 'Amo', 'Amor', 'Amores', 'Amorós',
        'Anaya', 'Andrade', 'Andrés', 'Andreu', 'Ángel', 'Anglada', 'Angulo', 'Anguita',
        'Antón', 'Antúnez', 'Aparicio', 'Aragón', 'Aragonés', 'Aramburu', 'Arana',
        'Aranda', 'Araujo', 'Arce', 'Arco', 'Arcos', 'Arellano', 'Arenas', 'Arévalo',
        'Arias', 'Ariño', 'Ariza', 'Arjona', 'Armas', 'Armengol', 'Arnaiz', 'Arnal',
        'Arnau', 'Aroca', 'Arranz', 'Arregui', 'Arribas', 'Arrieta', 'Arroyo',
        'Arteaga', 'Artigas', 'Asenjo', 'Asensio', 'Atienza', 'Ávila', 'Avilés',
        'Ayala', 'Ayllón', 'Ayuso', 'Azcona', 'Aznar', 'Azorin', 'Badía', 'Baena',
        'Báez', 'Baeza', 'Balaguer', 'Ballester', 'Ballesteros', 'Baños', 'Baquero',
        'Barba', 'Barberá', 'Barbero', 'Barceló', 'Bárcena', 'Barco', 'Baró', 'Barón',
        'Barragán', 'Barral', 'Barranco', 'Barreda', 'Barrena', 'Barrera', 'Barriga',
        'Barrio', 'Barrios', 'Barros', 'Barroso', 'Bartolomé', 'Bas', 'Bastida',
        'Batalla', 'Batlle', 'Bautista', 'Bauzà', 'Bayo', 'Bayón', 'Bayona', 'Becerra',
        'Bejarano', 'Belda', 'Belmonte', 'Beltrán', 'Bellido', 'Bello', 'Benavent',
        'Benavente', 'Benavides', 'Benet', 'Benítez', 'Benito', 'Berenguer', 'Bermejo',
        'Bermúdez', 'Bernad', 'Bernal', 'Bernat', 'Berrocal', 'Bertrán', 'Bilbao',
        'Blanca', 'Blanco', 'Blanch', 'Blanes', 'Blasco', 'Blázquez', 'Boada', 'Boix',
        'Bolaños', 'Bonet', 'Bonilla', 'Borja', 'Borrás', 'Borrego', 'Borrell', 'Bosch',
        'Botella', 'Bou', 'Bravo', 'Briones', 'Bru', 'Buendía', 'Bueno', 'Burgos',
        'Busquets', 'Bustamante', 'Bustos', 'Caballero', 'Cabanillas', 'Cabañas',
        'Cabello', 'Cabeza', 'Cabezas', 'Cabo', 'Cabrera', 'Cabrero', 'Cáceres',
        'Cadenas', 'Cal', 'Calatayud', 'Calderón', 'Calvet', 'Calvo', 'Calleja',
        'Calzada', 'Camacho', 'Cámara', 'Camino', 'Campillo', 'Campo', 'Campos',
        'Campoy', 'Camps', 'Canales', 'Canals', 'Canet', 'Cano', 'Cánovas', 'Cantero',
        'Cantón', 'Cañas', 'Cañellas', 'Cañete', 'Cañizares', 'Caparrós', 'Capdevila',
        'Carballo', 'Carbajo', 'Carbó', 'Carbonell', 'Cárdenas', 'Cardona', 'Carlos',
        'Carmona', 'Carnero', 'Caro', 'Carpio', 'Carranza', 'Carrasco', 'Carreño',
        'Carrera', 'Carreras', 'Carretero', 'Carrillo', 'Carrión', 'Carro', 'Carvajal',
        'Casado', 'Casal', 'Casals', 'Casanova', 'Casanovas', 'Casares', 'Casas',
        'Cases', 'Castañeda', 'Castejón', 'Castell', 'Castellanos', 'Castelló',
        'Castells', 'Castilla', 'Castillo', 'Castrillo', 'Castro', 'Catalá', 'Catalán',
        'Cazorla', 'Cepeda', 'Cerdá', 'Cerdán', 'Cerezo', 'Cerro', 'Cervantes',
        'Cervera', 'Céspedes', 'Cid', 'Cifuentes', 'Cisneros', 'Clavero', 'Clemente',
        'Cobo', 'Cobos', 'Coca', 'Codina', 'Coello', 'Colom', 'Coloma', 'Colomer',
        'Coll', 'Collado', 'Comas', 'Company', 'Conde', 'Conesa', 'Contreras',
        'Corbacho', 'Cordero', 'Córdoba', 'Cornejo', 'Corominas', 'Coronado', 'Corral',
        'Correa', 'Cortés', 'Cortina', 'Costa', 'Cózar', 'Criado', 'Crespi', 'Crespo',
        'Cruz', 'Cuadrado', 'Cuéllar', 'Cuenca', 'Cuervo', 'Cuesta', 'Cueto', 'Cuevas',
        'Chacón', 'Chamorro', 'Chaparro', 'Chaves', 'Checa', 'Chico', 'Dalmau',
        'Dávila', 'Daza', 'Delgado', 'Díaz', 'Diego', 'Diéguez', 'Díez', 'Doménech',
        'Domingo', 'Domínguez', 'Donaire', 'Donoso', 'Duarte', 'Dueñas', 'Duque',
        'Durán', 'Echevarría', 'Echeverría', 'Egea', 'Elías', 'Elorza', 'Enríquez',
        'Escalona', 'Escamilla', 'Escobar', 'Escolano', 'Escribano', 'Escrivá',
        'Escudero', 'Espada', 'España', 'Español', 'Esparza', 'Espejo', 'Espinosa',
        'Esteban', 'Esteve', 'Estévez', 'Estrada', 'Expósito', 'Fabra', 'Fábregas',
        'Fabregat', 'Fajardo', 'Falcó', 'Falcón', 'Farré', 'Feijoo', 'Feliu',
        'Fernández', 'Ferrán', 'Ferrández', 'Ferrándiz', 'Ferrando', 'Ferrer',
        'Ferrera', 'Ferrero', 'Ferreras', 'Figueras', 'Figueroa', 'Figuerola', 'Fiol',
        'Flor', 'Flores', 'Folch', 'Fonseca', 'Font', 'Fortuny', 'Franch', 'Francisco',
        'Franco', 'Franch', 'Frías', 'Frutos', 'Fuente', 'Fuentes', 'Fuertes', 'Fuster',
        'Gabaldón', 'Galán', 'Galiano', 'Galindo', 'Galván', 'Gálvez', 'Gallardo',
        'Gallart', 'Gallego', 'Gallo', 'Gámez', 'Gárate', 'Garay', 'Garcés', 'García',
        'Gargallo', 'Garmendia', 'Garrido', 'Garriga', 'Garzón', 'Gascón', 'Gaya',
        'Gelabert', 'Gibert', 'Gil', 'Gilabert', 'Giménez', 'Gimeno', 'Giner', 'Giralt',
        'Girón', 'Girona', 'Gisbert', 'Godoy', 'Goicoechea', 'Gómez', 'Gomila', 'Gomis',
        'González', 'Gonzalo', 'Goñi', 'Gordillo', 'Gracia', 'Granados', 'Grande',
        'Gras', 'Grau', 'Gual', 'Guardia', 'Guardiola', 'Guerra', 'Guerrero',
        'Guijarro', 'Guillén', 'Guitart', 'Gutiérrez', 'Guzmán', 'Haro', 'Heras',
        'Heredia', 'Hernández', 'Hernando', 'Herranz', 'Herrera', 'Herrero', 'Hervás',
        'Hervia', 'Hidalgo', 'Hierro', 'Higueras', 'Hoyos', 'Hoz', 'Huerta', 'Huertas',
        'Huguet', 'Hurtado', 'Ibáñez', 'Ibarra', 'Iborra', 'Iglesia', 'Iglesias',
        'Infante', 'Iniesta', 'Íñigo', 'Iñiguez', 'Iriarte', 'Isern', 'Izaguirre',
        'Izquierdo', 'Jaén', 'Jara', 'Jaume', 'Jáuregui', 'Jerez', 'Jiménez', 'Jódar',
        'Jordá', 'Jordán', 'Jove', 'Jover', 'Juan', 'Juárez', 'Juliá', 'Julián',
        'Jurado', 'Lago', 'Laguna', 'Lamas', 'Landa', 'Lara', 'Larrañaga', 'Larrea',
        'Lasa', 'Lastra', 'Leal', 'Ledesma', 'Leiva', 'León', 'Lerma', 'Lillo',
        'Linares', 'Lobato', 'Lobo', 'López', 'Lorenzo', 'Losa', 'Losada', 'Lozano',
        'Lucas', 'Lucena', 'Luís', 'Luján', 'Lumbreras', 'Luna', 'Luque', 'Luz',
        'Llabrés', 'Lladó', 'Llamas', 'Llano', 'Llanos', 'Lledó', 'Llobet', 'Llopis',
        'Llorens', 'Llorente', 'Lloret', 'Lluch', 'Macías', 'Machado', 'Madrid',
        'Madrigal', 'Maestre', 'Maldonado', 'Malo', 'Mancebo', 'Manjón', 'Manrique',
        'Manso', 'Manuel', 'Manzanares', 'Manzano', 'Marco', 'Marcos', 'Marí', 'Marín',
        'Mariño', 'Mariscal', 'Mármol', 'Marqués', 'Márquez', 'Martí', 'Martín',
        'Martínez', 'Martorell', 'Mas', 'Mascaró', 'Mata', 'Matas', 'Mate', 'Mateo',
        'Mateos', 'Mateu', 'Mayo', 'Mayol', 'Mayoral', 'Maza', 'Medina', 'Meléndez',
        'Melero', 'Mena', 'Méndez', 'Mendizábal', 'Mendoza', 'Menéndez', 'Mercader',
        'Merino', 'Mesa', 'Miguel', 'Milla', 'Millán', 'Mínguez', 'Mir', 'Miralles',
        'Miranda', 'Miró', 'Moles', 'Molina', 'Moliner', 'Molins', 'Moll', 'Monreal',
        'Montalbán', 'Montaña', 'Montenegro', 'Montero', 'Montes', 'Montesinos',
        'Montoya', 'Montserrat', 'Mora', 'Moraleda', 'Morales', 'Morán', 'Morante',
        'Morata', 'Morcillo', 'Morell', 'Moreno', 'Morera', 'Morillo', 'Mosquera',
        'Moya', 'Múgica', 'Mulet', 'Múñiz', 'Muñoz', 'Mur', 'Murcia', 'Murillo', 'Muro',
        'Nadal', 'Naranjo', 'Narváez', 'Navarrete', 'Navarro', 'Navas', 'Nebot',
        'Neira', 'Nevado', 'Nicolau', 'Nicolás', 'Nieto', 'Niño', 'Nogueira', 'Noguera',
        'Nogués', 'Noriega', 'Novoa', 'Núñez', 'Ocaña', 'Ochoa', 'Ojeda', 'Oliva',
        'Olivares', 'Olivé', 'Oliver', 'Olivera', 'Oliveras', 'Olmedo', 'Olmo', 'Oller',
        'Ordóñez', 'Orozco', 'Ortega', 'Ortiz', 'Ortuño', 'Osorio', 'Osuna', 'Otero',
        'Pablo', 'Pacheco', 'Padilla', 'Páez', 'Pagès', 'Palacio', 'Palacios', 'Palau',
        'Palma', 'Palmer', 'Palomar', 'Palomares', 'Palomino', 'Palomo', 'Pallarès',
        'Paniagua', 'Pardo', 'Paredes', 'Pareja', 'Parejo', 'Parra', 'Pascual',
        'Pastor', 'Patiño', 'Pavón', 'Paz', 'Pazos', 'Pedraza', 'Pedrero', 'Pedro',
        'Pedrosa', 'Peinado', 'Peiró', 'Peláez', 'Pelayo', 'Pellicer', 'Peña',
        'Peñalver', 'Peñas', 'Pera', 'Peral', 'Perales', 'Peralta', 'Perea', 'Pereira',
        'Perelló', 'Perera', 'Pérez', 'Pi', 'Pina', 'Pineda', 'Pinedo', 'Pinilla',
        'Pino', 'Pinto', 'Pintor', 'Piña', 'Piñeiro', 'Piñol', 'Piquer', 'Pizarro',
        'Pla', 'Plana', 'Planas', 'Plaza', 'Pol', 'Polo', 'Pomares', 'Pombo', 'Ponce',
        'Pons', 'Pont', 'Porcel', 'Porras', 'Porta', 'Portero', 'Portillo', 'Posada',
        'Pou', 'Poza', 'Pozo', 'Pozuelo', 'Prada', 'Prado', 'Prat', 'Prats', 'Priego',
        'Prieto', 'Puente', 'Puerta', 'Puga', 'Puig', 'Pujadas', 'Pujol', 'Pulido',
        'Quero', 'Querol', 'Quesada', 'Quevedo', 'Quintana', 'Quintanilla', 'Quintero',
        'Quiroga', 'Quirós', 'Ramírez', 'Ramis', 'Ramón', 'Ramos', 'Raya', 'Real',
        'Rebollo', 'Recio', 'Redondo', 'Reguera', 'Reig', 'Reina', 'Requena', 'Revilla',
        'Rey', 'Reyes', 'Riba', 'Ribas', 'Ribera', 'Ribes', 'Ricart', 'Rico', 'Riera',
        'Rincón', 'Río', 'Ríos', 'Ripoll', 'Riquelme', 'Rius', 'Rivero', 'Robledo',
        'Robles', 'Roca', 'Rocamora', 'Rocha', 'Roda', 'Ródenas', 'Rodrigo',
        'Rodríguez', 'Roig', 'Rojas', 'Roldán', 'Roma', 'Román', 'Romero', 'Romeu',
        'Ropero', 'Ros', 'Rosa', 'Rosado', 'Rosales', 'Rosell', 'Roselló', 'Rosselló',
        'Roura', 'Rovira', 'Royo', 'Rozas', 'Ruano', 'Rubio', 'Rueda', 'Ruiz',
        'Saavedra', 'Sabater', 'Sacristán', 'Sáenz', 'Sáez', 'Sainz', 'Sala',
        'Salamanca', 'Salas', 'Salazar', 'Salcedo', 'Saldaña', 'Sales', 'Salgado',
        'Salinas', 'Salmerón', 'Salom', 'Salvà', 'Salvador', 'Samper', 'Sanabria',
        'Sánchez', 'Sancho', 'Sandoval', 'Sanjuan', 'Sanmartín', 'Sanmiguel', 'Sans',
        'Santamaría', 'Santos', 'Sanz', 'Sarabia', 'Sarmiento', 'Sastre', 'Saura',
        'Sebastián', 'Seco', 'Sedano', 'Segarra', 'Segovia', 'Seguí', 'Segura', 'Serna',
        'Serra', 'Serrano', 'Sevilla', 'Sevillano', 'Sierra', 'Silva', 'Simó',
        'Sobrino', 'Sola', 'Solana', 'Solano', 'Solé', 'Soler', 'Solera', 'Solís',
        'Solsona', 'Somoza', 'Soria', 'Soriano', 'Sosa', 'Sotelo', 'Soto', 'Suárez',
        'Sureda', 'Taboada', 'Talavera', 'Tamarit', 'Tamayo', 'Tapia', 'Tejada',
        'Tejedor', 'Tejera', 'Tejero', 'Téllez', 'Tello', 'Tena', 'Tenorio', 'Terrón',
        'Teruel', 'Tirado', 'Toledo', 'Tolosa', 'Tomás', 'Tomé', 'Tormo', 'Toro',
        'Torralba', 'Torre', 'Torrecilla', 'Torrens', 'Torrent', 'Torrents', 'Torres',
        'Torrijos', 'Tovar', 'Trillo', 'Trujillo', 'Tudela', 'Tur', 'Ugarte', 'Ureña',
        'Uría', 'Uriarte', 'Uribe', 'Urrutia', 'Valbuena', 'Valcárcel', 'Valderrama',
        'Valdés', 'Valencia', 'Valenciano', 'Valentín', 'Valenzuela', 'Valera',
        'Valero', 'Valverde', 'Vall', 'Valle', 'Vallejo', 'Vallés', 'Valls', 'Vaquero',
        'Vara', 'Varela', 'Vargas', 'Vázquez', 'Vega', 'Velasco', 'Velázquez', 'Vélez',
        'Vendrell', 'Vera', 'Verdejo', 'Verdú', 'Verdugo', 'Vergara', 'Viana',
        'Vicente', 'Vicens', 'Vidal', 'Vigil', 'Vila', 'Vilanova', 'Vilalta',
        'Vilaplana', 'Vilar', 'Villa', 'Villalba', 'Villalobos', 'Villalonga',
        'Villanueva', 'Villar', 'Villaverde', 'Villegas', 'Villena', 'Viña', 'Viñas',
        'Vives', 'Vizcaíno', 'Yáñez', 'Yuste', 'Zabala', 'Zabaleta', 'Zamora',
        'Zamorano', 'Zapata', 'Zaragoza', 'Zorrilla', 'Zurita'
    )

    prefixes = ('de', 'del')

    @classmethod
    def prefix(cls):
        return cls.random_element(cls.prefixes)