# coding=utf-8
from .. import Provider as JobProvider

# https://vi.wikipedia.org/wiki/Thể_loại:Nghề_nghiệp

class Provider(JobProvider):
    """Job generator"""
    jobs = (
        'Bác sĩ',
        'Bảo mẫu',
        'Bệnh nghề nghiệp',
        'Bồi bàn',
        'Caddie',
        'Cán bộ',
        'Cảnh sát',
        'Cầu thủ bóng đá',
        'Chuyên viên',
        'Công chức',
        'Công chứng viên',
        'Công nhân',
        'Công tác xã hội',
        'Diễn viên',
        'Diễn viên võ thuật',
        'Dược sĩ',
        'Đao phủ',
        'Đầu bếp',
        'Điều dưỡng viên',
        'Điêu khắc đá',
        'Định phí bảo hiểm',
        'Gia sư',
        'Giám đốc (doanh nghiệp)',
        'Giám thị',
        'Giảng viên',
        'Khảo sát xây dựng',
        'Kiến trúc sư',
        'Kỹ sư tư vấn giám sát',
        'Kỹ thuật hệ thống',
        'Lao công',
        'Lập trình viên',
        'Luật sư',
        'Mại dâm',
        'Người bào chữa',
        'Người dẫn chương trình',
        'Người giết mổ gia súc',
        'Người giúp việc',
        'Người hâm mộ',
        'Người mẫu',
        'Người mẫu ảnh',
        'Người mẫu quảng cáo',
        'Nhà làm phim',
        'Nhân viên pha cà phê',
        'Nhiếp ảnh gia',
        'Phóng viên truyền hình',
        'Quản lý xây dựng',
        'Quân sư',
        'Siêu sao',
        'Socialite',
        'Thằng mõ',
        'Tài tử',
        'Thám tử tư',
        'Thiết kế xây dựng',
        'Thợ hồ',
        'Thợ may',
        'Thợ máy',
        'Thợ mỏ',
        'Thợ rèn sắt',
        'Thợ xây',
        'Thủ thư',
        'Thư ký',
        'Thừa phát lại',
        'Tổng thầu xây dựng',
        'Trợ giúp viên pháp lý',
        'Trưởng làng',
        'Tuyên truyền viên',
        'Tứ dân',
        'Tư vấn xây dựng',
        'Võ sĩ giác đấu',
        'Xe ôm',
    )
