from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    first_names_male = [
        "Àdéwálé",
        "Àdéolá",
        "Àdétúndé",
        "Àdéyèmì",
        "Àdéótí",
        "Àjàní",
        "Àjàyí",
        "Àkànní",
        "Àkínníwọ̀",
        "Àkínyẹ́mí",
        "Àkínyẹ́lú",
        "Àkórò",
        "Àlàbí",
        "Àlàdé",
        "Àlàgbàjà",
        "Bàbàjìdé",
        "Babátúndé",
        "Bàmídélé",
        "Bankólé",
        "Bòlúwàjí",
        "Bòlúwátífé",
        "Bùnmí",
        "Bọ̀lúwátító",
        "Dámilárè",
        "Dámilọ́lá",
        "Dẹ̀jì",
        "Dúrọ̀tìmí",
        "Dápọ̀",
        "Dẹ̀jì",
        "Ẹníọ́lá",
        "Fémí",
        "Fọlárìn",
        "Fólájimí",
        "Fúnmiláyọ̀",
        "Fúnṣọ̀",
        "Fọ́láhànmi",
        "Gbọ́láhàn",
        "Gbẹ́misọla",
        "Ifẹ́dáyọ̀",
        "Ifẹ́ọlúwà",
        "Jẹ́lílì",
        "Kéhìndé",
        "Káyọ̀dé",
        "Kọ́láwọlé",
        "Kọ́rẹ́dé",
        "Kùnlé",
        "Lẹ́kàn",
        "Látéẹ̀f",
        "Lánrẹ́",
        "Múyìwá",
        "Níyì",
        "Olúwáséùn",
        "Ọlámídé",
        "Ọlúmidé",
        "Olúwátóbi",
        "Ọlúwáfẹ́mí",
        "Ọláwálé",
        "Pélúmí",
        "Rọ́timí",
        "Ṣẹ́gún",
        "Ṣẹ́yì",
        "Táíwò",
        "Tẹ́mitọpẹ́",
        "Túndé",
        "Tọ́pẹ́",
        "Tólúlópé",
        "Wálé",
        "Wásíù",
        "Yínká",
        "Yẹ́mí",
    ]

    first_names_female = [
        "Ábidémi",
        "Abikẹ",
        "Adédọlá",
        "Adéfúnkẹ",
        "Adéjọkẹ",
        "Ayọ",
        "Ayọdélé",
        "Ayọdún",
        "Ayọjú",
        "Bisọlá",
        "Bọlatọ",
        "Bọ́lá",
        "Búkọla",
        "Dámilọlá",
        "Ẹniọlá",
        "Fọlákẹmi",
        "Fúnkẹ",
        "Fúnmi",
        "Fúnlọlá",
        "Fúnkẹ́",
        "Ifẹ́olúwá",
        "Īmọlẹ́",
        "Ọlájumọkẹ",
        "Olúwábúkọlá",
        "Ọmọlábáké",
        "Ọmọlọlá",
        "Ọmọlúwáfẹ́",
        "Ọmọníyí",
        "Ọpẹ́yẹ́mi",
        "Simisọlá",
        "Títílọlá",
        "Tíwálọlá",
        "Tọlúlopẹ́",
        "Tọ́pẹ́",
        "Ọládúpẹ́",
        "Ọlúwádámilọ́lá",
        "Ọlúwafúnké",
        "Olúwákémi",
        "Ọlúwásèmilọ́lá",
        "Ọmọ́lọ́lá",
        "Ọmọ́lólúwá",
        "Ọmọ́pẹ́",
        "Ọmọ́yẹ́mí",
        "Ọyindámọ́lá",
        "Yẹ́mi",
        "Yẹ́túndé",
        "Yẹ́wándé"
    ]

    first_names = first_names_male + first_names_female

    last_names = [
        'Afọláyán',
        'Ọlábísí',
        'Ládípọ̀',
        'Gbèngà',
        'Ọ̀ṣìbàjọ̀',
        'Ọlúwọlé',
        'Ọlátérú',
        'Ọ̀gúnyẹ́mí',
        'Ọ̀ní',
        'Ọyèdélé',
        'Áláò',
        'Ádẹníyì',
        'Ègbẹ́yẹ́mí',
        'Ọládíjì',
        'Jáyéọlá',
        'Fásọ́yìn',
        'Ọdékú',
        'Ákínọ́lá',
        'Ìlẹ̀ṣàǹmí',
        'Ọyẹkán',
        'Ákíndélé',
        'Ọlálérẹ̀',
        'Ajáyí',
        'Tíjání',
        'Ọwọ́yẹ̀mi',
        'Álábí',
        'Bàkárẹ̀',
        'Áyìndé',
        'Ọlúṣọ́lá',
        'Ọlágúnjú',
        'Adégọ́kẹ',
        'Ośódi',
        'Fásínà',
        'Ọlúmídé',
        'Ádésánmí',
        'Ọlábọ̀dẹ́',
        'Lánrẹ̀',
        'Ọlápẹ̀jú',
        'Ọláboye',
        'Ṣọ́yínká',
        'Ọ̀yẹ̀sínà',
        'Agùnbíàdé',
        'Áwòlọ́wọ̀',
        'Ámúsán',
        'Ọláníyàn',
        'Ágbàjé',
        'Ìgé',
        'Fájẹmìsìn',
        'Ọ̀jọ́',
        'Dárámọ́lá',
        'Alákìjá',
        'Bábálọ́lá',
        'Ṣàngódẹ́yì',
        'Fádípẹ̀',
        'Dúrọ̀ṣínmí',
        'Fásọ́lá',
        'Yúsùf',
        'Ágúnbiádè',
        'Ọ̀ké',
        'Jégédé',
        'Ìlọ́rí',
        'Òyètúndé',
        'Ṣódípọ̀',
        'Ọmọ̀táyọ̀',
        'Ọ̀yẹ́tọ́lá',
        'Ṣọnìbáre',
        'Ìdọ́wú',
        'Kọ́ládé',
        'Ọlúfẹ́mí',
        'Gbàdámọ̀ṣì',
        'Ọlásẹ́ní',
        'Táíwò',
        'Ọgúnkọ́yà',
        'Fátọ̀yìnbọ̀',
        'Ọládéjì',
        'Akíntọ́lá',
        'Ọlánrẹwájú',
        'Sọfọlúwẹ̀',
        'Ọlúwásẹ́yì',
        'Dádá',
        'Áládé',
        'Adébọ́yẹ̀',
        'Ákínyẹ́mí',
        'Ọyèwọlé',
        'Ẹwúọ̀lá',
        'Fábúnmí',
        'Ọlájídé',
        'Fákùnlẹ́',
        'Ádéọtí',
        'Fágbẹ́mí',
        'Ìṣọ́lá',
        'Ọlálẹ́kàn',
        'Akìnfenwà',
        'Ọyẹniyì',
        'Ọyìnlọ́là',
        'Adéyẹmí',
        'Fásúyì',
        'Ádélákún',
        'Arẹ́mu',
        'Ẹjìwùnmí',
        'Ọ̀ṣuntọ́kùn',
        'Fọlawíyọ̀',
        'Ọníkọ́yí',
        'Ọ̀gúnléyè',
        'Ọyẹkúnlẹ́',
        'Àrẹ́gbẹ́ṣọlá',
        'Ádémọ́lá',
        'Ọláwọ̀yé',
        'Ágbétúyi',
        'Ákándé',
        'Ádélẹ́kẹ́ ',
    ]
    prefixes_female = ("Omidan.", "Arábírìn.", "Ọba.", "Ọmọba.")
    prefixes_male = ("Ogbènì.", "Áṣípá.", "Ọ̀tún", "Báṣọ̀run", "Bálọ̀gún")  # arakunrin, osi
