# coding=utf-8

from __future__ import unicode_literals
from collections import OrderedDict

from .. import Provider as ColorProvider

localized = True


class Provider(ColorProvider):
    all_colors = OrderedDict((
        ("Água", "#00FFFF"),
        ("Azul turquesa", "#00CCEE"),
        ("Azul turquesa brilhante", "#00DDFF"),
        ("Azul brasilis", "#00BDCE"),
        ("Azul brasilis brilhante", "#09ACDB"),
        ("Água-marinha", "#7FFFD4"),
        ("Água-marinha média", "#66CDAA"),
        ("Azul celeste pernambucano", "#00A4CD"),
        ("Alizarina", "#E32636"),
        ("Amarelo", "#FFFF00"),
        ("Amarelo brasilis", "#ECDB00"),
        ("Amarelo creme", "#ECD690"),
        ("Amarelo claro", "#FFFFE0"),
        ("Amarelo escuro", "#F2B73F"),
        ("Amarelo esverdeado", "#ADFF2F"),
        ("Amarelo ouro claro", "#FAFAD2"),
        ("Amarelo queimado", "#EEAD2D"),
        ("Âmbar", "#FFBF00"),
        ("Ameixa", "#DDA0DD"),
        ("Ametista", "#9966CC"),
        ("Amêndoa", "#FFEBCD"),
        ("Aspargo", "#7BA05B"),
        ("Azul", "#0000FF"),
        ("Azul alice", "#F0F8FF"),
        ("Azul ardósia", "#6A5ACD"),
        ("Azul ardósia claro", "#8470FF"),
        ("Azul ardósia escuro", "#483D8B"),
        ("Azul ardósia médio", "#7B68EE"),
        ("Azul areado", "#B8CAD4"),
        ("Azul aço", "#4682B4"),
        ("Azul aço claro", "#B0C4DE"),
        ("Azul cadete", "#5F9EA0"),
        ("Azul camarada", "#054F77"),
        ("Azul celeste", "#F0FFFF"),
        ("Azul celeste brilhante", "#007FFF"),
        ("Azul claro", "#ADD8E6"),
        ("Azul cobalto", "#0047AB"),
        ("Azul céu", "#87CEEB"),
        ("Azul céu claro", "#87CEFA"),
        ("Azul céu profundo", "#00BFFF"),
        ("Azul escuro", "#00008B"),
        ("Azul flor de milho", "#6495ED"),
        ("Azul força aérea", "#5D8AA8"),
        ("Azul furtivo", "#1E90FF"),
        ("Azul manteiga", "#a6aa3e"),
        ("Azul marinho", "#120A8F"),
        ("Azul meia-noite", "#191970"),
        ("Azul médio", "#0000CD"),
        ("Azul petróleo", "#084D6E"),
        ("Azul pólvora", "#B0E0E6"),
        ("Azul taparuere", "#248EFF"),
        ("Azul real", "#0000DD"),
        ("Azul violeta", "#8A2BE2"),
        ("Açafrão", "#F4C430"),
        ("Bege", "#F5F5DC"),
        ("Bordô", "#800000"),
        ("Borgonha", "#900020"),
        ("Branco", "#FFFFFF"),
        ("Branco antigo", "#FAEBD7"),
        ("Branco fantasma", "#F8F8FF"),
        ("Branco floral", "#FFFAF0"),
        ("Branco fumaça", "#F5F5F5"),
        ("Branco navajo", "#FFDEAD"),
        ("Brasil", "#A7F432"),
        ("Bronze", "#CD7F32"),
        ("Caramelo", "#8B5742"),
        ("Caqui", "#F0E68C"),
        ("Cardo", "#D8BFD8"),
        ("Carmesim", "#DC143C"),
        ("Carmim", "#712F26"),
        ("Carmim clássico", "#992244"),
        ("Carmim carnáceo", "#960018"),
        ("Castanho avermelhado", "#8B0000"),
        ("Castanho claro", "#D2B48C"),
        ("Cenoura", "#ED9121"),
        ("Cereja", "#DE3163"),
        ("Cereja Hollywood", "#F400A1"),
        ("Chocolate", "#D2691E"),
        ("Ciano", "#00FFFF"),
        ("Ciano claro", "#E0FFFF"),
        ("Ciano escuro", "#008B8B"),
        ("Cinza", "#808080"),
        ("Cinza ardósia", "#708090"),
        ("Cinza ardósia claro", "#778899"),
        ("Cinza ardósia escuro", "#2F4F4F"),
        ("Cinza claro", "#D3D3D3"),
        ("Cinza escuro", "#A9A9A9"),
        ("Cinza fosco", "#696969"),
        ("Cinza médio", "#DCDCDC"),
        ("Cobre", "#B87333"),
        ("Concha", "#FFF5EE"),
        ("Coral", "#FF7F50"),
        ("Coral claro", "#F08080"),
        ("Couro", "#F0DC82"),
        ("Creme", "#FFFDD0"),
        ("Creme de marisco", "#FFE4C4"),
        ("Creme de menta", "#F5FFFA"),
        ("Caqui escuro", "#BDB76B"),
        ("Dainise", "#778899"),
        ("Dourado", "#DAA520"),
        ("Dourado escuro", "#B8860B"),
        ("Dourado pálido", "#EEE8AA"),
        ("Ébano", "#555D50"),
        ("Eminência", "#6C3082"),
        ("Escarlate", "#FF2400"),
        ("Esmeralda", "#50C878"),
        ("Eucalipto", "#44D7A8"),
        ("Fandango", "#B53389"),
        ("Feldspato", "#FDD5B1"),
        ("Ferrugem", "#B7410E"),
        ("Flerte", "#A2006D"),
        ("Fuligem", "#3D2B1F"),
        ("Fúchsia", "#FF00FF"),
        ("Grená", "#831D1C"),
        ("Gainsboro", "#DCDCDC"),
        ("Glitter", "#E6E8FA"),
        ("Herbal", "#2E8B57"),
        ("Heliotrópio", "#DF73FF"),
        ("Índigo", "#4B0082"),
        ("Independência", "#4C516D"),
        ("Iris", "#5A4FCF"),
        ("Jade", "#00A86B"),
        ("Jambo", "#FF4500"),
        ("Jasmine", "#F8DE7E"),
        ("Kiwi", "#8EE53F"),
        ("Kobi", "#E79FC4"),
        ("Kobicha", "#6B4423"),
        ("Laranja", "#FFA500"),
        ("Laranja escuro", "#FF8C00"),
        ("Laranja claro", "#FFB84D"),
        ("Lavanda", "#E6E6FA"),
        ("Lavanda avermelhada", "#FFF0F5"),
        ("Lilás", "#C8A2C8"),
        ("Limão", "#00FF00"),
        ("Lima", "#FDE910"),
        ("Linho", "#FAF0E6"),
        ("Madeira", "#DEB887"),
        ("Magenta", "#FF00FF"),
        ("Magenta escuro", "#8B008B"),
        ("Malva", "#E0B0FF"),
        ("Mamão batido", "#FFEFD5"),
        ("Maná", "#F0FFF0"),
        ("Marfim", "#FFFFF0"),
        ("Marrom", "#964b00"),
        ("Marrom amarelado", "#F4A460"),
        ("Marrom claro", "#A52A2A"),
        ("Marrom rosado", "#BC8F8F"),
        ("Marrom sela", "#8B4513"),
        ("Milho", "#FBEC5D"),
        ("Milho Claro", "#FFF8DC"),
        ("Mocassim", "#FFE4B5"),
        ("Mostarda", "#FFDB58"),
        ("Naval", "#000080"),
        ("Neve", "#FFFAFA"),
        ("Nyanza", "#E9FFDB"),
        ("Ocre", "#CC7722"),
        ("Oliva", "#808000"),
        ("Oliva escura", "#556B2F"),
        ("Oliva parda", "#6B8E23"),
        ("Orquídea", "#DA70D6"),
        ("Orquídea escura", "#9932CC"),
        ("Orquídea média", "#BA55D3"),
        ("Ouro", "#FFD700"),
        ("Pardo", "#CD853F"),
        ("Pardo escuro", "#CC6600"),
        ("Prata", "#C0C0C0"),
        ("Preto", "#000000"),
        ("Pêssego", "#FFDAB9"),
        ("Púrpura", "#800080"),
        ("Púrpura média", "#9370DB"),
        ("Quantum", "#111111"),
        ("Quartz", "#51484F"),
        ("Renda antiga", "#FDF5E6"),
        ("Rosa", "#FFCBDB"),
        ("Rosa brilhante", "#FF007F"),
        ("Rosa Choque", "#FC0FC0"),
        ("Rosa amoroso", "#CD69CD"),
        ("Rosa claro", "#FFB6C1"),
        ("Rosa danação", "#DA69A1"),
        ("Rosa embaçado", "#FFE4E1"),
        ("Rosa forte", "#FF69B4"),
        ("Rosa profundo", "#FF1493"),
        ("Roxo", "#993399"),
        ("Roxo brasilis", "#8A008A"),
        ("Rútilo", "#6D351A"),
        ("Salmão", "#FA7F72"),
        ("Salmão claro", "#FFA07A"),
        ("Salmão escuro", "#E9967A"),
        ("Siena", "#FF8247"),
        ("Sépia", "#705714"),
        ("Tangerina", "#F28500"),
        ("Terracota", "#E2725B"),
        ("Tijolo refratário", "#B22222"),
        ("Tomate", "#FF6347"),
        ("Trigo", "#F5DEB3"),
        ("Triássico", "#FF2401"),
        ("Turquesa", "#40E0D0"),
        ("Turquesa escura", "#00CED1"),
        ("Turquesa média", "#48D1CC"),
        ("Turquesa pálida", "#AFEEEE"),
        ("Ube", "#8878C3"),
        ("Urucum", "#EC2300"),
        ("Verde", "#008000"),
        ("Verde espectro", "#00FF00"),
        ("Verde amarelado", "#9ACD32"),
        ("Verde claro", "#90EE90"),
        ("Verde escuro", "#006400"),
        ("Verde floresta", "#228B22"),
        ("Verde fluorescente", "#CCFF33"),
        ("Verde lima", "#32CD32"),
        ("Verde grama", "#7CFC00"),
        ("Verde mar claro", "#20B2AA"),
        ("Verde mar escuro", "#8FBC8F"),
        ("Verde mar médio", "#3CB371"),
        ("Verde militar", "#78866B"),
        ("Verde Paris", "#7FFF00"),
        ("Verde primavera", "#00FF7F"),
        ("Verde primavera médio", "#00FA9A"),
        ("Verde pálido", "#98FB98"),
        ("Verde-azulado", "#008080"),
        ("Vermelho", "#FF0000"),
        ("Vermelho enegrecido", "#550000"),
        ("Vermelho escuro", "#8B0000"),
        ("Vermelho indiano", "#CD5C5C"),
        ("Vermelho violeta", "#D02090"),
        ("Vermelho violeta médio", "#C71585"),
        ("Vermelho violeta pálido", "#DB7093"),
        ("Violeta", "#EE82EE"),
        ("Violeta escuro", "#9400D3"),
        ("Violeta claro", "#F8CBF8"),
        ("Wageningen Verde", "#34B233"),
        ("Wenge", "#645452"),
        ("Wisteria", "#C9A0DC"),
        ("Xanadu", "#738678"),
        ("Yale Blue", "#0F4D92"),
        ("Yellow (process)", "#FFEF00"),
        ("Yellow (RYB)", "#FEFE33"),
        ("Yellow-green", "#9ACD32"),
        ("Zaffre", "#0014A8"),
        ("Zomp", "#39A78E"),
        ("Zinco", "#E2DDF0"),
    ))

    safe_colors = (
        'preto', 'marrom', 'verde', 'azul escuro', 'verde escuro',
        'roxo', 'laranja', 'verde claro', 'azul', 'rosa', 'violeta',
        'cinza', 'amarelo', 'magenta', 'ciano', 'branco',
    )
