# coding=utf-8
from __future__ import unicode_literals
from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        '{{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{first_name_female}} {{last_name}} {{last_name}}',
        '{{first_name_female}} {{last_name}} {{last_name}}',
        '{{prefix_female}} {{first_name_female}} {{first_name_female}} {{last_name}}',
        '{{prefix_female}} {{first_name_female}} {{first_name_female}} {{last_name}} {{last_name}}',
        '{{prefix_female}} {{first_name_female}} {{last_name}} {{last_name}}'
    )

    formats_male = (
        '{{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{first_name_male}} {{last_name}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{prefix_male}} {{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{prefix_male}} {{first_name_male}} {{first_name_male}} {{last_name}}'
    )

    formats = formats_male + formats_female

    first_names_female = ('Abiye', 'Acarkan', 'Adal', 'Adila', 'Adviye',
        'Afife', 'Ahter', 'Akay', 'Akgüneş', 'Akise', 'Akmaral', 'Aksoy',
        'Akyıldız', 'Alabezek', 'Alaz', 'Algış', 'Alize', 'Almast', 'Alsoy',
        'Altınbike', 'Altınçiçek', 'Alışık', 'Amre', 'Anargül', 'Anka', 'Aral',
        'Armahan', 'Arziye', 'Arıpınar', 'Asiman', 'Asliye', 'Asu', 'Atanur',
        'Atiyye', 'Avunç', 'Ayasun', 'Aybet', 'Aycagül', 'Aydar', 'Ayduru',
        'Aygönenç', 'Ayhan', 'Aykut', 'Aylil', 'Aynilhayat', 'Aynımah',
        'Aysema', 'Aysevim', 'Aysuna', 'Ayten', 'Aytöz', 'Ayyaruk', 'Ayçan',
        'Ayülker', 'Ayşeana', 'Ayşenur', 'Azade', 'Azize', 'Açılay', 'Ağbegim',
        'Aşhan', 'Badegül', 'Bahtinur', 'Balca', 'Ballı', 'Banü', 'Basriye',
        'Bağdat', 'Bediriye', 'Begim', 'Behiza', 'Belgizar', 'Belkize', 'Benek',
        'Benice', 'Beray', 'Bergen', 'Beriye', 'Berrin', 'Besey', 'Beste',
        'Beyhatun', 'Bezek', 'Bidayet', 'Bilay', 'Bilginur', 'Bilkay', 'Binay',
        'Birben', 'Birgül', 'Birsan', 'Bitül', 'Burcuhan', 'Buşra', 'Büreyre',
        'Büşranur', 'Canan', 'Canfeza', 'Cannur', 'Canseven', 'Canur', 'Cedide',
        'Cemiyle', 'Cevale', 'Ceyhun', 'Cihan', 'Cuheyna', 'Damlanur', 'Deha',
        'Deniz', 'Deryanur', 'Değer', 'Dilara', 'Dilcan', 'Dilfeza', 'Dilhuş',
        'Dilsitan', 'Dilşat', 'Divan', 'Doğannur', 'Duha', 'Durgadin',
        'Dursadiye', 'Duyguhan', 'Döner', 'Dürrüşehvar', 'Ecegül', 'Edaviye',
        'Efil', 'Egenur', 'Elamiye', 'Elgin', 'Elifnur', 'Elvan', 'Emal',
        'Emine.', 'Emiş', 'Enfes', 'Erbay', 'Erem', 'Ergül', 'Eriş', 'Ervaniye',
        'Esengün', 'Esmanperi', 'Esna', 'Evde', 'Evrim', 'Ezgin', 'Eşim',
        'Fadile', 'Fadıla', 'Faize', 'Fatigül', 'Fatinur', 'Fatmanur', 'Fayize',
        'Feden', 'Fehmiye', 'Ferahdiba', 'Feraye', 'Ferhan', 'Ferinaz',
        'Fermuta', 'Feryas', 'Feyha', 'Feyzin', 'Fidaye', 'Fildan', 'Firdevis',
        'Fitnat', 'Fügen', 'Gabel', 'Ganiye', 'Gelengül', 'Gilman', 'Goncafer',
        'Gök', 'Gökperi', 'Gökçe', 'Göli', 'Görsev', 'Gözem', 'Gül', 'Gülay',
        'Gülbani', 'Gülbeyan', 'Gülbiye', 'Gülcegün', 'Güldam', 'Gülder',
        'Güldünya', 'Gülenay', 'Güler', 'Gülev', 'Gülfari', 'Gülfeza', 'Gülgen',
        'Gülgüzel', 'Gülhisar', 'Gülinaz', 'Gülkadın', 'Güllühan', 'Gülmisal',
        'Gülnaziye', 'Gülper', 'Gülsalın', 'Gülselin', 'Gülseren', 'Gülsevil',
        'Gülsiye', 'Gülsü', 'Gülter', 'Gülzadiye', 'Gülçe', 'Gülözge', 'Gülüs',
        'Gülşa', 'Gülşeref', 'Günar', 'Günebakan', 'Güngören', 'Günsel',
        'Günver', 'Gürcüye', 'Gürten', 'Güverçin', 'Güzey', 'Habibe', 'Hacile',
        'Hadrey', 'Hafıza', 'Halenur', 'Haliye', 'Hamiyet', 'Hanbiken', 'Hanim',
        'Hansultan', 'Harbinaz', 'Hasgül', 'Hasret', 'Hatin', 'Havali', 'Havse',
        'Hayel', 'Hayrünnisa', 'Hazine', 'Hekime', 'Henife', 'Heva', 'Hezniye',
        'Hilayda', 'Hinet', 'Hoşkadem', 'Huban', 'Hurican', 'Hurşide', 'Hüda',
        'Hümeyra', 'Hürmet', 'Hürüyet', 'Hüsnühâl', 'Ildız', 'Irıs', 'Işin',
        'Işın', 'Jaruthip', 'Kader', 'Kadınana', 'Kandef', 'Kardelen', 'Kaver',
        'Kefser', 'Kerime', 'Kezban', 'Kifaye', 'Kitan', 'Koncagül', 'Kumral',
        'Kutgün', 'Kutun', 'Kâzime', 'Kübran', 'Kısmet', 'Laika', 'Laze',
        'Lerze', 'Leyli', 'Lezize', 'Limon', 'Lâle', 'Lüfen', 'Macide',
        'Mahigül', 'Mahnaz', 'Mahter', 'Maksüde', 'Masume', 'Maynur', 'Maşide',
        'Mecide', 'Mefharet', 'Mehdiye', 'Mehrigül', 'Melaha', 'Meleknur',
        'Melikkan', 'Melûl', 'Menfeat', 'Menişan', 'Merba', 'Merim', 'Merva',
        'Meryeme', 'Mesude', 'Meveddet', 'Mevlüdiye', 'Meyhanim', 'Mezide',
        'Mihrab', 'Mihriye', 'Minibe', 'Miray', 'Misra', 'Miyesser', 'Muarra',
        'Mufide', 'Muhiye', 'Mujde', 'Mukbile', 'Musaffa', 'Muvahhide',
        'Mübetcel', 'Mücevher', 'Müferrih', 'Müjde', 'Mükrüme', 'Mümtaze',
        'Münezzer', 'Müret', 'Müsemma', 'Müveddet', 'Müğber', 'Müşüre', 'Nades',
        'Nafile', 'Naide', 'Nalân', 'Narhanim', 'Nasiba', 'Natalia', 'Naz',
        'Nazende', 'Nazi', 'Nazimet', 'Nazlihan', 'Nazıdil', 'Nebiha',
        'Necilal', 'Necva', 'Nefaret', 'Nefiye', 'Nejdet', 'Neptün', 'Neriban',
        'Nesfe', 'Neslinur', 'Neval', 'Nevgin', 'Nevise', 'Nevsale', 'Neyran',
        'Nezengül', 'Nezize', 'Neşrin', 'Nihan', 'Nilcan', 'Nili', 'Nirgül',
        'Niğmet', 'Nura', 'Nurbanu', 'Nurda', 'Nurdeniz', 'Nurey', 'Nurgil',
        'Nurhayet', 'Nuriyet', 'Nurmelek', 'Nurseda', 'Nurser', 'Nursim',
        'Nurtaç', 'Nurveren', 'Nurşan', 'Nüdret', 'Nürice', 'Oguş', 'Oluş',
        'Orçin', 'Paksu', 'Paye', 'Pekkan', 'Pembesin', 'Peren', 'Perinur',
        'Permun', 'Pesent', 'Piran', 'Pürçek', 'Rabbiye', 'Rafia', 'Rahiye',
        'Rakide', 'Rana', 'Rayla', 'Rebihat', 'Refet', 'Rehime', 'Rengül',
        'Revza', 'Rezin', 'Risalet', 'Rojnu', 'Ruhide', 'Ruhugül', 'Rumeysa',
        'Rümeysa', 'Rıfkıye', 'Sabihe', 'Sabır', 'Sadeti', 'Sadiye', 'Safinaz',
        'Safura', 'Sahil', 'Saire', 'Salimet', 'Samahat', 'Sanavber', 'Sanur',
        'Sarya', 'Satıa', 'Saygın', 'Saçı', 'Sebigül', 'Seblâ', 'Sedife',
        'Sefer', 'Sehel', 'Sejda', 'Selcen', 'Selime', 'Selmin', 'Selvi',
        'Selçuk', 'Semat', 'Semine', 'Semrin', 'Seniha', 'Serda', 'Serfinaz',
        'Serma', 'Sernur', 'Servinaz', 'Sevcan', 'Sevdinar', 'Sevgen',
        'Sevginur', 'Sevican', 'Sevim', 'Sevla', 'Sevsevil', 'Seyhan',
        'Seyyide', 'Sezen', 'Seçgül', 'Sidar', 'Silanur', 'Simber', 'Simten',
        'Sirap', 'Siti', 'Solma', 'Sonnur', 'Soykan', 'Subutiye', 'Sultane',
        'Sunay', 'Susam', 'Söyler', 'Süheyda', 'Süleyla', 'Sümerya', 'Süner',
        'Süsen', 'Süzer', 'Sırriye', 'Tagangül', 'Talibe', 'Tan', 'Tangül',
        'Tanses', 'Tanyu', 'Tasvir', 'Tayyibe', 'Taçnur', 'Teknaz', 'Temime',
        'Tercan', 'Teybet', 'Ticen', 'Tomurcuk', 'Tule', 'Turcein', 'Tutkucan',
        'Tuğçe', 'Tülin', 'Türcan', 'Türknur', 'Tüzenur', 'Ufukay', 'Ummahani',
        'Umuşan', 'Uyanser', 'Uğur', 'Vacibe', 'Varlık', 'Vecide', 'Vefia',
        'Verde', 'Vezrife', 'Vildane', 'Yahşi', 'Yalın', 'Yasemen', 'Yazgül',
        'Yaşar', 'Yekbun', 'Yepelek', 'Yeşil', 'Yosma', 'Yurdaser', 'Yurtseven',
        'Yücel', 'Yıldız', 'Zahfer', 'Zaliha', 'Zebirce', 'Zehranur', 'Zelha',
        'Zemzem', 'Zerafet', 'Zeride', 'Zevlüde', 'Zeyno', 'Zilfa', 'Zinnure',
        'Zubeyde', 'Zöhrehan', 'Züheyla', 'Zülbiye', 'Zülfüye', 'Zümre',
        'Âlemşah', 'Çalım', 'Çağlar', 'Çevregül', 'Çilga', 'Çisem', 'Çolpan',
        'Ömriye', 'Öncel', 'Örfiye', 'Övün', 'Özay', 'Özbilge', 'Özdeş', 'Özge',
        'Özgün', 'Özlem', 'Özpetek', 'Özyurt', 'Üge', 'Ülke', 'Ülküm',
        'Ümmahan', 'Ümmühan', 'Ümray', 'Ünal', 'Ünsever', 'Ürper', 'Üçgül',
        'İde', 'İhsan', 'İklim', 'İldeş', 'İlkbahar', 'İlklima', 'İlper',
        'İmge', 'İmrihan', 'İncifir', 'İnsaf', 'İrfan', 'İslime', 'İsra',
        'İzel', 'İçimbike', 'Şadıman', 'Şahdiye', 'Şahinder', 'Şahnuray',
        'Şahıgül', 'Şamiha', 'Şayan', 'Şazime', 'Şefiye', 'Şehreban', 'Şehza',
        'Şelâle', 'Şemsinisa', 'Şendoğan', 'Şennur', 'Şeref', 'Şerman',
        'Şevketfeza', 'Şeyda', 'Şilan', 'Şirivan', 'Şöhret', 'Şüküfe'

    )

    first_names_male = (
        'Abidin', 'Acar', 'Acaralp', 'Acarsoy', 'Acun', 'Adem', 'Adil', 'Adnan',
        'Agah', 'Aktuğ', 'Ali', 'Alican', 'Alp', 'Arat', 'Arda', 'Baha', 'Bahadır',
        'Bahri', 'Balaban', 'Baran', 'Barbaros', 'Barın', 'Barış', 'Barlas',
        'Bartu', 'Batu', 'Berk', 'Berkay', 'Birkan', 'Boğaç', 'Bora', 'Buğra',
        'Bülent', 'Çağan', 'Çağatay', 'Çağdan', 'Çağdaş', 'Çağlar', 'Çağlayan',
        'Cahit', 'Çakır', 'Can', 'Candemir', 'Caner', 'Cankut', 'Canol', 'Canpolat',
        'Cansın', 'Cantekin', 'Çelebi', 'Çelik', 'Cem', 'Cemil', 'Cengiz', 'Ceyhun',
        'Cihan', 'Çınar', 'Coşkun', 'Dağhan', 'Dağtekin', 'Deha', 'Demirel',
        'Demirkan', 'Demirol', 'Deran', 'Dinçer', 'Doğan', 'Doğuş', 'Doruk',
        'Ecevit', 'Edip', 'Edis', 'Ediz', 'Efdal', 'Efe', 'Efehan', 'Ege', 'Egemen',
        'Ekber', 'Ekrem', 'Emin', 'Emir', 'Emrah', 'Emre', 'Ender', 'Enes', 'Enez',
        'Eray', 'Erdinç', 'Evren', 'Fahir', 'Faik', 'Faruk', 'Fazıl', 'Ferdi',
        'Ferhat', 'Feridun', 'Ferit', 'Ferruh', 'Fethi', 'Fevzi', 'Feyyaz', 'Feyzi',
        'Fikri', 'Fırat', 'Fuat', 'Galip', 'Gani', 'Gazi', 'Gediz', 'Gençay',
        'Gencer', 'Giray', 'Gökalp', 'Gökay', 'Gökbay', 'Gökçe', 'Gökhan', 'Güralp',
        'Hakan', 'Haldun', 'Halil', 'Halim', 'Halit', 'Haluk', 'Hamit', 'Hamza',
        'Harun', 'Hasan', 'Hayati', 'Haydar', 'Hayrettin', 'Hayri', 'Hazar',
        'Hıfzı', 'Hıncal', 'Hüseyin', 'İbrahim', 'İdris', 'İhsan', 'İldeniz',
        'Ilgaz', 'İlhami', 'İlhan', 'İlkay', 'İlker', 'İlyas', 'Kaan', 'Kadir',
        'Kadri', 'Kahraman', 'Kamer', 'Kamil', 'Kandemir', 'Kasım', 'Kaya',
        'Kayahan', 'Kazım', 'Kemal', 'Kerem', 'Kerim', 'Latif', 'Levent', 'Lütfi',
        'Macit', 'Mahir', 'Mahmut', 'Mahzun', 'Malik', 'Malkoç', 'Mazhar', 'Mecnun',
        'Mehmet', 'Melih', 'Melik', 'Memduh', 'Menderes', 'Mert', 'Mesut', 'Mete',
        'Metin', 'Murat', 'Naci', 'Nail', 'Naim', 'Namık', 'Nazım', 'Nazmi',
        'Necat', 'Necati', 'Necdet', 'Necip', 'Necmi', 'Nedim', 'Nejat', 'Neşet',
        'Nevzat', 'Nezih', 'Nihat', 'Niyazi', 'Nizam', 'Nizami', 'Nuri', 'Oben',
        'Öcal', 'Oğulcan', 'Ogün', 'Öğüt', 'Oğuz', 'Okan', 'Okay', 'Ökmen', 'Oktay',
        'Okyar', 'Olcay', 'Olcayto', 'Olcaytuğ', 'Ömer', 'Önal', 'Önay', 'Önder',
        'Öner', 'Övünç', 'Özalp', 'Ozan', 'Özgür', 'Pars', 'Paşa', 'Peker', 'Polat',
        'Poyraz', 'Rafet', 'Ragıp', 'Rahman', 'Raif', 'Rakım', 'Ramazan', 'Rami',
        'Ramiz', 'Rasim', 'Rasin', 'Raşit', 'Rauf', 'Recai', 'Recep', 'Refik',
        'Reha', 'Remzi', 'Renan', 'Reşat', 'Rıdvan', 'Rıfat', 'Rıfkı', 'Rıza',
        'Rüzgar', 'Sabri', 'Sadi', 'Şadi', 'Safa', 'Şafak', 'Şahan', 'Şahin',
        'Samet', 'Sancar', 'Şansal', 'Sarp', 'Savaş', 'Sedat', 'Şefik', 'Semih',
        'Şemsi', 'Şener', 'Şengül', 'Şenol', 'Sercan', 'Serdar', 'Şeref', 'Serhat',
        'Şerif', 'Serkan', 'Soner', 'Suat', 'Tahsin', 'Talat', 'Talip', 'Talu',
        'Tamer', 'Tandoğan', 'Taner', 'Tanju', 'Tarık', 'Tarkan', 'Tayfun',
        'Teoman', 'Timuçin', 'Tufan', 'Tuğrul', 'Tümer', 'Ufuk', 'Uğur', 'Uğurcan',
        'Uğurtan', 'Ulaş', 'Ulu', 'Uluç', 'Ümit', 'Umut', 'Ünal', 'Ünalan', 'Ünalp',
        'Üner', 'Ünol', 'Ünsal', 'Ünver', 'Uras', 'Vahdet', 'Vahit', 'Vargın',
        'Varol', 'Vecihi', 'Vedat', 'Vefa', 'Vehbi', 'Veli', 'Volkan', 'Vural',
        'Yağız', 'Yağmur', 'Yalçın', 'Yalın', 'Yalvaç', 'Yaman', 'Yamaner', 'Yankı',
        'Yaşar', 'Yavuz', 'Yener', 'Yetkin', 'Yiğit', 'Yıldıray', 'Yıldırım',
        'Yılmaz', 'Yücel', 'Yüksel', 'Yunus', 'Yurdakul', 'Yusuf', 'Zafer', 'Zeki',
        'Zihni', 'Zikri', 'Ziya'
    )

    first_names = first_names_male + first_names_female

    last_names = (
        'Abacı', 'Abadan', 'Adıvar', 'Akar', 'Akay', 'Akaydın', 'Akbulut', 'Akgül',
        'Akman', 'Akyürek', 'Akyüz', 'Akşit', 'Alnıaçık', 'Alyanak', 'Arıcan',
        'Arslanoğlu', 'Ayaydın', 'Aybar', 'Aydan', 'Ağaoğlu', 'Aşıkoğlu', 'Babacan',
        'Babaoğlu', 'Bademci', 'Bakırcıoğlu', 'Balcı', 'Barbarosoğlu', 'Baturalp',
        'Bayındır', 'Baykam', 'Başoğlu', 'Berberoğlu', 'Beşerler', 'Beşok', 'Biçer',
        'Bolatlı', 'Bulak', 'Dalkıran', 'Dağdaş', 'Dağlaroğlu', 'Demirbaş',
        'Demirel', 'Dizdar', 'Doğan', 'Durak', 'Durmaz', 'Egeli', 'Ekici', 'Erbay',
        'Erberk', 'Erbulak', 'Erdoğan', 'Erez', 'Erginsoy', 'Erkekli', 'Ertepınar',
        'Ertürk', 'Erçetin', 'Evliyaoğlu', 'Gökgöz', 'Gönültaş', 'Gümüşpala',
        'Hakyemez', 'Hamzaoğlu', 'Ilıcalı', 'Kahveci', 'Karabulut', 'Karaböcek',
        'Karadaş', 'Karaduman', 'Karaer', 'Karatepe', 'Kasapoğlu', 'Keseroğlu',
        'Keçeci', 'Kılıççı', 'Kıraç', 'Kocabıyık', 'Koç', 'Koçyiğit', 'Kunt',
        'Kunter', 'Kurutluoğlu', 'Kuzucu', 'Körmükçü', 'Mertoğlu', 'Okumuş', 'Okur',
        'Ozansoy', 'Polat', 'Sabuncu', 'Sadıklar', 'Samancı', 'Sandalcı',
        'Sarıoğlu', 'Saygıner', 'Sepetçi', 'Sinanoğlu', 'Solmaz', 'Sözeri',
        'Süleymanoğlu', 'Tahincioğlu', 'Tanrıkulu', 'Tazegül', 'Taşlı', 'Taşçı',
        'Tekand', 'Tekelioğlu', 'Tokatlıoğlu', 'Tokgöz', 'Topaloğlu', 'Topçuoğlu',
        'Toraman', 'Tunaboylu', 'Tunçeri', 'Tuğlu', 'Tuğluk', 'Türkdoğan',
        'Türkyılmaz', 'Tütüncü', 'Tüzün', 'Uca', 'Uluhan', 'Uzun', 'Uzunoğlu',
        'Velioğlu', 'Yalçın', 'Yazıcı', 'Yetkiner', 'Yeşilkaya', 'Yıldırım',
        'Yıldızoğlu', 'Yılmazer', 'Yorulmaz', 'Âdem', 'Çakır', 'Çamdalı',
        'Çapanoğlu', 'Çatalbaş', 'Çağıran', 'Çebi', 'Çetin', 'Çetiner', 'Çevik',
        'Çörekçi', 'Önür', 'Örge', 'Öymen', 'Özbey')

    prefixes_female = ('Bayan', 'Dr.')
    prefixes_male = ('Bay', 'Dr.')

    prefixes = prefixes_female + prefixes_male
