from .. import Provider as AddressProvider


class Provider(AddressProvider):
    cities = (
        "Warszawa",
        "Kraków",
        "Łódź",
        "Wrocław",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Katowice",
        "Białystok",
        "Gdynia",
        "Częstochowa",
        "Radom",
        "Sosnowiec",
        "Toruń",
        "Kielce",
        "Gliwice",
        "Rzeszów",
        "Zabrze",
        "Bytom",
        "Olsztyn",
        "Bielsko-Biała",
        "Ruda Śląska",
        "Rybnik",
        "Tychy",
        "Dąbrowa Górnicza",
        "Gorzów Wielkopolski",
        "Elbląg",
        "Płock",
        "Opole",
        "Wałbrzych",
        "Zielona Góra",
        "Włocławek",
        "Tarnów",
        "Chorzów",
        "Koszalin",
        "Kalisz",
        "Legnica",
        "Grudziądz",
        "Słupsk",
        "Jaworzno",
        "Jastrzębie-Zdrój",
        "Nowy Sącz",
        "Jelenia Góra",
        "Konin",
        "Piotrków Trybunalski",
        "Siedlce",
        "Inowrocław",
        "Mysłowice",
        "Piła",
        "Lubin",
        "Ostrów Wielkopolski",
        "Ostrowiec Świętokrzyski",
        "Gniezno",
        "Stargard Szczeciński",
        "Siemianowice Śląskie",
        "Suwałki",
        "Głogów",
        "Pabianice",
        "Chełm",
        "Zamość",
        "Tomaszów Mazowiecki",
        "Leszno",
        "Przemyśl",
        "Stalowa Wola",
        "Kędzierzyn-Koźle",
        "Łomża",
        "Żory",
        "Mielec",
        "Tarnowskie Góry",
        "Tczew",
        "Bełchatów",
        "Świdnica",
        "Ełk",
        "Pruszków",
        "Będzin",
        "Biała Podlaska",
        "Zgierz",
        "Piekary Śląskie",
        "Racibórz",
        "Legionowo",
        "Ostrołęka",
        "Świętochłowice",
        "Starachowice",
        "Zawiercie",
        "Wejherowo",
        "Puławy",
        "Wodzisław Śląski",
        "Starogard Gdański",
        "Skierniewice",
        "Tarnobrzeg",
        "Skarżysko-Kamienna",
        "Radomsko",
        "Krosno",
        "Rumia",
        "Dębica",
        "Kołobrzeg",
        "Kutno",
        "Nysa",
        "Ciechanów",
        "Otwock",
        "Piaseczno",
        "Zduńska Wola",
        "Sieradz",
        "Świnoujście",
        "Żyrardów",
        "Szczecinek",
        "Świdnik",
        "Chojnice",
        "Nowa Sól",
        "Oświęcim",
        "Bolesławiec",
        "Mińsk Mazowiecki",
        "Mikołów",
        "Jarosław",
        "Sanok",
        "Knurów",
        "Malbork",
        "Żary",
        "Kwidzyn",
        "Chrzanów",
        "Sopot",
        "Sochaczew",
        "Wołomin",
        "Oleśnica",
        "Brzeg",
        "Olkusz",
        "Jasło",
        "Cieszyn",
        "Kraśnik",
        "Lębork",
        "Czechowice-Dziedzice",
        "Dzierżoniów",
        "Ostróda",
        "Police",
        "Nowy Targ",
        "Iława",
        "Czeladź",
        "Myszków",
        "Żywiec",
        "Zgorzelec",
        "Oława",
        "Bielawa",
        "Swarzędz",
        "Mława",
        "Ząbki",
        "Łuków",
        "Augustów",
        "Śrem",
        "Bochnia",
        "Luboń",
        "Giżycko",
        "Grodzisk Mazowiecki",
        "Łowicz",
        "Krotoszyn",
        "Września",
        "Turek",
        "Pruszcz Gdański",
        "Brodnica",
        "Gorlice",
        "Czerwionka-Leszczyny",
        "Kłodzko",
        "Marki",
        "Nowy Dwór Mazowiecki",
        "Kętrzyn",
        "Zakopane",
        "Wyszków",
        "Biłgoraj",
        "Żagań",
        "Bielsk Podlaski",
        "Świecie",
        "Wałcz",
        "Jarocin",
        "Pszczyna",
        "Wągrowiec",
        "Szczytno",
        "Białogard",
        "Sandomierz",
        "Bartoszyce",
        "Kluczbork",
        "Lubliniec",
        "Skawina",
        "Jawor",
        "Kościan",
        "Wieluń",
        "Kościerzyna",
        "Nowa Ruda",
        "Świebodzice",
        "Koło",
        "Piastów",
        "Goleniów",
        "Ostrów Mazowiecka",
        "Polkowice",
        "Lubartów",
        "Zambrów",
        "Płońsk",
        "Reda",
        "Łaziska Górne",
        "Środa Wielkopolska",
    )

    street_prefixes_feminine = (
        "ulica",
        "aleja",
    )

    street_prefixes_masculine = ("plac",)

    street_prefixes = street_prefixes_feminine + street_prefixes_masculine

    streets_adjective_feminine = (
        "Polna",
        "Leśna",
        "Słoneczna",
        "Krótka",
        "Szkolna",
        "Ogrodowa",
        "Lipowa",
        "Brzozowa",
        "Łąkowa",
        "Kwiatowa",
        "Sosnowa",
        "Kościelna",
        "Akacjowa",
        "Parkowa",
        "Zielona",
        "Kolejowa",
        "Sportowa",
        "Dębowa",
        "Cicha",
        "Spokojna",
        "Klonowa",
        "Spacerowa",
        "Swierkowa",
        "Kasztanowa",
        "Nowa",
        "Piaskowa",
        "Rózana",
        "Topolowa",
        "Wiśniowa",
        "Dworcowa",
        "Wiejska",
        "Graniczna",
        "Długa",
        "Wrzosowa",
        "Boczna",
        "Wąska",
        "Wierzbowa",
        "Jaśminowa",
        "Wspólna",
        "Modrzewiowa",
        "Poprzeczna",
        "Wesoła",
        "Pogodna",
        "Bukowa",
        "Sadowa",
        "Górna",
        "Jodłowa",
        "Glówna",
        "Młyńska",
        "Strażacka",
        "Jesionowa",
        "Przemysłowa",
        "Osiedlowa",
        "Wiosenna",
        "Południowa",
        "Malinowa",
        "Stawowa",
        "Reymonta",
        "Zacisze",
        "Cmentarna",
        "Okrężna",
        "Miła",
        "Jasna",
        "Wodna",
        "Zamkowa",
        "Warszawska",
        "Miodowa",
        "Krzywa",
        "Dolna",
        "Podgórna",
        "Kreta",
        "Jarzębinowa",
        "Targowa",
        "Prosta",
        "Spółdzielcza",
        "Jagodowa",
        "Działkowa",
        "Orzechowa",
        "Rzemieślnicza",
        "Rzeczna",
        "Fabryczna",
        "Tęczowa",
        "Chabrowa",
        "Poziomkowa",
        "Konwaliowa",
        "Kalinowa",
        "Północna",
        "Grunwaldzka",
        "Cisowa",
        "Nadrzeczna",
        "Pocztowa",
        "Zachodnia",
        "Dąbrowskiego",
        "Grabowa",
        "Źródlana",
        "Gajowa",
        "Mostowa",
        "Wschodnia",
        "Jaworowa",
        "Poznańska",
        "Makowa",
        "Jeziorna",
        "Piękna",
        "Czereśniowa",
        "Mała",
        "Krakowska",
        "Radosna",
        "Leszczynowa",
        "Rolna",
        "Piastowska",
        "Grzybowa",
        "Podleśna",
        "Żytnia",
        "Złota",
        "Bursztynowa",
        "Żwirowa",
        "Widokowa",
        "Kamienna",
        "Jałowcowa",
        "Morelowa",
        "Myśliwska",
        "Łączna",
        "Szpitalna",
        "Wczasowa",
        "Żurawia",
        "Fiołkowa",
        "Rolnicza",
        "Tulipanowa",
        "Dworska",
        "Letnia",
        "Liliowa",
        "Owocowa",
        "Harcerska",
        "Strzelecka",
        "Wrocławska",
        "Gdańska",
        "Turystyczna",
        "Rybacka",
        "Okrzei",
        "Krucza",
        "Jagiellońska",
        "Szeroka",
        "Młynarska",
        "Olchowa",
        "Rumiankowa",
        "Stroma",
        "Starowiejska",
        "Mazowiecka",
        "Lawendowa",
        "Robotnicza",
        "Zbożowa",
        "Mokra",
        "Towarowa",
        "Dobra",
        "Środkowa",
        "Willowa",
        "Zielna",
        "Zdrojowa",
        "Opolska",
        "Agrestowa",
        "Księżycowa",
        "Zwycięstwa",
        "Letniskowa",
        "Orla",
        "Błękitna",
        "Rubinowa",
        "Brzoskwiniowa",
        "Urocza",
        "Pomorska",
        "Jeżynowa",
        "Zaciszna",
        "Porzeczkowa",
        "Krańcowa",
        "Jesienna",
        "Klasztorna",
        "Irysowa",
        "Niecała",
        "Nadbrzeżna",
        "Wałowa",
        "Strumykowa",
        "Gołębia",
        "Torowa",
        "Cegielniana",
        "Cyprysowa",
        "Słowianska",
        "Diamentowa",
        "Częstochowska",
        "Dojazdowa",
        "Przechodnia",
        "Lubelska",
        "Borówkowa",
        "Plażowa",
        "Tartaczna",
        "Jabłoniowa",
        "Ludowa",
        "Sokola",
        "Azaliowa",
        "Szmaragdowa",
        "Lipca",
        "Jastrzębia",
        "Storczykowa",
        "Wilcza",
        "Górnicza",
        "Szafirowa",
        "Handlowa",
        "Krokusowa",
        "Składowa",
        "Widok",
        "Perłowa",
        "Skośna",
        "Wypoczynkowa",
        "Chmielna",
        "Jaskółcza",
        "Nowowiejska",
        "Piwna",
        "Śląska",
        "Zaułek",
        "Głogowa",
        "Górska",
        "Truskawkowa",
        "Kaszubska",
        "Mazurska",
        "Srebrna",
        "Bociania",
        "Ptasia",
        "Cedrowa",
        "Rycerska",
        "Żabia",
        "Toruńska",
        "Podmiejska",
        "Słonecznikowa",
        "Sowia",
        "Stolarska",
        "Szczęśliwa",
        "Lazurowa",
        "Miarki",
        "Narcyzowa",
        "Browarna",
        "Majowa",
        "Orkana",
        "Skrajna",
        "Bankowa",
        "Bydgoska",
        "Piekarska",
        "Żeglarska",
        "Turkusowa",
        "Tylna",
        "Wysoka",
        "Zakątek",
        "Morska",
        "Rataja",
        "Szewska",
        "Podwale",
        "Pałacowa",
        "Magnoliowa",
        "Ceglana",
        "Wiklinowa",
        "Zakole",
        "Borowa",
        "Kolorowa",
        "Lisia",
        "Lotnicza",
        "Sarnia",
        "Wiązowa",
        "Kolonia",
        "Królewska",
        "Promienna",
        "Daleka",
        "Wiatraczna",
        "Kaliska",
        "Łanowa",
        "Średnia",
        "Wiślana",
        "Koralowa",
        "Sybiraków",
        "Kowalska",
        "Morcinka",
        "Odrzańska",
        "Okulickiego",
        "Zapolskiej",
        "Łabędzia",
        "Bałtycka",
        "Lwowska",
        "Rajska",
        "Pszenna",
        "Ciasna",
        "Hutnicza",
        "Kielecka",
    )

    streets_universal = (
        "Stycznia",
        "Maja",
        "Listopada",
        "Rynek",
        "Kościuszki",
        "Mickiewicza",
        "Sienkiewicza",
        "Słowackiego",
        "Konopnickiej",
        "Kopernika",
        "Jana Pawła II",
        "Żeromskiego",
        "Wojska Polskiego",
        "Wolności",
        "Prusa",
        "Sikorskiego",
        "Chopina",
        "Piłsudskiego",
        "Kochanowskiego",
        "Armii Krajowej",
        "Witosa",
        "Reja",
        "Partyzantów",
        "Kilińskiego",
        "Moniuszki",
        "Orzeszkowej",
        "Staszica",
        "Bolesława Chrobrego",
        "Wyszyńskiego",
        "Matejki",
        "Norwida",
        "Asnyka",
        "Paderewskiego",
        "Wyspiańskiego",
        "Broniewskiego",
        "Tuwima",
        "Bema",
        "Traugutta",
        "Jadwigi",
        "Wyzwolenia",
        "Krasickiego",
        "Kazimierza Wielkiego",
        "Mieszka I",
        "Głowackiego",
        "Władysława Jagiełły",
        "Pułaskiego",
        "Stefana Batorego",
        "Kołłątaja",
        "Kraszewskiego",
        "Władysława Łokietka",
        "Żwirki i Wigury",
        "Niepodległości",
        "Poniatowskiego",
        "Korczaka",
        "Narutowicza",
        "Świerczewskiego",
        "Kasprowicza",
        "Jana III Sobieskiego",
        "Powstańców Śląskich",
        "Powstańców Wielkopolskich",
        "Fredry",
        "Andersa",
        "Baczyńskiego",
        "Batalionów Chłopskich",
        "Dąbrowskiej",
        "Skłodowskiej-Curie",
        "Gałczyńskiego",
        "Krasińskiego",
        "Szymanowskiego",
        "Czarnieckiego",
        "Nałkowskiej",
        "Wybickiego",
        "Szarych Szeregów",
        "Słowicza",
        "Drzymały",
        "Waryńskiego",
        "Hallera",
        "Plater",
        "Popiełuszki",
        "Chełmońskiego",
        "Daszyńskiego",
        "Kossaka",
        "Skargi",
        "Staffa",
        "Tysiąclecia",
        "Brzechwy",
        "Kusocińskiego",
        "Długosza",
        "Kosynierów",
        "Wieniawskiego",
        "Powstańców",
        "Sucharskiego",
        "Bolesława Krzywoustego",
        "Konarskiego",
        "Konstytucji 3 Maja",
        "Miłosza",
        "Malczewskiego",
        "Jana",
        "Maczka",
        "Sawickiej",
        "Ściegiennego",
        "Grottgera",
        "Jana Sobieskiego",
        "Rejtana",
        "Wróblewskiego",
        "Kruczkowskiego",
        "Lelewela",
        "Makuszyńskiego",
        "Solidarności",
        "Wojciecha",
        "Korfantego",
        "Floriana",
    )

    streets = streets_adjective_feminine + streets_universal

    regions = (
        "Dolnośląskie",
        "Kujawsko - pomorskie",
        "Lubelskie",
        "Lubuskie",
        "Łódzkie",
        "Małopolskie",
        "Mazowieckie",
        "Opolskie",
        "Podkarpackie",
        "Podlaskie",
        "Pomorskie",
        "Śląskie",
        "Świętokrzyskie",
        "Warmińsko - mazurskie",
        "Wielkopolskie",
        "Zachodniopomorskie",
    )

    admin2_in_admin1 = {
        "Dolnośląskie": [
            "Powiat bolesławiecki",
            "Powiat dzierżoniowski",
            "Powiat głogowski",
            "Powiat górowski",
            "Powiat jaworski",
            "Powiat jeleniogórski",
            "Jelenia Góra",
            "Powiat kamiennogórski",
            "Powiat kłodzki",
            "Powiat lubański",
            "Powiat legnicki",
            "Powiat lubiński",
            "Legnica",
            "Powiat lwówecki",
            "Powiat milicki",
            "Powiat oleśnicki",
            "Powiat oławski",
            "Powiat polkowicki",
            "Powiat średzki",
            "Powiat strzeliński",
            "Powiat świdnicki",
            "Powiat trzebnicki",
            "Powiat wałbrzyski",
            "Powiat wrocławski",
            "Powiat wołowski",
            "Wrocław",
            "Powiat ząbkowicki",
            "Powiat zgorzelecki",
            "Powiat złotoryjski",
        ],
        "Kujawsko-pomorskie": [
            "Powiat aleksandrowski",
            "Bydgoszcz",
            "Powiat brodnicki",
            "Powiat bydgoski",
            "Powiat chełmiński",
            "Grudziądz",
            "Powiat golubsko-dobrzyński",
            "Powiat grudziądzki",
            "Powiat inowrocławski",
            "Powiat lipnowski",
            "Powiat mogileński",
            "Powiat nakielski",
            "Powiat radziejowski",
            "Powiat rypiński",
            "Powiat sępoleński",
            "Powiat świecki",
            "Toruń",
            "Powiat toruński",
            "Powiat tucholski",
            "Powiat wąbrzeski",
            "Powiat włocławski",
            "Włocławek",
            "Powiat żniński",
        ],
        "Lubuskie": [
            "Gorzów Wielkopolski",
            "Powiat gorzowski",
            "Powiat krośnieński",
            "Powiat międzyrzecki",
            "Powiat nowosolski",
            "Powiat słubicki",
            "Powiat strzelecko-drezdenecki",
            "Powiat sulęciński",
            "Powiat świebodziński",
            "Powiat wschowski",
            "Powiat żagański",
            "Powiat zielonogórski",
            "Zielona Góra",
            "Powiat żarski",
        ],
        "Łódzkie": [
            "Powiat bełchatowski",
            "Powiat brzeziński",
            "Powiat kutnowski",
            "Powiat łaski",
            "Powiat łowicki",
            "Powiat łódzki wschodni",
            "Powiat łęczycki",
            "Łódź",
            "Powiat opoczyński",
            "Powiat pabianicki",
            "Powiat pajęczański",
            "Piotrków Trybunalski",
            "Powiat poddębicki",
            "Powiat piotrkowski",
            "Powiat radomszczański",
            "Powiat rawski",
            "Powiat sieradzki",
            "Powiat skierniewicki",
            "Skierniewice",
            "Powiat tomaszowski",
            "Powiat wieluński",
            "Powiat wieruszowski",
            "Powiat zduńskowolski",
            "Powiat zgierski",
        ],
        "Lubelskie": [
            "Powiat biłgorajski",
            "Biała Podlaska",
            "Powiat bialski",
            "Powiat chełmski",
            "Chełm",
            "Powiat hrubieszowski",
            "Powiat janowski",
            "Powiat kraśnicki",
            "Powiat krasnostawski",
            "Powiat łęczyński",
            "Powiat łukowski",
            "Lublin",
            "Powiat lubartowski",
            "Powiat lubelski",
            "Powiat opolski",
            "Powiat parczewski",
            "Powiat puławski",
            "Powiat radzyński",
            "Powiat rycki",
            "Powiat świdnicki",
            "Powiat tomaszowski",
            "Powiat włodawski",
            "Powiat zamojski",
            "Zamość",
        ],
        "Małopolskie": [
            "Powiat bocheński",
            "Powiat brzeski",
            "Powiat chrzanowski",
            "Powiat dąbrowski",
            "Powiat gorlicki",
            "Kraków",
            "Powiat krakowski",
            "Powiat limanowski",
            "Powiat miechowski",
            "Powiat myślenicki",
            "Nowy Sącz",
            "Powiat nowosądecki",
            "Powiat nowotarski",
            "Powiat olkuski",
            "Powiat oświęcimski",
            "Powiat proszowicki",
            "Powiat suski",
            "Powiat tarnowski",
            "Tarnów",
            "Powiat tatrzański",
            "Powiat wadowicki",
            "Powiat wielicki",
        ],
        "Mazowieckie": [
            "Powiat białobrzeski",
            "Powiat ciechanowski",
            "Powiat garwoliński",
            "Powiat grodziski",
            "Powiat grójecki",
            "Powiat gostyniński",
            "Powiat kozienicki",
            "Powiat legionowski",
            "Powiat lipski",
            "Powiat łosicki",
            "Powiat makowski",
            "Powiat miński",
            "Powiat mławski",
            "Powiat nowodworski",
            "Powiat ostrołęcki",
            "Ostrołęka",
            "Powiat ostrowski",
            "Powiat otwocki",
            "Powiat piaseczyński",
            "Powiat pruszkowski",
            "Powiat płocki",
            "Płock",
            "Powiat płoński",
            "Powiat pułtuski",
            "Powiat przysuski",
            "Powiat przasnyski",
            "Powiat radomski",
            "Radom",
            "Powiat siedlecki",
            "Powiat sokołowski",
            "Siedlce",
            "Powiat sochaczewski",
            "Powiat sierpecki",
            "Powiat szydłowiecki",
            "Warszawa",
            "Powiat węgrowski",
            "Powiat wołomiński",
            "Powiat wyszkowski",
            "Powiat warszawski zachodni",
            "Powiat żuromiński",
            "Powiat zwoleński",
            "Powiat żyrardowski",
        ],
        "Opolskie": [
            "Powiat brzeski",
            "Powiat głubczycki",
            "Powiat kędzierzyńsko-kozielski",
            "Powiat kluczborski",
            "Powiat krapkowicki",
            "Powiat namysłowski",
            "Powiat nyski",
            "Powiat oleski",
            "Opole",
            "Powiat opolski",
            "Powiat prudnicki",
            "Powiat strzelecki",
        ],
        "Podlaskie": [
            "Powiat augustowski",
            "Powiat białostocki",
            "Białystok",
            "Powiat bielski",
            "Powiat grajewski",
            "Powiat hajnowski",
            "Powiat kolneński",
            "Łomża",
            "Powiat łomżyński",
            "Powiat moniecki",
            "Powiat sejneński",
            "Powiat siemiatycki",
            "Suwałki",
            "Powiat sokólski",
            "Powiat suwalski",
            "Powiat wysokomazowiecki",
            "Powiat zambrowski",
        ],
        "Podkarpackie": [
            "Powiat bieszczadzki",
            "Powiat brzozowski",
            "Powiat dębicki",
            "Powiat jarosławski",
            "Powiat jasielski",
            "Krosno",
            "Powiat kolbuszowski",
            "Powiat krośnieński",
            "Powiat łańcucki",
            "Powiat leżajski",
            "Powiat leski",
            "Powiat lubaczowski",
            "Powiat mielecki",
            "Powiat niżański",
            "Przemyśl",
            "Powiat przemyski",
            "Powiat przeworski",
            "Rzeszów",
            "Powiat ropczycko-sędziszowski",
            "Powiat rzeszowski",
            "Powiat sanocki",
            "Powiat strzyżowski",
            "Powiat stalowowolski",
            "Powiat tarnobrzeski",
            "Tarnobrzeg",
        ],
        "Pomorskie": [
            "Powiat bytowski",
            "Powiat chojnicki",
            "Powiat człuchowski",
            "Powiat gdański",
            "Gdańsk",
            "Gdynia",
            "Powiat kartuski",
            "Powiat kościerski",
            "Powiat kwidzyński",
            "Powiat lęborski",
            "Powiat malborski",
            "Powiat nowodworski",
            "Powiat pucki",
            "Powiat słupski",
            "Słupsk",
            "Sopot",
            "Powiat starogardzki",
            "Powiat sztumski",
            "Powiat tczewski",
            "Powiat wejherowski",
        ],
        "Świętokrzyskie": [
            "Powiat buski",
            "Powiat jędrzejowski",
            "Powiat kazimierski",
            "Powiat kielecki",
            "Kielce",
            "Powiat konecki",
            "Powiat opatowski",
            "Powiat ostrowiecki",
            "Powiat pińczowski",
            "Powiat sandomierski",
            "Powiat skarżyski",
            "Powiat staszowski",
            "Powiat starachowicki",
            "Powiat włoszczowski",
        ],
        "Śląskie": [
            "Powiat będziński",
            "Powiat bielski",
            "Bielsko-Biała",
            "Bytom",
            "Chorzów",
            "Powiat cieszyński",
            "Częstochowa",
            "Powiat częstochowski",
            "Dąbrowa Górnicza",
            "Powiat gliwicki",
            "Gliwice",
            "Jaworzno",
            "Jastrzębie-Zdrój",
            "Katowice",
            "Powiat kłobucki",
            "Powiat lubliniecki",
            "Powiat mikołowski",
            "Powiat myszkowski",
            "Mysłowice",
            "Powiat piekary śląskie",
            "Powiat pszczyński",
            "Powiat raciborski",
            "Rybnik",
            "Ruda Śląska",
            "Powiat rybnicki",
            "Siemianowice Śląskie",
            "Sosnowiec",
            "Świętochłowice",
            "Powiat tarnogórski",
            "Tychy",
            "Powiat bieruńsko-lędziński",
            "Powiat wodzisławski",
            "Powiat zawierciański",
            "Zabrze",
            "Żory",
            "Powiat żywiecki",
        ],
        "Warmińsko-Mazurskie": [
            "Powiat bartoszycki",
            "Powiat braniewski",
            "Powiat działdowski",
            "Powiat ełcki",
            "Powiat elbląski",
            "Elbląg",
            "Powiat gołdapski",
            "Powiat giżycki",
            "Powiat iławski",
            "Powiat kętrzyński",
            "Powiat lidzbarski",
            "Powiat mrągowski",
            "Powiat nidzicki",
            "Powiat nowomiejski",
            "Powiat olecki",
            "Powiat olsztyński",
            "Olsztyn",
            "Powiat ostródzki",
            "Powiat piski",
            "Powiat szczycieński",
            "Powiat węgorzewski",
        ],
        "Wielkopolskie": [
            "Powiat chodzieski",
            "Powiat czarnkowsko-trzcianecki",
            "Powiat gnieżnieński",
            "Powiat gostyński",
            "Powiat grodziski",
            "Powiat jarociński",
            "Powiat kaliski",
            "Powiat kępiński",
            "Powiat kolski",
            "Kalisz",
            "Powiat koniński",
            "Konin",
            "Powiat krotoszyński",
            "Powiat kościański",
            "Powiat leszczyński",
            "Leszno",
            "Powiat międzychodzki",
            "Powiat nowotomyski",
            "Powiat obornicki",
            "Powiat ostrzeszowski",
            "Powiat ostrowski",
            "Powiat pilski",
            "Powiat pleszewski",
            "Poznań",
            "Powiat poznański",
            "Powiat rawicki",
            "Powiat średzki",
            "Powiat słupecki",
            "Powiat śremski",
            "Powiat szamotulski",
            "Powiat turecki",
            "Powiat wągrowiecki",
            "Powiat wolsztyński",
            "Powiat wrzesiński",
            "Powiat złotowski",
        ],
        "Zachodniopomorskie": [
            "Powiat białogardzki",
            "Powiat choszczeński",
            "Powiat drawski",
            "Powiat gryficki",
            "Powiat goleniowski",
            "Powiat gryfiński",
            "Powiat kamieński",
            "Powiat kołobrzeski",
            "Koszalin",
            "Powiat koszaliński",
            "Powiat łobeski",
            "Powiat myśliborski",
            "Powiat policki",
            "Powiat pyrzycki",
            "Powiat stargardzki",
            "Świnoujście",
            "Powiat sławieński",
            "Powiat szczecin",
            "Powiat świdwiński",
            "Powiat szczecinecki",
            "Powiat wałecki",
        ],
    }

    building_number_formats = ("##", "###", "##/##")
    postcode_formats = ("##-###",)
    street_address_formats = (
        "{{street_prefix_feminine}} {{street_name_adjective_feminine}} {{building_number}}",
        "{{street_prefix_feminine}} {{street_name_universal}} {{building_number}}",
        "{{street_prefix_masculine}} {{street_name_universal}} {{building_number}}",
        "{{street_prefix_feminine_short}} {{street_name_adjective_feminine}} {{building_number}}",
        "{{street_prefix_feminine_short}} {{street_name_universal}} {{building_number}}",
        "{{street_prefix_masculine_short}} {{street_name_universal}} {{building_number}}",
    )
    address_formats = ("{{street_address}}\n{{postcode}} {{city}}",)

    def street_prefix(self) -> str:
        """
        Randomly returns a street prefix
        :example: 'aleja'
        """
        return self.random_element(self.street_prefixes)

    def street_prefix_feminine(self) -> str:
        """
        Randomly returns a feminine street prefix
        :example: 'aleja'
        """
        return self.random_element(self.street_prefixes_feminine)

    def street_prefix_masculine(self) -> str:
        """
        Randomly returns a masculine street prefix
        :example: 'plac'
        """
        return self.random_element(self.street_prefixes_masculine)

    def street_prefix_short(self) -> str:
        """
        Randomly returns an abbreviation of the street prefix.
        :example: 'al.'
        """
        return self.random_element(self.street_prefixes)[:2] + "."  # type: ignore

    def street_prefix_feminine_short(self) -> str:
        """
        Randomly returns an abbreviation of the feminine street prefix.
        :example: 'al.'
        """
        return self.random_element(self.street_prefixes_feminine)[:2] + "."  # type: ignore

    def street_prefix_masculine_short(self) -> str:
        """
        Randomly returns an abbreviation of the masculine street prefix.
        :example: 'pl.'
        """
        return self.random_element(self.street_prefixes_masculine)[:2] + "."  # type: ignore

    def street_name(self) -> str:
        """
        Randomly returns a street name
        :example: 'Wróblewskiego'
        """
        return self.random_element(self.streets)

    def street_name_adjective_feminine(self) -> str:
        """
        Randomly returns an adjective feminine street name
        :example: 'Zielona'
        """
        return self.random_element(self.streets_adjective_feminine)

    def street_name_universal(self) -> str:
        """
        Randomly returns a universal street name
        :example: 'Wróblewskiego'
        """
        return self.random_element(self.streets_universal)

    def city(self) -> str:
        """
        Randomly returns a city name
        :example: 'Konin'
        """
        return self.random_element(self.cities)

    def administrative_unit(self) -> str:
        """
        :example: 'Wielkopolskie'
        """
        return self.random_element(self.regions)

    def postcode(self) -> str:
        """
        :example: '62-200'
        """
        return "%02d-%03d" % (
            self.generator.random.randint(1, 99),
            self.generator.random.randint(1, 999),
        )

    def zipcode(self) -> str:
        """
        :example: '62-200'
        """
        return self.postcode()

    def postalcode(self) -> str:
        """
        :example: '62-200'
        """
        return self.postcode()

    region = administrative_unit
    admin1 = administrative_unit

    def admin2(self) -> str:
        return self.random_element(
            tuple(
                admin2
                for admin2s in self.admin2_in_admin1.values()
                for admin2 in admin2s
            )
        )

    def admin2_from_admin1(self, admin1: str) -> str:
        return self.random_element(self.admin2_in_admin1[admin1])

    def admin2_with_admin1(self) -> str:
        admin1 = self.admin1()
        admin2 = self.admin2_from_admin1(admin1)
        return f"{admin2} {admin1}"

    def admin2_w_admin1(self, admin1: str) -> str:
        admin2 = self.admin2_from_admin1(admin1)
        return f"{admin2} {admin1}"
