# coding=utf-8

from __future__ import unicode_literals
from .. import BaseProvider


localized = True


class Provider(BaseProvider):
    formats = (
        '{{last_name}} {{company_suffix}}',
        '{{last_name}}-{{last_name}}',
        '{{last_name}}, {{last_name}} and {{last_name}}',
    )

    company_suffixes = ('Inc', 'and Sons', 'LLC', 'Group', 'PLC', 'Ltd')

    catch_phrase_words = (
        ('Adaptive',
         'Advanced',
         'Ameliorated',
         'Assimilated',
         'Automated',
         'Balanced',
         'Business-focused',
         'Centralized',
         'Cloned',
         'Compatible',
         'Configurable',
         'Cross-group',
         'Cross-platform',
         'Customer-focused',
         'Customizable',
         'Decentralized',
         'De-engineered',
         'Devolved',
         'Digitized',
         'Distributed',
         'Diverse',
         'Down-sized',
         'Enhanced',
         'Enterprise-wide',
         'Ergonomic',
         'Exclusive',
         'Expanded',
         'Extended',
         'Face-to-face',
         'Focused',
         'Front-line',
         'Fully-configurable',
         'Function-based',
         'Fundamental',
         'Future-proofed',
         'Grass-roots',
         'Horizontal',
         'Implemented',
         'Innovative',
         'Integrated',
         'Intuitive',
         'Inverse',
         'Managed',
         'Mandatory',
         'Monitored',
         'Multi-channeled',
         'Multi-lateral',
         'Multi-layered',
         'Multi-tiered',
         'Networked',
         'Object-based',
         'Open-architected',
         'Open-source',
         'Operative',
         'Optimized',
         'Optional',
         'Organic',
         'Organized',
         'Persevering',
         'Persistent',
         'Phased',
         'Polarized',
         'Pre-emptive',
         'Proactive',
         'Profit-focused',
         'Profound',
         'Programmable',
         'Progressive',
         'Public-key',
         'Quality-focused',
         'Reactive',
         'Realigned',
         'Re-contextualized',
         'Re-engineered',
         'Reduced',
         'Reverse-engineered',
         'Right-sized',
         'Robust',
         'Seamless',
         'Secured',
         'Self-enabling',
         'Sharable',
         'Stand-alone',
         'Streamlined',
         'Switchable',
         'Synchronized',
         'Synergistic',
         'Synergized',
         'Team-oriented',
         'Total',
         'Triple-buffered',
         'Universal',
         'Up-sized',
         'Upgradable',
         'User-centric',
         'User-friendly',
         'Versatile',
         'Virtual',
         'Visionary',
         'Vision-oriented'),
        ('24hour',
         '24/7',
         '3rdgeneration',
         '4thgeneration',
         '5thgeneration',
         '6thgeneration',
         'actuating',
         'analyzing',
         'asymmetric',
         'asynchronous',
         'attitude-oriented',
         'background',
         'bandwidth-monitored',
         'bi-directional',
         'bifurcated',
         'bottom-line',
         'clear-thinking',
         'client-driven',
         'client-server',
         'coherent',
         'cohesive',
         'composite',
         'context-sensitive',
         'contextually-based',
         'content-based',
         'dedicated',
         'demand-driven',
         'didactic',
         'directional',
         'discrete',
         'disintermediate',
         'dynamic',
         'eco-centric',
         'empowering',
         'encompassing',
         'even-keeled',
         'executive',
         'explicit',
         'exuding',
         'fault-tolerant',
         'foreground',
         'fresh-thinking',
         'full-range',
         'global',
         'grid-enabled',
         'heuristic',
         'high-level',
         'holistic',
         'homogeneous',
         'human-resource',
         'hybrid',
         'impactful',
         'incremental',
         'intangible',
         'interactive',
         'intermediate',
         'leadingedge',
         'local',
         'logistical',
         'maximized',
         'methodical',
         'mission-critical',
         'mobile',
         'modular',
         'motivating',
         'multimedia',
         'multi-state',
         'multi-tasking',
         'national',
         'needs-based',
         'neutral',
         'next generation',
         'non-volatile',
         'object-oriented',
         'optimal',
         'optimizing',
         'radical',
         'real-time',
         'reciprocal',
         'regional',
         'responsive',
         'scalable',
         'secondary',
         'solution-oriented',
         'stable',
         'static',
         'systematic',
         'systemic',
         'system-worthy',
         'tangible',
         'tertiary',
         'transitional',
         'uniform',
         'upward-trending',
         'user-facing',
         'value-added',
         'web-enabled',
         'well-modulated',
         'zero administration',
         'zero-defect',
         'zero tolerance'),
        ('ability',
         'access',
         'adapter',
         'algorithm',
         'alliance',
         'analyzer',
         'application',
         'approach',
         'architecture',
         'archive',
         'artificial intelligence',
         'array',
         'attitude',
         'benchmark',
         'budgetary management',
         'capability',
         'capacity',
         'challenge',
         'circuit',
         'collaboration',
         'complexity',
         'concept',
         'conglomeration',
         'contingency',
         'core',
         'customer loyalty',
         'database',
         'data-warehouse',
         'definition',
         'emulation',
         'encoding',
         'encryption',
         'extranet',
         'firmware',
         'flexibility',
         'focus group',
         'forecast',
         'frame',
         'framework',
         'function',
         'functionalities',
         'Graphic Interface',
         'groupware',
         'Graphical User Interface',
         'hardware',
         'help-desk',
         'hierarchy',
         'hub',
         'implementation',
         'info-mediaries',
         'infrastructure',
         'initiative',
         'installation',
         'instruction set',
         'interface',
         'Internet solution',
         'intranet',
         'knowledge user',
         'knowledgebase',
         'Local Area Network',
         'leverage',
         'matrices',
         'matrix',
         'methodology',
         'middleware',
         'migration',
         'model',
         'moderator',
         'monitoring',
         'moratorium',
         'neural-net',
         'open architecture',
         'open system',
         'orchestration',
         'paradigm',
         'parallelism',
         'policy',
         'portal',
         'pricing structure',
         'process improvement',
         'product',
         'productivity',
         'project',
         'projection',
         'protocol',
         'secured line',
         'service-desk',
         'software',
         'solution',
         'standardization',
         'strategy',
         'structure',
         'success',
         'superstructure',
         'support',
         'synergy',
         'system engine',
         'task-force',
         'throughput',
         'time-frame',
         'toolset',
         'utilization',
         'website',
         'workforce'))

    bsWords = (
        ('implement',
         'utilize',
         'integrate',
         'streamline',
         'optimize',
         'evolve',
         'transform',
         'embrace',
         'enable',
         'orchestrate',
         'leverage',
         'reinvent',
         'aggregate',
         'architect',
         'enhance',
         'incentivize',
         'morph',
         'empower',
         'envisioneer',
         'monetize',
         'harness',
         'facilitate',
         'seize',
         'disintermediate',
         'synergize',
         'strategize',
         'deploy',
         'brand',
         'grow',
         'target',
         'syndicate',
         'synthesize',
         'deliver',
         'mesh',
         'incubate',
         'engage',
         'maximize',
         'benchmark',
         'expedite',
         're-intermediate',
         'whiteboard',
         'visualize',
         'repurpose',
         'innovate',
         'scale',
         'unleash',
         'drive',
         'extend',
         'engineer',
         'revolutionize',
         'generate',
         'exploit',
         'transition',
         'e-enable',
         'iterate',
         'cultivate',
         'matrix',
         'productize',
         'redefine',
         're-contextualize'),
        ('clicks-and-mortar',
         'value-added',
         'vertical',
         'proactive',
         'robust',
         'revolutionary',
         'scalable',
         'leading-edge',
         'innovative',
         'intuitive',
         'strategic',
         'e-business',
         'mission-critical',
         'sticky',
         'one-to-one',
         '24/7',
         'end-to-end',
         'global',
         'B2B',
         'B2C',
         'granular',
         'frictionless',
         'virtual',
         'viral',
         'dynamic',
         '24/365',
         'best-of-breed',
         'killer',
         'magnetic',
         'bleeding-edge',
         'web-enabled',
         'interactive',
         'dot-com',
         'sexy',
         'back-end',
         'real-time',
         'efficient',
         'front-end',
         'distributed',
         'seamless',
         'extensible',
         'turn-key',
         'world-class',
         'open-source',
         'cross-platform',
         'cross-media',
         'synergistic',
         'bricks-and-clicks',
         'out-of-the-box',
         'enterprise',
         'integrated',
         'impactful',
         'wireless',
         'transparent',
         'next-generation',
         'cutting-edge',
         'user-centric',
         'visionary',
         'customized',
         'ubiquitous',
         'plug-and-play',
         'collaborative',
         'compelling',
         'holistic',
         'rich'),
        ('synergies',
         'web-readiness',
         'paradigms',
         'markets',
         'partnerships',
         'infrastructures',
         'platforms',
         'initiatives',
         'channels',
         'eyeballs',
         'communities',
         'ROI',
         'solutions',
         'e-tailers',
         'e-services',
         'action-items',
         'portals',
         'niches',
         'technologies',
         'content',
         'vortals',
         'supply-chains',
         'convergence',
         'relationships',
         'architectures',
         'interfaces',
         'e-markets',
         'e-commerce',
         'systems',
         'bandwidth',
         'info-mediaries',
         'models',
         'mindshare',
         'deliverables',
         'users',
         'schemas',
         'networks',
         'applications',
         'metrics',
         'e-business',
         'functionalities',
         'experiences',
         'web services',
         'methodologies'))

    # Taken the list nl_NL providers
    company_names = [
        'Shell', 'Coolblue', 'ASML', 'Ahold', 'Tata Steel', 'KLM', 'Bol.com', 'BP Nederland', 'De Efteling', 'Eneco',
        'De Persgroep', 'ING', 'Royal HaskoningDHV', 'Randstad', 'Google', 'Ikea', 'Rockwool', 'BAM', 'Achmea',
        'Damen Shipyard', 'ABN Amro', 'Remeha Group', 'TenneT', 'Coca-Cola', 'Van Leeuwen Buizen', 'Wavin', 'Rabobank',
        'AkzoNobel', 'Arcadis', 'AFAS', 'Cisco', 'DAF Trucks', 'DHL', 'Hanos', 'Boon Edam', 'BMW Nederland',
        'The Greenery', 'Dutch Flower Group', 'Koninklijke Mosa', 'Yacht', 'Rituals', 'Microsoft', 'Esso',
        '3W Vastgoed', 'Deloitte', 'Corio', 'Voortman Steel Group', 'Agrifirm', 'Makro Nederland',
        'Nederlandse Publieke Omroep', 'De Alliantie', 'Heijmans', 'McDonalds', 'ANWB', 'Mediamarkt', 'Kruidvat'
        'Van Merksteijn Steel', 'Dura Vermeer', 'Alliander', 'Unilever', 'Enexis', 'Berenschot', 'Jumbo',
        'Technische Unie', 'Havenbedrijf Rotterdam', 'Ballast Nedam', 'RTL Nederland', 'Talpa Media',
        'Blauwhoed Vastgoed', 'DSM', 'Ymere', 'Witteveen+Bos', 'NS', 'Action', 'FloraHolland', 'Heineken', 'Nuon', 'EY',
        'Dow Benelux', 'Bavaria', 'Schiphol', 'Holland Casino', 'Binck bank', 'BDO', 'HEMA', 'Alphabet Nederland',
        'Croon Elektrotechniek', 'ASR Vastgoed ontwikkeling', 'PwC', 'Mammoet', 'KEMA', 'IBM', 'A.S. Watson',
        'KPMG', 'VodafoneZiggo', 'YoungCapital', 'Triodos Bank', 'Aviko', 'AgruniekRijnvallei', 'Heerema', 'Accenture',
        'Aegon', 'NXP', 'Breman Installatiegroep', 'Movares Groep', 'Q-Park', 'FleuraMetz', 'Sanoma',
        'Bakker Logistiek', 'VDL Group', 'Bayer', 'Boskalis', 'Nutreco', 'Dell', 'Brunel', 'Exact', 'Manpower',
        'Essent', 'Canon', 'ONVZ Zorgverzekeraar', 'Telegraaf Media Group', 'Nationale Nederlanden', 'Andus Group',
        'Den Braven Group', 'ADP', 'ASR', 'ArboNed', 'Plieger', 'De Heus Diervoeders', 'USG People', 'Bidvest Deli XL',
        'Apollo Vredestein', 'Tempo-Team', 'Trespa', 'Janssen Biologics', 'Starbucks', 'PostNL', 'Vanderlande',
        'FrieslandCampina', 'Constellium', 'Huisman', 'Abbott', 'Koninklijke Boom Uitgevers', 'Bosch Rexroth', 'BASF',
        'Audax', 'VolkerWessels', 'Hunkemöller', 'Athlon Car Lease', 'DSW Zorgverzekeraar', 'Mars',
        'De Brauw Blackstone Westbroek', 'NDC Mediagroep', 'Bluewater', 'Stedin', 'Feenstra',
        'Wuppermann Staal Nederland', 'Kramp', 'SABIC', 'Iv-Groep', 'Bejo Zaden', 'Wolters Kluwer', 'Nyrstar holding',
        'Adecco', 'Tauw', 'Robeco', 'Eriks', 'Allianz Nederland Groep', 'Driessen', 'Burger King', 'Lekkerland',
        'Van Lanschot', 'Brocacef', 'Bureau Veritas', 'Relx', 'Pathé Bioscopen', 'Bosal',
        'Ardagh Group', 'Maandag', 'Inalfa', 'Atradius', 'Capgemini', 'Greenchoice', 'Q8 (Kuwait Petroleum Europe)',
        'ASM International', 'Van der Valk', 'Delta Lloyd', 'GlaxoSmithKline', 'ABB',
        'Fabory, a Grainger company', 'Veen Bosch & Keuning Uitgeversgroep', 'CZ', 'Plus', 'RET Rotterdam',
        'Loyens & Loeff', 'Holland Trading', 'Archer Daniels Midland Nederland', 'Ten Brinke', 'NAM', 'DAS',
        'Samsung Electronics Benelux', 'Koopman International', 'TUI', 'Lannoo Meulenhoff', 'AC Restaurants',
        'Stage Entertainment', 'Acer', 'HDI Global SE', 'Detailresult', 'Nestle', 'GVB Amsterdam', 'Dekamarkt', 'Dirk',
        'MSD', 'Arriva', 'Baker Tilly Berk', 'SBM Offshore', 'TomTom', 'Fujifilm', 'B&S', 'BCC', 'Gasunie',
        'Oracle Nederland', 'Astellas Pharma', 'SKF', 'Woningstichting Eigen Haard', 'Rijk Zwaan', 'Chubb', 'Fugro',
        'Total', 'Rochdale', 'ASVB', 'Atos', 'Acomo', 'KPN', 'Van Drie Group', 'Olympia uitzendbureau',
        'Bacardi Nederland', 'JMW Horeca Uitzendbureau', 'Warner Bros/Eyeworks', 'Aalberts Industries', 'SNS Bank',
        'Amtrada Holding', 'VGZ', 'Grolsch', 'Office Depot', 'De Rijke Group', 'Bovemij Verzekeringsgroep',
        'Coop Nederland', 'Eaton Industries', 'ASN', 'Yara Sluiskil', 'HSF Logistics', 'Fokker', 'Deutsche Bank',
        'Sweco', 'Univé Groep', 'Koninklijke Wagenborg', 'Strukton', 'Conclusion', 'Philips', 'In Person',
        'Fluor', 'Vroegop-Windig', 'ArboUnie', 'Centraal Boekhuis', 'Siemens', 'Connexxion', 'Fujitsu', 'Consolid',
        'AVR Afvalverwerking', 'Brabant Alucast', 'Centric', 'Havensteder', 'Novartis', 'Booking.com', 'Menzis',
        'Frankort & Koning Groep', 'Jan de Rijk', 'Brand Loyalty Group', 'Ohra Verzekeringen', 'Terberg Group',
        'Cloetta', 'Holland & Barrett', 'Enza Zaden', 'VION', 'Woonzorg Nederland',
        'T-Mobile', 'Crucell', 'NautaDutilh', 'BNP Paribas', 'NIBC Bank', 'VastNed', 'CCV Holland',
        'IHC Merwede', 'Neways', 'NSI N.V.', 'Deen', 'Accor', 'HTM', 'ITM Group', 'Ordina', 'Dümmen Orange', 'Optiver',
        'Zara', 'L\'Oreal Nederland B.V.', 'Vinci Energies', 'Suit Supply Topco', 'Sita', 'Vos Logistics',
        'Altran', 'St. Clair', 'BESI', 'Fiat Chrysler Automobiles', 'UPS', 'Jacobs', 'Emté', 'TBI', 'De Bijenkorf',
        'Aldi Nederland', 'Van Wijnen', 'Vitens', 'De Goudse Verzekeringen', 'SBS Broadcasting',
        'Sandd', 'Omron', 'Sogeti', 'Alfa Accountants & Adviseurs', 'Harvey Nash', 'Stork', 'Glencore Grain',
        'Meijburg & Co', 'Honeywell', 'Meyn', 'Ericsson Telecommunicatie', 'Hurks', 'Mitsubishi', 'GGN',
        'CGI Nederland', 'Staples Nederland', 'Denkavit International', 'Ecorys', 'Rexel Nederland',
        'A. Hakpark', 'DuPont Nederland', 'CBRE Group', 'Bolsius', 'Marel', 'Metro',
        'Flynth Adviseurs en Accountants', 'Kropman Installatietechniek', 'Kuijpers', 'Medtronic', 'Cefetra',
        'Simon Loos', 'Citadel Enterprises', 'Intergamma', 'Ceva Logistics', 'Beter Bed', 'Subway', 'Gamma', 'Karwei'
        'Varo Energy', 'APM Terminals', 'Center Parcs', 'Brenntag Nederland', 'NFI', 'Hoogvliet',
        'Van Gansewinkel', 'Nedap', 'Blokker', 'Perfetti Van Melle', 'Vestia', 'Kuehne + Nagel Logistics',
        'Rensa Group', 'NTS Group', 'Joh. Mourik & Co. Holding', 'Mercedes-Benz', 'DIT Personeel', 'Verkade',
        'Hametha', 'Vopak', 'IFF', 'Pearle', 'Mainfreight', 'De Jong & Laan', 'DSV', 'P4People', 'Mazars', 'Cargill',
        'Ten Brinke Groep', 'Alewijnse', 'Agio Cigars', 'Peter Appel Transport', 'Syngenta', 'Avery Dennison',
        'Accon AVM', 'Vitol', 'Vermaat Groep', 'BMC', 'Alcatel-Lucent', 'Maxeda DIY', 'Equens',
        'Van Gelder Groep', 'Emerson Electric Nederland', 'Bakkersland', 'Specsavers', 'E.On', 'Landal Greenparks',
        'IMC Trading', 'Barentz Group', 'Epson', 'Raet', 'Van Oord', 'Thomas Cook Nederland', 'SDU uitgevers',
        'Nedschroef', 'Linde Gas', 'Ewals Cargo Care', 'Theodoor Gilissen', 'TMF Group', 'Cornelis Vrolijk',
        'Jan Linders Supermarkten', 'SIF group', 'BT Nederland', 'Kinepolis', 'Pink Elephant',
        'General Motors Nederland', 'Carlson Wagonlit', 'Bruna', 'Docdata', 'Schenk Tanktransport', 'WPG', 'Peak-IT',
        'Martinair', 'Reesink', 'Elopak Nederland', 'Fagron N.V.', 'OVG Groep', 'Ford Nederland', 'Multi Corporation',
        'Simac', 'Primark', 'Tech Data Nederland', 'Vleesgroothandel Zandbergen', 'Raben Group', 'Farm Frites',
        'Libéma', 'Caldic', 'Portaal', 'Syntus', 'Jacobs DE', 'Stena Line', 'The Phone House', 'Interfood Group',
        'Thales', 'Teva Pharmaceuticals', 'RFS Holland', 'Aebi Schmidt Nederland',
        'Rockwell Automation Nederland', 'Engie Services', 'Hendrix Genetics', 'Qbuzz', 'Unica',
        '2SistersFoodGroup', 'Ziut', 'Munckhof Groep', 'Spar Holding', 'Samskip', 'Continental Bakeries', 'Sligro',
        'Merck', 'Foot Locker Europe', 'Unit4', 'PepsiCo', 'Sulzer', 'Tebodin', 'Value8', 'Boels',
        'DKG Groep', 'Bruynzeel Keukens', 'Janssen de Jong Groep', 'ProRail', 'Solid Professionals', 'Hermes Partners',
    ]

    def companies(self, nb=3, unique=False):
        """
        :returns: An array of random companies. for example: ['Shell', 'Cisco']

        Keyword arguments:
        :param nb: how many companies to return
        :param unique: If True, the returned word list will contain unique companies

        :rtype: list
        """
        if unique:
            return self.random_sample(self.company_names, length=nb)
        return self.random_choices(self.company_names, length=nb)

    def company(self):
        """
        :example 'Acme Ltd'
        """
        pattern = self.random_element(self.formats)
        return self.generator.parse(pattern)

    def company_suffix(self):
        """
        :example 'Ltd'
        """
        return self.random_element(self.company_suffixes)

    def catch_phrase(self):
        """
        :example 'Robust full-range hub'
        """
        result = []
        for word_list in self.catch_phrase_words:
            result.append(self.random_element(word_list))

        return " ".join(result)

    def bs(self):
        """
        :example 'integrate extensible convergence'
        """
        result = []
        for word_list in self.bsWords:
            result.append(self.random_element(word_list))

        return " ".join(result)
