from .. import BaseProvider, ElementsType


class Provider(BaseProvider):
    """Provider for generating AI/ML-related fake data."""

    ai_models: ElementsType[str] = (
        "GPT-4",
        "GPT-4o",
        "GPT-4o-mini",
        "GPT-3.5-turbo",
        "GPT-4.5",
        "GPT-5",
        "GPT-5.2",
        "Claude 3 Opus",
        "Claude 3 Sonnet",
        "Claude 3 Haiku",
        "Claude 3.5 Sonnet",
        "Claude 3.7 Sonnet",
        "Claude 4",
        "Gemini Pro",
        "Gemini Ultra",
        "Gemini 1.5 Pro",
        "Gemini 1.5 Flash",
        "Gemini 2.5",
        "Gemini 3",
        "Gemini 3 Flash",
        "LLaMA 2 7B",
        "LLaMA 2 13B",
        "LLaMA 2 70B",
        "LLaMA 3 8B",
        "LLaMA 3 70B",
        "LLaMA 3.1 405B",
        "LLaMA 4",
        "Mistral 7B",
        "Mistral 8x7B",
        "Mixtral 8x22B",
        "Mistral Large 3",
        "Mistral Nemo",
        "Falcon 40B",
        "Falcon 180B",
        "PaLM 2",
        "BERT",
        "RoBERTa",
        "T5",
        "DALL-E 3",
        "Stable Diffusion XL",
        "Midjourney v6",
        "Midjourney v7",
        "Whisper",
        "Codex",
        "Copilot",
        "StarCoder",
        "CodeLlama",
        "Phi-2",
        "Phi-3",
        "Qwen 72B",
        "Qwen3",
        "DeepSeek-V2",
        "DeepSeek-V3",
        "Command R+",
        "Cohere Embed",
        "Grok-3",
        "Grok-4",
        "GLM 4.7",
        "Flux Pro",
        "Sora 2",
        "Gemma 2",
    )

    ai_companies: ElementsType[str] = (
        "OpenAI",
        "Anthropic",
        "Google DeepMind",
        "Meta AI",
        "Microsoft",
        "Mistral AI",
        "Cohere",
        "Hugging Face",
        "Stability AI",
        "Midjourney",
        "xAI",
        "Inflection AI",
        "AI21 Labs",
        "Aleph Alpha",
        "Character.AI",
        "Adept AI",
        "Runway",
        "Jasper",
        "Scale AI",
        "Databricks",
        "Nvidia",
        "Amazon AWS",
        "IBM Watson",
        "Baidu",
        "Alibaba Cloud",
        "Tencent",
        "ByteDance",
        "Anduril",
        "Grammarly",
        "Hive",
        "Sanctuary",
        "Lambda",
        "Dataiku",
        "Tessian",
        "Reclaim.ai",
        "Fireflies.ai",
        "Roboflow",
        "DevRev",
        "People.ai",
        "Nektar.ai",
        "World Labs",
        "Thinking Machine Labs",
        "Mercor",
        "Anysphere",
    )

    ai_model_architectures: ElementsType[str] = (
        "Transformer",
        "GPT",
        "BERT",
        "T5",
        "Diffusion",
        "GAN",
        "VAE",
        "RNN",
        "LSTM",
        "CNN",
        "ResNet",
        "ViT",
        "Mamba",
        "RWKV",
        "Mixture of Experts",
        "State Space Model",
        "Retrieval-Augmented Generation",
        "Encoder-Decoder",
        "Decoder-Only",
        "Encoder-Only",
        "Vision-Language Model",
        "Agentic AI",
        "Hybrid Model",
        "Dense Model",
    )

    ml_frameworks: ElementsType[str] = (
        "PyTorch",
        "TensorFlow",
        "JAX",
        "Keras",
        "Hugging Face Transformers",
        "scikit-learn",
        "XGBoost",
        "LightGBM",
        "ONNX",
        "MLflow",
        "Weights & Biases",
        "Ray",
        "Dask",
        "Apache Spark MLlib",
        "Fast.ai",
        "Lightning",
        "LangChain",
        "LlamaIndex",
        "vLLM",
        "DeepSpeed",
        "TensorFlow Lite",
        "OpenCV",
        "Caffe",
    )

    ai_tasks: ElementsType[str] = (
        "text-generation",
        "text-classification",
        "question-answering",
        "summarization",
        "translation",
        "sentiment-analysis",
        "named-entity-recognition",
        "fill-mask",
        "text-to-image",
        "image-to-text",
        "image-classification",
        "object-detection",
        "image-segmentation",
        "speech-to-text",
        "text-to-speech",
        "audio-classification",
        "video-classification",
        "zero-shot-classification",
        "feature-extraction",
        "embedding-generation",
        "code-generation",
        "conversational",
        "reinforcement-learning",
        "recommendation",
        "multi-modal generation",
        "agentic workflow",
        "reasoning",
        "world-modeling",
        "autonomous agents",
    )

    ai_model_parameters: ElementsType[str] = (
        "1B",
        "3B",
        "7B",
        "8B",
        "9B",
        "13B",
        "27B",
        "30B",
        "33B",
        "34B",
        "40B",
        "65B",
        "70B",
        "72B",
        "100B",
        "175B",
        "180B",
        "405B",
        "500B",
        "540B",
        "1T",
        "1.5T",
    )

    ai_datasets: ElementsType[str] = (
        "ImageNet",
        "COCO",
        "Common Crawl",
        "The Pile",
        "C4",
        "RedPajama",
        "LAION-5B",
        "Wikipedia",
        "BookCorpus",
        "OpenWebText",
        "Stack Overflow",
        "GitHub Code",
        "MNIST",
        "CIFAR-10",
        "CIFAR-100",
        "LibriSpeech",
        "SQuAD",
        "GLUE",
        "SuperGLUE",
        "MMLU",
        "HumanEval",
        "GSM8K",
        "HellaSwag",
        "TruthfulQA",
        "Dolma",
        "RefinedWeb",
        "FineWeb",
        "Proof-Pile",
        "Boston House Price",
        "Iris",
        "Dog Breed Identification",
    )

    def ai_model(self) -> str:
        return self.random_element(self.ai_models)

    def ai_company(self) -> str:
        return self.random_element(self.ai_companies)

    def ai_model_architecture(self) -> str:
        return self.random_element(self.ai_model_architectures)

    def ml_framework(self) -> str:
        return self.random_element(self.ml_frameworks)

    def ai_task(self) -> str:
        return self.random_element(self.ai_tasks)

    def ai_model_parameter(self) -> str:
        return self.random_element(self.ai_model_parameters)

    def ai_dataset(self) -> str:
        return self.random_element(self.ai_datasets)
