from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = OrderedDict((
        ('{{first_name_female}} {{last_name_female}}', 0.97),
        ('{{prefix_female}} {{first_name_female}} {{last_name_female}}', 0.015),
        ('{{first_name_female}} {{last_name_female}} {{suffix}}', 0.02),
        ('{{prefix_female}} {{first_name_female}} {{last_name_female}} {{suffix}}', 0.005),
    ))

    formats_male = OrderedDict((
        ('{{first_name_male}} {{last_name_male}}', 0.97),
        ('{{prefix_male}} {{first_name_male}} {{last_name_male}}', 0.015),
        ('{{first_name_male}} {{last_name_male}} {{suffix}}', 0.02),
        ('{{prefix_male}} {{first_name_male}} {{last_name_male}} {{suffix}}', 0.005),
    ))

    formats = formats_male.copy()
    formats.update(formats_female)

    first_names_male = (
        "Adam",
        "Adolf",
        "Adrián",
        "Albert",
        "Aleš",
        "Alfonz",
        "Ambróz",
        "Andrej",
        "Anton",
        "Aurel",
        "Bartolomej",
        "Belo",
        "Beňadik",
        "Blahoslav",
        "Bohuslav",
        "Bonifác",
        "Branislav",
        "Ctibor",
        "Cyril",
        "Daniel",
        "Dávid",
        "Demeter",
        "Denis",
        "Dezider",
        "Dobroslav",
        "Dominik",
        "Dušan",
        "Erik",
        "Ervín",
        "Fedor",
        "Félix",
        "Ferdinand",
        "Filip",
        "Florián",
        "František",
        "Gašpar",
        "Gustáv",
        "Hugo",
        "Ignác",
        "Igor",
        "Imrich",
        "Ivan",
        "Jakub",
        "Ján",
        "Jaroslav",
        "Jerguš",
        "Jozef",
        "Július",
        "Juraj",
        "Kamil",
        "Karol",
        "Kazimír",
        "Koloman",
        "Kristián",
        "Krištof",
        "Ladislav",
        "Leopold",
        "Ľubomír",
        "Ľuboslav",
        "Ľuboš",
        "Ľudovít",
        "Lukáš",
        "Marek",
        "Marián",
        "Maroš",
        "Martin",
        "Matúš",
        "Maximilián",
        "Miloš",
        "Miroslav",
        "Norbert",
        "Oliver",
        "Ondrej",
        "Oto",
        "Pankrác",
        "Patrik",
        "Pavol",
        "Peter",
        "Prokop",
        "Radoslav",
        "Radovan",
        "Roland",
        "Rudolf",
        "Samuel",
        "Servác",
        "Silvester",
        "Slavomír",
        "Stanislav",
        "Tibor",
        "Timotej",
        "Tomáš",
        "Václav",
        "Valér",
        "Vasil",
        "Viliam",
        "Vladimír",
        "Vojtech",
        "Zlatko",
        "Zoltán",
        "Žigmund",
        )

    first_names_female = (
        "Adela",
        "Adriána",
        "Agáta",
        "Alica",
        "Alžbeta",
        "Amália",
        "Andrea",
        "Antónia",
        "Beáta",
        "Bibiána",
        "Blanka",
        "Blažena",
        "Božena",
        "Cecília",
        "Dagmara",
        "Dana",
        "Daniela",
        "Dáša",
        "Denisa",
        "Dominika",
        "Dorota",
        "Dušana",
        "Edita",
        "Elena",
        "Eliška",
        "Ema",
        "Emília",
        "Erika",
        "Etela",
        "Eva",
        "Filoména",
        "Františka",
        "Gabriela",
        "Helena",
        "Henrieta",
        "Iveta",
        "Jana",
        "Jarmila",
        "Jaroslava",
        "Judita",
        "Kamila",
        "Karina",
        "Katarína",
        "Klaudia",
        "Kristína",
        "Laura",
        "Libuša",
        "Lívia",
        "Ľubica",
        "Ľubomíra",
        "Ľuboslava",
        "Lucia",
        "Ľudmila",
        "Lýdia",
        "Magdaléna",
        "Marcela",
        "Margaréta",
        "Mária",
        "Marianna",
        "Marína",
        "Marta",
        "Martina",
        "Melánia",
        "Milena",
        "Miriama",
        "Miroslava",
        "Monika",
        "Natália",
        "Nina",
        "Oľga",
        "Otília",
        "Patrícia",
        "Paulína",
        "Renáta",
        "Romana",
        "Rozália",
        "Ružena",
        "Sabína",
        "Sára",
        "Silvia",
        "Slávka",
        "Sofia",
        "Soňa",
        "Stanislava",
        "Štefánia",
        "Tamara",
        "Tatiana",
        "Terézia",
        "Uršuľa",
        "Valentína",
        "Veronika",
        "Viera",
        "Viktória",
        "Vlasta",
        "Zita",
        "Zlatica",
        "Zora",
        "Zuzana",
        "Žaneta",
        "Žofia",
        )

    first_names = first_names_male + first_names_female

    last_names_male = (
        "Abelovský",
        "Baláž",
        "Balog",
        "Bartoš",
        "Beržinský",
        "Bodnár",
        "Capik",
        "Čižmár",
        "Demeter",
        "Džudža",
        "Farkaš",
        "Gábor",
        "Gajdoš",
        "Giba",
        "Horňák",
        "Horváth",
        "Hudák",
        "Hudec",
        "Iľko",
        "Jaššo",
        "Karička",
        "Kollár",
        "Kovács",
        "Kováč",
        "Kováčik",
        "Lacko",
        "Lakatoš",
        "Lukáč",
        "Molnár",
        "Moravčík",
        "Nagy",
        "Németh",
        "Novák",
        "Oláh",
        "Oravec",
        "Pavlík",
        "Polák",
        "Pulko",
        "Rusnák",
        "Szabó",
        "Šandor",
        "Šimko",
        "Štefanko",
        "Tóth",
        "Turčan",
        "Urban",
        "Varga",
        "Vojvoda",
        "Zajac",
        "Žabecká",
        )

    last_names_female = (
        "Abelovská",
        "Balážová",
        "Balogová",
        "Bartošová",
        "Beňová",
        "Beržinská",
        "Bodnárová",
        "Capiková",
        "Čižmárová",
        "Demeterová",
        "Džudžová",
        "Farkašová",
        "Gajdošová",
        "Gibová",
        "Horňákoví",
        "Horváthová",
        "Hudáková",
        "Hudecová",
        "Iľková",
        "Jaššová",
        "Karičková",
        "Kollárová",
        "Kovácsová",
        "Kováčiková",
        "Kováčová",
        "Lacková",
        "Lakatošová",
        "Lukáčová",
        "Molnárová",
        "Moravčíková",
        "Nagyová",
        "Némethová",
        "Nováková",
        "Oláhová",
        "Oravcová",
        "Pavlíková",
        "Poláková",
        "Pulková",
        "Rusnáková",
        "Szabóová",
        "Szabová",
        "Šandorová",
        "Šimková",
        "Štefanková",
        "Tóthová",
        "Turčanová",
        "Vargová",
        "Vojvodová",
        "Zajacová",
        "Žabecká",
        )

    last_names = last_names_male + last_names_female

    degrees = ('JUDr.', 'Ing.', 'Bc.', 'Mgr.', 'MUDr.', 'RNDr.')

    prefixes_male = ('pan', ) + degrees

    prefixes_female = ('paní', 'slečna') + degrees

    suffixes = ('CSc.', 'DiS.', 'Ph.D.', 'Th.D.')
