# coding=utf-8
from __future__ import unicode_literals
from ..address import Provider as AddressProvider


class Provider(AddressProvider):

    city_formats = ('{{city_name}}', )

    street_name_formats = ('{{street_name}}', )
    street_address_formats = ('{{street_name}} {{building_number}}', )
    address_formats = ('{{street_address}}\n{{postcode}} {{city}}', )

    building_number_formats = ('###', '##', '#', '#a', '#b', '#c')

    postcode_formats = ('####', )

    cities = (
        "Ajdovščina", "Bled", "Bovec", "Brežice", "Celje", "Cerknica", "Črnomelj", "Domžale", 
        "Dravograd", "Gornja Radgona", "Gornji Grad", "Grosuplje", "Hrastnik", 
        "Idrija", "Ilirska Bistrica", "Izola", "Jesenice", "Kamnik", "Kobarid", 
        "Kočevje", "Koper", "Kostanjevica na Krki", "Kranj", "Krško", "Laško", 
        "Lenart v Slovenskih goricah", "Lendava", "Litija", "Ljubljana", "Ljutomer", 
        "Logatec", "Maribor", "Medvode", "Mengeš", "Metlika", "Mežica", "Murska Sobota", 
        "Nova Gorica", "Novo mesto", "Ormož", "Piran", "Postojna", "Prevalje", "Ptuj", 
        "Radeče", "Radovljica", "Ravne na Koroškem", "Ribnica", "Rogaška Slatina", 
        "Ruše", "Sevnica", "Sežana", "Slovenj Gradec", "Slovenska Bistrica", 
        "Slovenske Konjice", "Šempeter pri Gorici", "Šentjur", "Škofja Loka", 
        "Šoštanj", "Tolmin", "Trbovlje", "Trebnje", "Tržič", "Turnišče", "Velenje", 
        "Vipava", "Vipavski Križ", "Višnja Gora", "Vrhnika", "Zagorje ob Savi", 
        "Žalec", "Železniki", "Žiri",
    )

    streets = (
        "Abramova ulica",
        "Adamičeva ulica",
        "Adamič-Lundrovo nabrežje",
        "Agrokombinatska cesta",
        "Ajdovščina",
        "Aleševa ulica",
        "Alešovčeva ulica",
        "Aličeva ulica",
        "Aljaževa ulica",
        "Ambrožev trg",
        "Ameriška ulica",
        "Andreaševa ulica",
        "Andrićeva ulica",
        "Anžurjeva ulica",
        "Apihova ulica",
        "Archinetova ulica",
        "Argentinska ulica",
        "Arharjeva cesta",
        "Arkova ulica",
        "Arničeva ulica",
        "Artačeva ulica",
        "Aškerčeva cesta",
        "Avčinova ulica",
        "Avgustinčičeva ulica",
        "Avsečeva ulica",
        "Avstrijska ulica",
        "Avšičeva cesta",
        "Ažbetova ulica",
        "Ažmanova ulica",
        "Babičeva ulica",
        "Badjurova ulica",
        "Bajtova ulica",
        "Balinarska pot",
        "Baragova ulica",
        "Barjanska cesta",
        "Barvarska steza",
        "Bavdkova ulica",
        "Baznikova ulica",
        "Bazoviška ulica",
        "Beblerjev trg",
        "Beethovnova ulica",
        "Belačeva ulica",
        "Beljaška ulica",
        "Belokranjska ulica",
        "Berčičeva ulica",
        "Berčonova pot",
        "Berdajsova ulica",
        "Bergantova ulica",
        "Bernekerjeva ulica",
        "Bernikova ulica",
        "Betettova cesta",
        "Bevkova cesta",
        "Bezenškova ulica",
        "Bežigrad",
        "Bičevje",
        "Bilečanska ulica",
        "Bistriška ulica",
        "Bitenčeva ulica",
        "Bizjakova ulica",
        "Bizjanova ulica",
        "Bizoviška cesta",
        "Bizovški štradon",
        "Blasnikova ulica",
        "Blasov breg",
        "Blažičeva ulica",
        "Bleiweisova cesta",
        "Bobenčkova ulica",
        "Bobrova ulica",
        "Bogišićeva ulica",
        "Bognarjeva pot",
        "Bohinjčeva ulica",
        "Bohoričeva ulica",
        "Bokalova ulica",
        "Boletova ulica",
        "Bolgarska ulica",
        "Borovniška ulica",
        "Borsetova ulica",
        "Borštnikov trg",
        "Borutova ulica",
        "Božičeva ulica",
        "Brajnikova ulica",
        "Brankova ulica",
        "Bratinova ulica",
        "Bratislavska cesta",
        "Bratov Čebuljev ulica",
        "Bratov Jakopičev ulica",
        "Bratov Kunovarjev ulica",
        "Bratovševa ploščad",
        "Bravničarjeva ulica",
        "Brdnikova ulica",
        "Breg",
        "Bregarjeva ulica",
        "Brejčeva ulica",
        "Breznikova ulica",
        "Brglezov štradon",
        "Brilejeva ulica",
        "Brnčičeva ulica",
        "Brodarjev trg",
        "Brodska cesta",
        "Burnikova ulica",
        "Cankarjev vrh",
        "Cankarjeva cesta",
        "Cankarjevo nabrežje",
        "Carja Dušana ulica",
        "Celarčeva ulica",
        "Celestinova ulica",
        "Celjska ulica",
        "Celovška cesta",
        "Cerkniška ulica",
        "Cerkova ulica",
        "Cerutova ulica",
        "Cesta Andreja Bitenca",
        "Cesta Ceneta Štuparja",
        "Cesta Cirila Kosmača",
        "Cesta Dolomitskega odreda",
        "Cesta dveh cesarjev",
        "Cesta II. grupe odredov",
        "Cesta Janeza Porente",
        "Cesta Ljubljanske brigade",
        "Cesta na Bellevue",
        "Cesta na Bokalce",
        "Cesta na Brdo",
        "Cesta na Brinovec",
        "Cesta na Brod",
        "Cesta na Ježah",
        "Cesta na Ključ",
        "Cesta na Kope",
        "Cesta na Laze",
        "Cesta na Loko",
        "Cesta na Mesarico",
        "Cesta na Obrije",
        "Cesta na Ozare",
        "Cesta na Poljane",
        "Cesta na Prevoje",
        "Cesta na Rožnik",
        "Cesta na Urh",
        "Cesta na Vrhovce",
        "Cesta slov. kmečkih uporov",
        "Cesta španskih borcev",
        "Cesta Urške Zatlerjeve",
        "Cesta v Dvor",
        "Cesta v Gameljne",
        "Cesta v Gorice",
        "Cesta v Hrastje",
        "Cesta v hrib",
        "Cesta v Kleče",
        "Cesta v Kostanj",
        "Cesta v Kresnice",
        "Cesta v Legarico",
        "Cesta v Mestni log",
        "Cesta v Pečale",
        "Cesta v Podboršt",
        "Cesta v Prod",
        "Cesta v Rožno dolino",
        "Cesta v Šmartno",
        "Cesta v Zajčjo dobravo",
        "Cesta v Zeleni log",
        "Cesta v Zgornji log",
        "Cesta vstaje",
        "Cesta 13. julija",
        "Cesta 24. junija",
        "Cesta 25 talcev",
        "Cesta 27. aprila",
        "Cesta 30. avgusta",
        "Chengdujska cesta",
        "Chopinov prehod",
        "Cigaletova ulica",
        "Ciglerjeva ulica",
        "Cilenškova ulica",
        "Cimermanova ulica",
        "Cimpermanova ulica",
        "Ciril-Metodov trg",
        "Cizejeva ulica",
        "Clevelandska ulica",
        "Colnarjeva ulica",
        "Cvetkova ulica",
        "Cvetlična pot",
        "Čampova ulica",
        "Čanžekova ulica",
        "Čapova ulica",
        "Čargova ulica",
        "Čebelarska ulica",
        "Čehova ulica",
        "Čemažarjeva ulica",
        "Čepelnikova ulica",
        "Čepovanska ulica",
        "Čerinova ulica",
        "Černetova ulica",
        "Černigojeva ulica",
        "Černivčeva ulica",
        "Červanova ulica",
        "Česnikova ulica",
        "Čevljarska ulica",
        "Čižmanova ulica",
        "Čopova ulica",
        "Črna pot",
        "Črna vas",
        "Črnuška cesta",
        "Črtomirova ulica",
        "Čučkova ulica",
        "Čufarjeva ulica",
        "Dajnkova ulica",
        "Dalmatinova ulica",
        "Danile Kumarjeve ulica",
        "Davčna ulica",
        "Dečkova ulica",
        "Dečmanova ulica",
        "Delakova ulica",
        "Delavska ulica",
        "Demšarjeva cesta",
        "Derčeva ulica",
        "Dergančeva ulica",
        "Dergomaška ulica",
        "Dermotova ulica",
        "Detelova ulica",
        "Devinska ulica",
        "Devova ulica",
        "Dimičeva ulica",
        "Divjakova ulica",
        "Do proge",
        "Dobrajčeva ulica",
        "Dobrdobska ulica",
        "Dobrunjska cesta",
        "Dolenjska cesta",
        "Dolgi breg",
        "Dolgi most",
        "Dolharjeva ulica",
        "Dolina",
        "Dolinarjeva ulica",
        "Dolinškova ulica",
        "Dolničarjeva ulica",
        "Dolniška cesta",
        "Dolomitska ulica",
        "Drabosnjakova ulica",
        "Draga",
        "Draveljska ulica",
        "Dravska ulica",
        "Dražgoška ulica",
        "Drenikov vrh",
        "Drenikova ulica",
        "Društvena ulica",
        "Dunajska cesta",
        "Dvojna ulica",
        "Dvorakova ulica",
        "Dvorni trg",
        "Einspielerjeva ulica",
        "Eipprova ulica",
        "Ellerjeva ulica",
        "Emonska cesta",
        "Endliherjeva ulica",
        "Erbežnikova ulica",
        "Erjavčeva cesta",
        "Fabianijeva ulica",
        "Fajfarjeva ulica",
        "Fani Grumove ulica",
        "Ferberjeva ulica",
        "Filipičeva ulica",
        "Finžgarjeva ulica",
        "Flajšmanova ulica",
        "Flandrova ulica",
        "Forsterjeva ulica",
        "Francoska ulica",
        "Franketova ulica",
        "Frankopanska ulica",
        "Frenkova pot",
        "Freyerjeva ulica",
        "Friškovec",
        "Funtkova ulica",
        "Fužinska cesta",
        "Gabrov trg",
        "Gabrščkova ulica",
        "Gača",
        "Galičeva ulica",
        "Galjevica",
        "Gallusovo nabrežje",
        "Gameljska cesta",
        "Gasilska cesta",
        "Gasparijeva ulica",
        "Gašperšičeva ulica",
        "Gerberjevo stopnišče",
        "Gerbičeva ulica",
        "Gestrinova ulica",
        "Glavarjeva ulica",
        "Gledališka pasaža",
        "Gledališka stolba",
        "Glinška ulica",
        "Glinškova ploščad",
        "Globočnikova ulica",
        "Glonarjeva ulica",
        "Gmajnice",
        "Gobarska pot",
        "Godeževa ulica",
        "Gogalova ulica",
        "Gola Loka",
        "Golarjeva ulica",
        "Goljarjeva pot",
        "Golouhova ulica",
        "Gorazdova ulica",
        "Goriška ulica",
        "Gorjančeva ulica",
        "Gorjupova ulica",
        "Gorkičeva ulica",
        "Gornji Rudnik I",
        "Gornji Rudnik II",
        "Gornji Rudnik III",
        "Gornji Rudnik IV",
        "Gornji trg",
        "Goropečnikova ulica",
        "Gortanova ulica",
        "Gosarjeva ulica",
        "Gospodinjska ulica",
        "Gosposka ulica",
        "Gosposvetska cesta",
        "Gotska ulica",
        "Govekarjeva ulica",
        "Gozdna pot",
        "Grablovičeva ulica",
        "Gradaška ulica",
        "Gradišče",
        "Gradnikova ulica",
        "Grafenauerjeva ulica",
        "Grajska planota",
        "Grajski drevored",
        "Grajzerjeva ulica",
        "Gramozna pot",
        "Grampovčanova ulica",
        "Grassellijeva ulica",
        "Gregorčičeva ulica",
        "Gregorinova ulica",
        "Grič",
        "Grintovška ulica",
        "Grobeljca",
        "Grobeljska pot",
        "Groharjeva cesta",
        "Grošljeva ulica",
        "Groznikova ulica",
        "Grška ulica",
        "Grško",
        "Gruberjevo nabrežje",
        "Grudnova ulica",
        "Grudnovo nabrežje",
        "Gubčeva ulica",
        "Gunceljska cesta",
        "Gundulićeva ulica",
        "Gustinčarjeva ulica",
        "Gustinčičeva ulica",
        "Hacetova ulica",
        "Hacquetova ulica",
        "Hafnerjeva ulica",
        "Hajdrihova ulica",
        "Hauptmanca",
        "Herbersteinova ulica",
        "Hladilniška pot",
        "Hladnikova cesta",
        "Hlebčeva ulica",
        "Hodoščkova ulica",
        "Hotimirova ulica",
        "Hradeckega cesta",
        "Hranilniška ulica",
        "Hrenova ulica",
        "Hribarjevo nabrežje",
        "Hribernikova ulica",
        "Hribovska pot",
        "Hruševska cesta",
        "Hrvaška ulica",
        "Hrvatski trg",
        "Hubadova ulica",
        "Hudourniška pot",
        "Hudovernikova ulica",
        "Idrijska ulica",
        "Igriška ulica",
        "Ilešičeva ulica",
        "Ilirska ulica",
        "Ilovški štradon",
        "Industrijska cesta",
        "Ingličeva ulica",
        "Ipavčeva ulica",
        "Italijanska ulica",
        "Izletniška ulica",
        "Ižanska cesta",
        "Jadranska ulica",
        "Jakčeva ulica",
        "Jakhljeva ulica",
        "Jakopičev drevored",
        "Jakopičeva ulica",
        "Jakopičevo sprehajališče",
        "Jakšičeva ulica",
        "Jalnova ulica",
        "Jamnikarjeva ulica",
        "Jamova cesta",
        "Janežičeva cesta",
        "Janova ulica",
        "Janševa ulica",
        "Japljeva ulica",
        "Jarčeva ulica",
        "Jarnikova ulica",
        "Jarše",
        "Jarška cesta",
        "Javorjev drevored",
        "Javorškova ulica",
        "Jazbečeva pot",
        "Jelinčičeva ulica",
        "Jelovškova ulica",
        "Jenkova ulica",
        "Jensenova ulica",
        "Jerajeva ulica",
        "Jerančičeva ulica",
        "Jeranova ulica",
        "Jesenkova ulica",
        "Jesihov štradon",
        "Jezerska pot",
        "Jezerska ulica",
        "Ježa",
        "Ježica",
        "Joškov štradon",
        "Jurčeva ulica",
        "Jurčičev trg",
        "Jurčkova cesta",
        "Juričeva ulica",
        "Justinova ulica",
        "Juvanova ulica",
        "K reaktorju",
        "Kadilnikova ulica",
        "Kajakaška cesta",
        "Kajuhova ulica",
        "Kalingerjeva ulica",
        "Kalinova ulica",
        "Kališnikov trg",
        "Kaminova ulica",
        "Kamniška ulica",
        "Kamnogoriška cesta",
        "Kamnoseška ulica",
        "Kančeva ulica",
        "Kanonijeva cesta",
        "Kantetova ulica",
        "Kapiteljska ulica",
        "Kapusova ulica",
        "Kardeljeva ploščad",
        "Karingerjeva ulica",
        "Karlovška cesta",
        "Karunova ulica",
        "Kastelčeva ulica",
        "Kašeljska cesta",
        "Katreževa pot",
        "Kavadarska cesta",
        "Kavčičeva ulica",
        "Kavškova ulica",
        "Kebetova ulica",
        "Kekčeva ulica",
        "Kermaunerjeva ulica",
        "Kernova cesta",
        "Kersnikova ulica",
        "Kerševanova ulica",
        "Keržičeva ulica",
        "Kettejeva ulica",
        "Kikljeva ulica",
        "Kladezna ulica",
        "Klančarjeva ulica",
        "Kleče",
        "Klemenčičeva ulica",
        "Klemenova ulica",
        "Kleparska steza",
        "Ključavničarska ulica",
        "Klopčičeva ulica",
        "Klunova ulica",
        "Kmečka pot",
        "Knafljev prehod",
        "Kneza Koclja ulica",
        "Knezov štradon",
        "Knezova ulica",
        "Knobleharjeva ulica",
        "Kobetova ulica",
        "Koblarjeva ulica",
        "Kocbekova ulica",
        "Kocenova ulica",
        "Kocjančičeva ulica",
        "Kocjanova ulica",
        "Kočenska ulica",
        "Kodrova ulica",
        "Kogejeva ulica",
        "Kogojeva ulica",
        "Kogovškova ulica",
        "Kokaljeva ulica",
        "Kolajbova ulica",
        "Kolarjeva ulica",
        "Kolesarska pot",
        "Koleševa ulica",
        "Kolezijska ulica",
        "Kolinska ulica",
        "Kolmanova ulica",
        "Kolodvorska ulica",
        "Komacova ulica",
        "Komanova ulica",
        "Komenskega ulica",
        "Kongresni trg",
        "Kopačeva cesta",
        "Kopališka ulica",
        "Kopitarjeva ulica",
        "Kopna pot",
        "Koprska ulica",
        "Korenčanova ulica",
        "Koreninova ulica",
        "Koroška ulica",
        "Korotanska ulica",
        "Korytkova ulica",
        "Kosančeva ulica",
        "Koseskega ulica",
        "Koseška cesta",
        "Kosijeva ulica",
        "Kosmačeva ulica",
        "Kosova ulica",
        "Kosovelova ulica",
        "Koščeva ulica",
        "Koširjeva ulica",
        "Kotnikova ulica",
        "Kovačeva ulica",
        "Kovačičeva ulica",
        "Kovaška ulica",
        "Kovinarska ulica",
        "Kozakova ulica",
        "Kozarska cesta",
        "Kozinova ulica",
        "Kozlarjeva pot",
        "Koželjeva ulica",
        "Krakovska ulica",
        "Krakovski nasip",
        "Kraljeva ulica",
        "Kranerjeva ulica",
        "Kranjčeva ulica",
        "Kraška ulica",
        "Kratka pot",
        "Kratka steza",
        "Kregarjeva ulica",
        "Krekov trg",
        "Kreljeva ulica",
        "Kremžarjeva ulica",
        "Krimska ulica",
        "Kristanova ulica",
        "Krištofova ulica",
        "Kriva pot",
        "Krivec",
        "Križevniška soteska",
        "Križevniška ulica",
        "Križna ulica",
        "Krmčeva ulica",
        "Krmeljeva ulica",
        "Krojaška ulica",
        "Kropova ulica",
        "Krošljeva ulica",
        "Krovska ulica",
        "Krožna pot",
        "Krvinova ulica",
        "Kržičeva ulica",
        "Kudrova ulica",
        "Kuhljeva cesta",
        "Kumanovska ulica",
        "Kumerdejeva ulica",
        "Kumerjeve ulica",
        "Kumrovška ulica",
        "Kunaverjeva ulica",
        "Kurilniška ulica",
        "Kurirska ulica",
        "Kusoldova ulica",
        "Kušarjeva ulica",
        "Kuštrinova ulica",
        "Kuzeletova ulica",
        "Kuzmičeva ulica",
        "Kvedrova cesta",
        "Lahova pot",
        "Lajovčeva ulica",
        "Laknerjeva ulica",
        "Lakotence",
        "Lambergarjeva ulica",
        "Lampetova ulica",
        "Lamutova ulica",
        "Langusova ulica",
        "Latinski trg",
        "Lavričeva ulica",
        "Lavrinova ulica",
        "Layerjeva ulica",
        "Lazarjeva ulica",
        "Ledarska ulica",
        "Legatova ulica",
        "Lemeževa ulica",
        "Lepi pot",
        "Lepodvorska ulica",
        "Leskoškova cesta",
        "Leskovičeva ulica",
        "Letališka cesta",
        "Levarjeva ulica",
        "Levčeva ulica",
        "Levičnikova ulica",
        "Levstikov trg",
        "Levstikova ulica",
        "Likozarjeva ulica",
        "Linhartov podhod",
        "Linhartova cesta",
        "Lipahova ulica",
        "Lipovškova ulica",
        "Litijska cesta",
        "Litostrojska cesta",
        "Livada",
        "Livarska ulica",
        "Ljubeljska ulica",
        "Ločnikarjeva ulica",
        "Lončarska steza",
        "Lorenzova cesta",
        "Lotričeva ulica",
        "Lovrenčičeva ulica",
        "Lovska ulica",
        "Lovšetova ulica",
        "Ložarjeva ulica",
        "Lubejeva ulica",
        "Luize Pesjakove ulica",
        "Lunačkova ulica",
        "Lužiško-srbska ulica",
        "Mačja steza",
        "Mačkov kot",
        "Mačkova ulica",
        "Madžarska ulica",
        "Magajnova ulica",
        "Magistrova ulica",
        "Maistrova ulica",
        "Majaronova ulica",
        "Majde Šilčeve ulica",
        "Majde Vrhovnikove ulica",
        "Majorja Lavriča ulica",
        "Makucova ulica",
        "Mala čolnarska ulica",
        "Mala ulica",
        "Mala vas",
        "Malejeva ulica",
        "Malenškova ulica",
        "Maleševa ulica",
        "Malgajeva ulica",
        "Mali štradon",
        "Mali trg",
        "Malnarjeva ulica",
        "Malova ulica",
        "Marčenkova ulica",
        "Marentičeva ulica",
        "Mareška pot",
        "Mariborska ulica",
        "Marice Kovačeve ulica",
        "Marincljeva ulica",
        "Marinovševa cesta",
        "Marjekova pot",
        "Maroltova ulica",
        "Martina Krpana ulica",
        "Martinčeva ulica",
        "Martinova pot",
        "Martinova ulica",
        "Marušičeva ulica",
        "Masarykova cesta",
        "Mašera-Spasićeva ulica",
        "Matjanova pot",
        "Matjaževa ulica",
        "Maurerjeva ulica",
        "Mazijeva ulica",
        "Mazovčeva pot",
        "Med hmeljniki",
        "Medarska ulica",
        "Medenska cesta",
        "Medvedova cesta",
        "Medveščkova ulica",
        "Mekinčeva ulica",
        "Melikova ulica",
        "Menardova ulica",
        "Mencingerjeva ulica",
        "Merčnikova ulica",
        "Merosodna ulica",
        "Mesarska cesta",
        "Mesesnelova ulica",
        "Mestni trg",
        "Meškova ulica",
        "Metelkova ulica",
        "Metliška ulica",
        "Miheličeva cesta",
        "Mihov štradon",
        "Miklavčeva ulica",
        "Miklošičev park",
        "Miklošičeva cesta",
        "Mikuževa ulica",
        "Milčetova pot",
        "Milčinskega ulica",
        "Mire Lenardičeve ulica",
        "Mirje",
        "Mirna pot",
        "Mislejeva ulica",
        "Mivka",
        "Mizarska pot",
        "Mladinska ulica",
        "Mlake",
        "Mlinska pot",
        "Močilnikarjeva ulica",
        "Močnikova ulica",
        "Mokrška ulica",
        "Molekova ulica",
        "Moskovska ulica",
        "Moškričeva ulica",
        "Mrharjeva ulica",
        "Mrzelova ulica",
        "Mucherjeva ulica",
        "Murkova ulica",
        "Murnikova ulica",
        "Murnova ulica",
        "Muzejska ulica",
        "Na brežini",
        "Na cvetači",
        "Na delih",
        "Na dolih",
        "Na gaju",
        "Na gmajni",
        "Na griču",
        "Na Herši",
        "Na jami",
        "Na klančku",
        "Na Korošci",
        "Na Palcah",
        "Na peči",
        "Na požaru",
        "Na produ",
        "Na Rojah",
        "Na Stolbi",
        "Na Straški vrh",
        "Na tezi",
        "Na Trati",
        "Na Žalah",
        "Nade Ovčakove ulica",
        "Nadgoriška cesta",
        "Nagodetova ulica",
        "Nahlikova ulica",
        "Nahtigalova ulica",
        "Nanoška ulica",
        "Nasperska pot",
        "Nazorjeva ulica",
        "Nebotičnikov prehod",
        "Nedohova ulica",
        "Neubergerjeva ulica",
        "Njegoševa cesta",
        "Nova ulica",
        "Novakova pot",
        "Novakova ulica",
        "Nove Fužine",
        "Novi trg",
        "Novinarska ulica",
        "Novo naselje",
        "Novo Polje, cesta I",
        "Novo Polje, cesta II",
        "Novo Polje, cesta III",
        "Novo Polje, cesta IV",
        "Novo Polje, cesta IX",
        "Novo Polje, cesta V",
        "Novo Polje, cesta VI",
        "Novo Polje, cesta VII",
        "Novo Polje, cesta VIII",
        "Novo Polje, cesta X",
        "Novo Polje, cesta XI",
        "Novo Polje, cesta XII",
        "Novo Polje, cesta XIII",
        "Novo Polje, cesta XIV",
        "Novo Polje, cesta XIX",
        "Novo Polje, cesta XV",
        "Novo Polje, cesta XVI",
        "Novo Polje, cesta XVII",
        "Novo Polje, cesta XVIII",
        "Novo Polje, cesta XXI",
        "Novo Polje, cesta XXIII",
        "Novosadska ulica",
        "Nusdorferjeva ulica",
        "Ob daljnovodu",
        "Ob dolenjski železnici",
        "Ob Farjevcu",
        "Ob kamniški progi",
        "Ob Ljubljanici",
        "Ob Mejašu",
        "Ob potoku",
        "Ob pristanu",
        "Ob Savi",
        "Ob sotočju",
        "Ob studencu",
        "Ob zdravstvenem domu",
        "Ob zeleni jami",
        "Ob zelenici",
        "Ob železnici",
        "Ob žici",
        "Obirska ulica",
        "Obrežna steza",
        "Obrije",
        "Obvozna cesta",
        "Ocvirkova ulica",
        "Ogrinčeva ulica",
        "Okiškega ulica",
        "Okrogarjeva ulica",
        "Omahnova ulica",
        "Omejčeva ulica",
        "Omersova ulica",
        "Opekarska cesta",
        "Oražnova ulica",
        "Orlova ulica",
        "Osenjakova ulica",
        "Oslavijska ulica",
        "Osojna pot",
        "Osojna steza",
        "Osterčeva ulica",
        "Ovčakova ulica",
        "Ovinki",
        "Pahorjeva ulica",
        "Palmejeva ulica",
        "Papirniška pot",
        "Papirniški trg",
        "Park Ajdovščina",
        "Park Arturo Toscanini",
        "Park slovenske reformacije",
        "Parmova ulica",
        "Parmska cesta",
        "Partizanska ulica",
        "Pasterkova pot",
        "Pavlovčeva ulica",
        "Pavšičeva ulica",
        "Pečarjeva ulica",
        "Pečinska ulica",
        "Pečnik",
        "Pečnikova ulica",
        "Pegamova ulica",
        "Perčeva ulica",
        "Peričeva ulica",
        "Periška cesta",
        "Perkova ulica",
        "Peršinova cesta",
        "Peruzzijeva ulica",
        "Pesarska cesta",
        "Pestotnikova ulica",
        "Peščena pot",
        "Peternelova ulica",
        "Petkova ulica",
        "Petkovškovo nabrežje",
        "Petrčeva ulica",
        "Petričeva ulica",
        "Pilonova ulica",
        "Pionirska pot",
        "Pipanova pot",
        "Pirnatova ulica",
        "Pivovarniška ulica",
        "Planinska cesta",
        "Planinškova ulica",
        "Plečnikov podhod",
        "Plečnikov trg",
        "Plemljeva ulica",
        "Plešičeva ulica",
        "Pleteršnikova ulica",
        "Plevančeva ulica",
        "Pločanska ulica",
        "Pod akacijami",
        "Pod bregom",
        "Pod bresti",
        "Pod brezami",
        "Pod bukvami",
        "Pod Debnim vrhom",
        "Pod gabri",
        "Pod gozdom",
        "Pod gričem",
        "Pod hrasti",
        "Pod hribom",
        "Pod hruško",
        "Pod jelšami",
        "Pod jeseni",
        "Pod jezom",
        "Pod ježami",
        "Pod Kamno gorico",
        "Pod klancem",
        "Pod kostanji",
        "Pod lipami",
        "Pod topoli",
        "Pod Trančo",
        "Pod turnom",
        "Pod vrbami",
        "Podgorica",
        "Podgornikova ulica",
        "Podgorska cesta",
        "Podgrajska cesta",
        "Podhod Ajdovščina",
        "Podjunska ulica",
        "Podlimbarskega ulica",
        "Podmilščakova ulica",
        "Podmolniška cesta",
        "Podrožniška pot",
        "Podsmreška cesta",
        "Podutiška cesta",
        "Podvozna pot",
        "Pogačarjev trg",
        "Pohlinova ulica",
        "Poklukarjeva ulica",
        "Pokopališka ulica",
        "Polakova ulica",
        "Polanškova ulica",
        "Poljanska cesta",
        "Poljanski nasip",
        "Polje",
        "Polje, cesta I",
        "Polje, cesta II",
        "Polje, cesta III",
        "Polje, cesta V",
        "Polje, cesta VI",
        "Polje, cesta VIII",
        "Polje, cesta X",
        "Polje, cesta XII",
        "Polje, cesta XIV",
        "Polje, cesta XL",
        "Polje, cesta XLII",
        "Polje, cesta XLIV",
        "Polje, cesta XLVI",
        "Polje, cesta XVI",
        "Polje, cesta XVIII",
        "Polje, cesta XX",
        "Polje, cesta XXII",
        "Polje, cesta XXIV",
        "Polje, cesta XXVI",
        "Polje, cesta XXVIII",
        "Polje, cesta XXX",
        "Polje, cesta XXXII",
        "Polje, cesta XXXIV",
        "Polje, cesta XXXVI",
        "Polje, cesta XXXVIII",
        "Poljedelska ulica",
        "Poljska pot",
        "Popovičeva ulica",
        "Porentova ulica",
        "Posavskega ulica",
        "Postojnska ulica",
        "Pot čez gmajno",
        "Pot do šole",
        "Pot Draga Jakopiča",
        "Pot heroja Trtnika",
        "Pot ilegalcev",
        "Pot k igrišču",
        "Pot k ribniku",
        "Pot k Savi",
        "Pot k sejmišču",
        "Pot k skakalnici",
        "Pot k studencu",
        "Pot na Breje",
        "Pot na Drenikov vrh",
        "Pot na Fužine",
        "Pot na Golovec",
        "Pot na goro",
        "Pot na Gradišče",
        "Pot na Grič",
        "Pot na Hreše",
        "Pot na Labar",
        "Pot na mah",
        "Pot na most",
        "Pot na Orle",
        "Pot na Rakovo jelšo",
        "Pot na Visoko",
        "Pot na Zduše",
        "Pot Rdečega križa",
        "Pot sodarjev",
        "Pot v boršt",
        "Pot v Čeželj",
        "Pot v dolino",
        "Pot v Goričico",
        "Pot v Hrastovec",
        "Pot v hribec",
        "Pot v mejah",
        "Pot v Mlake",
        "Pot v Podgorje",
        "Pot v Smrečje",
        "Pot v Zeleni gaj",
        "Pot za Brdom",
        "Pot za razori",
        "Potočnikova ulica",
        "Potokarjeva ulica",
        "Potrčeva ulica",
        "Povšetova ulica",
        "Praprotnikova ulica",
        "Prašnikarjeva ulica",
        "Praznikova ulica",
        "Pražakova ulica",
        "Prečna ulica",
        "Pred Savljami",
        "Predjamska cesta",
        "Predor pod Gradom",
        "Pregljeva ulica",
        "Preglov trg",
        "Prekmurska ulica",
        "Prelčeva ulica",
        "Preloge",
        "Prelovčeva ulica",
        "Premrlova ulica",
        "Preradovićeva ulica",
        "Preserska ulica",
        "Presetnikova ulica",
        "Prešernov trg",
        "Prešernova cesta",
        "Pretnarjeva ulica",
        "Prežihova ulica",
        "Pri borštu",
        "Pri brvi",
        "Pri malem kamnu",
        "Pri mostiščarjih",
        "Pri velikem kamnu",
        "Pribinova ulica",
        "Prijateljeva ulica",
        "Primorska ulica",
        "Primožičeva ulica",
        "Prinčičeva ulica",
        "Prisojna ulica",
        "Prištinska ulica",
        "Privoz",
        "Privškova ulica",
        "Proletarska cesta",
        "Prule",
        "Prušnikova ulica",
        "Prvomajska ulica",
        "Pržanjska ulica",
        "Pšatnik",
        "Pšatska pot",
        "Ptujska ulica",
        "Pučnikova ulica",
        "Pugljeva ulica",
        "Puharjeva ulica",
        "Puhova ulica",
        "Puhtejeva ulica",
        "Pustovrhova ulica",
        "Puterlejeva ulica",
        "Putrihova ulica",
        "Raičeva ulica",
        "Rakarska ulica",
        "Rakovniška ulica",
        "Rakuševa ulica",
        "Ramovševa ulica",
        "Rašiška ulica",
        "Ravbarjeva ulica",
        "Ravna pot",
        "Ravnikova ulica",
        "Razdevškova ulica",
        "Razgledna steza",
        "Reber",
        "Reboljeva ulica",
        "Rečna ulica",
        "Redelonghijeva ulica",
        "Regentova cesta",
        "Resljeva cesta",
        "Reška ulica",
        "Rezijanska ulica",
        "Ribičičeva ulica",
        "Ribji trg",
        "Ribniška ulica",
        "Riharjeva ulica",
        "Rimska cesta",
        "Rjava cesta",
        "Robbova ulica",
        "Robičeva ulica",
        "Rocenska ulica",
        "Rodičeva ulica",
        "Rojčeva ulica",
        "Romavhova ulica",
        "Rosna pot",
        "Roška cesta",
        "Rotarjeva ulica",
        "Rovšnikova ulica",
        "Rozmanova ulica",
        "Rožančeva cesta",
        "Rožanska ulica",
        "Rožičeva ulica",
        "Rožna dolina, cesta I",
        "Rožna dolina, cesta II",
        "Rožna dolina, cesta III",
        "Rožna dolina, cesta IV",
        "Rožna dolina, cesta IX",
        "Rožna dolina, cesta V",
        "Rožna dolina, cesta VI",
        "Rožna dolina, cesta VII",
        "Rožna dolina, cesta VIII",
        "Rožna dolina, cesta X",
        "Rožna dolina, cesta XI",
        "Rožna dolina, cesta XII",
        "Rožna dolina, cesta XIII",
        "Rožna dolina, cesta XIX",
        "Rožna dolina, cesta XV",
        "Rožna dolina, cesta XVII",
        "Rožna dolina, cesta XXI",
        "Rožna ulica",
        "Rudnik I",
        "Rudnik II",
        "Rudnik III",
        "Runkova ulica",
        "Rusjanov trg",
        "Ruska ulica",
        "Rutarjeva ulica",
        "Sadinja vas",
        "Sajovčeva ulica",
        "Salendrova ulica",
        "Samova ulica",
        "Saškova ulica",
        "Sattnerjeva ulica",
        "Saveljska cesta",
        "Savinova ulica",
        "Savinškova ulica",
        "Savlje",
        "Savska cesta",
        "Scopolijeva ulica",
        "Sedejeva ulica",
        "Selanov trg",
        "Selanova ulica",
        "Seliškarjeva ulica",
        "Setnikarjeva ulica",
        "Seunigova ulica",
        "Simončičeva ulica",
        "Simonitijeva ulica",
        "Siva pot",
        "Skapinova ulica",
        "Sketova ulica",
        "Skopčeva ulica",
        "Skopska ulica",
        "Skrbinškova ulica",
        "Slape",
        "Slapnikova ulica",
        "Slavčja ulica",
        "Slodnjakova ulica",
        "Slomškova ulica",
        "Slovenčeva ulica",
        "Slovenska cesta",
        "Smerdujeva ulica",
        "Smoletova ulica",
        "Smrekarjeva ulica",
        "Smrtnikova ulica",
        "Sneberska cesta",
        "Snebersko nabrežje",
        "Snežniška ulica",
        "Snojeva ulica",
        "Sodarska steza",
        "Sojerjeva ulica",
        "Sončna pot",
        "Sostrska cesta",
        "Soška ulica",
        "Soteska",
        "Soteška pot",
        "Soussenska ulica",
        "Sovretova ulica",
        "Splitska ulica",
        "Spodnji Rudnik I",
        "Spodnji Rudnik II",
        "Spodnji Rudnik III",
        "Spodnji Rudnik IV",
        "Spodnji Rudnik V",
        "Spomeniška pot",
        "Srebrničeva ulica",
        "Središka ulica",
        "Srednja pot",
        "Stadionska ulica",
        "Staničeva ulica",
        "Stantetova ulica",
        "Stara Ježica",
        "Stara slovenska ulica",
        "Stare Črnuče",
        "Staretova ulica",
        "Stari trg",
        "Stegne",
        "Steletova ulica",
        "Sternadova ulica",
        "Sternenova ulica",
        "Stiška ulica",
        "Stolpniška ulica",
        "Stoženska ulica",
        "Stožice",
        "Stranska pot",
        "Stražarjeva ulica",
        "Streliška ulica",
        "Stritarjeva ulica",
        "Strmec",
        "Strmeckijeva ulica",
        "Strmi pot",
        "Strniševa cesta",
        "Strojeva ulica",
        "Strossmayerjeva ulica",
        "Strugarska ulica",
        "Strupijevo nabrežje",
        "Studenec",
        "Suhadolčanova ulica",
        "Sulčja ulica",
        "Svetčeva ulica",
        "Svetosavska ulica",
        "Šarhova ulica",
        "Šentjakob",
        "Šentviška ulica",
        "Šercerjeva ulica",
        "Šerkova ulica",
        "Šestova ulica",
        "Šibeniška ulica",
        "Šifrerjeva ulica",
        "Šinkov štradon",
        "Šišenska cesta",
        "Šivičeva ulica",
        "Škerjančeva ulica",
        "Škerljeva ulica",
        "Škofova ulica",
        "Škrabčeva ulica",
        "Šlajmerjeva ulica",
        "Šlandrova ulica",
        "Šlosarjeva ulica",
        "Šmarna gora",
        "Šmarnogorska pot",
        "Šmartinska cesta",
        "Šmartno",
        "Španova pot",
        "Španska ulica",
        "Športna ulica",
        "Štajerska cesta",
        "Štebijeva cesta",
        "Štefančeva ulica",
        "Štefanova ulica",
        "Štembalova ulica",
        "Štepanjska cesta",
        "Štepanjsko nabrežje",
        "Štihova ulica",
        "Štirnova ulica",
        "Štradon čez Prošco",
        "Štrekljeva ulica",
        "Štrukljeva ulica",
        "Študentovska ulica",
        "Štukljeva cesta",
        "Štula",
        "Štularjeva ulica",
        "Šturmova ulica",
        "Šubičeva ulica",
        "Šumarjeva ulica",
        "Šuštarjevo nabrežje",
        "Švabićeva ulica",
        "Švarova ulica",
        "Švegljeva cesta",
        "Tabor",
        "Taborska cesta",
        "Tacenska cesta",
        "Tavčarjeva ulica",
        "Tbilisijska ulica",
        "Tehnološki park",
        "Tesarska ulica",
        "Teslova ulica",
        "Tesna ulica",
        "Tesovnikova ulica",
        "Thumova ulica",
        "Tiha ulica",
        "Tiranova ulica",
        "Tischlerjeva ulica",
        "Tisnikarjeva ulica",
        "Tivolska cesta",
        "Tkalska ulica",
        "Tobačna ulica",
        "Tolminska ulica",
        "Tolstojeva ulica",
        "Tomačevo",
        "Tomačevska cesta",
        "Tomažičeva ulica",
        "Tomčeva ulica",
        "Tometova ulica",
        "Tominškova ulica",
        "Tomišeljska ulica",
        "Tomšičeva ulica",
        "Toplarniška ulica",
        "Topniška ulica",
        "Torkarjeva ulica",
        "Tovarniška ulica",
        "Tratnikova ulica",
        "Travniška ulica",
        "Trbeže",
        "Trdinova ulica",
        "Trebinjska ulica",
        "Trebušakova ulica",
        "Trg francoske revolucije",
        "Trg komandanta Staneta",
        "Trg mladih",
        "Trg mladinskih delov. brigad",
        "Trg narodnih herojev",
        "Trg Osvobodilne fronte",
        "Trg prekomorskih brigad",
        "Trg republike",
        "Trg 9. maja",
        "Triglavska ulica",
        "Trinkova ulica",
        "Trnovčeva ulica",
        "Trnovska ulica",
        "Trnovski pristan",
        "Trpinčeva ulica",
        "Trstenjakova ulica",
        "Trtnikova ulica",
        "Trubarjeva cesta",
        "Tržaška cesta",
        "Tržna ulica",
        "Tugomerjeva ulica",
        "Turjaška ulica",
        "Turnerjeva ulica",
        "Turnsko nabrežje",
        "Udvančeva ulica",
        "Ukmarjeva ulica",
        "Ulica aktivistov",
        "Ulica Alme Sodnik",
        "Ulica Andreja Kumarja",
        "Ulica Ane Ziherlove",
        "Ulica Angelce Ocepkove",
        "Ulica Angele Ljubičeve",
        "Ulica Bena Zupančiča",
        "Ulica borca Petra",
        "Ulica borcev za severno mejo",
        "Ulica bratov Babnik",
        "Ulica bratov Bezlajev",
        "Ulica bratov Blanč",
        "Ulica bratov Jančar",
        "Ulica bratov Knapič",
        "Ulica bratov Komel",
        "Ulica bratov Kraljič",
        "Ulica bratov Martinec",
        "Ulica bratov Miklič",
        "Ulica bratov Novak",
        "Ulica bratov Rozmanov",
        "Ulica bratov Škofov",
        "Ulica bratov Tuma",
        "Ulica bratov Učakar",
        "Ulica bratov Židan",
        "Ulica Cankarjeve brigade",
        "Ulica Dušana Kraigherja",
        "Ulica Ernesta Kramerja",
        "Ulica Franca Mlakarja",
        "Ulica Franca Nebca",
        "Ulica Francke Jerasove",
        "Ulica Franja Novaka",
        "Ulica Franje Koširjeve",
        "Ulica gledališča BTC",
        "Ulica Goce Delčeva",
        "Ulica Gradnikove brigade",
        "Ulica Gubčeve brigade",
        "Ulica Hermana Potočnika",
        "Ulica Iga Grudna",
        "Ulica Ivana Roba",
        "Ulica Ivanke Kožuh",
        "Ulica Ivice Pirjevčeve",
        "Ulica Jana Husa",
        "Ulica Janeza Pavla II.",
        "Ulica Janeza Rožiča",
        "Ulica Josipine Turnograjske",
        "Ulica Jožeta Jame",
        "Ulica Jožeta Japlja",
        "Ulica Jožeta Mirtiča",
        "Ulica Jožeta Štruklja",
        "Ulica Konrada Babnika",
        "Ulica Koroškega bataljona",
        "Ulica Lili Novy",
        "Ulica Lizike Jančarjeve",
        "Ulica Lojzeta Spacala",
        "Ulica Lojzke Štebijeve",
        "Ulica Lovre Klemenčiča",
        "Ulica Malči Beličeve",
        "Ulica Manice Komanove",
        "Ulica Marije Drakslerjeve",
        "Ulica Marije Hvaličeve",
        "Ulica Marije Mlinar",
        "Ulica Marje Boršnikove",
        "Ulica Marka Šlajmerja",
        "Ulica Metoda Mikuža",
        "Ulica Milana Majcna",
        "Ulica Milke Kerinove",
        "Ulica Minke Bobnar",
        "Ulica Mire Miheličeve",
        "Ulica Mirka Jurce",
        "Ulica Mirka Tomšiča",
        "Ulica Miroslava Turka",
        "Ulica miru",
        "Ulica Molniške čete",
        "Ulica na Grad",
        "Ulica Nade Čamernikove",
        "Ulica nadgoriških borcev",
        "Ulica Olge Mohorjeve",
        "Ulica padlih borcev",
        "Ulica Pariške komune",
        "Ulica Pavle Jeromnove",
        "Ulica Pohorskega bataljona",
        "Ulica Polonce Čude",
        "Ulica pregnancev",
        "Ulica prvoborcev",
        "Ulica Rezke Dragarjeve",
        "Ulica Rezke Klopčič",
        "Ulica Rozke Usenik",
        "Ulica Rudolfa Janežiča",
        "Ulica Staneta Severja",
        "Ulica stare pravde",
        "Ulica Štefke Zbašnikove",
        "Ulica talcev",
        "Ulica Tomšičeve brigade",
        "Ulica Tončke Čečeve",
        "Ulica v Kokovšek",
        "Ulica Vide Janežičeve",
        "Ulica Vide Pregarčeve",
        "Ulica Vladimirja Trampuža",
        "Ulica Zore Majcnove",
        "Ulica Zore Ragancinove",
        "Ulica Žanke Erjavec",
        "Ulica Željka Tonija",
        "Ulica 15. aprila",
        "Ulica 15. maja",
        "Ulica 24. avgusta",
        "Ulica 28. maja",
        "Ulica 4. julija",
        "Ulica 7. septembra",
        "Ulica 9. junija",
        "Uraničeva ulica",
        "Uršičev štradon",
        "Usnjarska ulica",
        "V Češnjico",
        "V dolini",
        "V Dovjež",
        "V Karlovce",
        "V Karlovce",
        "V Kladeh",
        "V Murglah",
        "V Sige",
        "V Toplice",
        "V Varde",
        "V Zalar",
        "Vagajeva ulica",
        "Valjavčeva ulica",
        "Valjhunova ulica",
        "Valvasorjeva ulica",
        "Vandotova ulica",
        "Vaška pot",
        "Vavpotičeva ulica",
        "Večna pot",
        "Vegova ulica",
        "Velebitska ulica",
        "Velika čolnarska ulica",
        "Veliki štradon",
        "Velikovška ulica",
        "Velnarjeva ulica",
        "Verdnikova ulica",
        "Verovškova ulica",
        "Veršičeva ulica",
        "Veselova ulica",
        "Vevška cesta",
        "Videmska ulica",
        "Vidergarjeva ulica",
        "Vidičeva ulica",
        "Vidmarjeva ulica",
        "Vidovdanska cesta",
        "Vilharjev podhod",
        "Vilharjeva cesta",
        "Vinčarjeva ulica",
        "Vinterca",
        "Vipavska ulica",
        "Vipotnikova ulica",
        "Viška cesta",
        "Višnjevarjeva ulica",
        "Vižmarska pot",
        "Vodmatska ulica",
        "Vodmatski trg",
        "Vodna steza",
        "Vodnikov trg",
        "Vodnikova cesta",
        "Vodnikovo naselje",
        "Vodovodna cesta",
        "Voduškova ulica",
        "Vogelna ulica",
        "Vojkova cesta",
        "Volaričeva ulica",
        "Volarjev štradon",
        "Vošnjakova ulica",
        "Vozna pot na Grad",
        "Vožarski pot",
        "Vranja pot",
        "Vrazov trg",
        "Vrbovec",
        "Vrbska ulica",
        "Vregova ulica",
        "Vrhniška ulica",
        "Vrhovci, cesta I",
        "Vrhovci, cesta II",
        "Vrhovci, cesta III",
        "Vrhovci, cesta IV",
        "Vrhovci, cesta IX",
        "Vrhovci, cesta V",
        "Vrhovci, cesta VI",
        "Vrhovci, cesta VIII",
        "Vrhovci, cesta X",
        "Vrhovci, cesta XI",
        "Vrhovci, cesta XII",
        "Vrhovci, cesta XIII",
        "Vrhovci, cesta XIV",
        "Vrhovci, cesta XIX",
        "Vrhovci, cesta XV",
        "Vrhovci, cesta XVI",
        "Vrhovci, cesta XVII",
        "Vrhovci, cesta XVIII",
        "Vrhovci, cesta XX",
        "Vrhovci, cesta XXI",
        "Vrhovci, cesta XXII",
        "Vrhovci, cesta XXVI",
        "Vrhovci, cesta XXVIII",
        "Vrhovci, cesta XXX",
        "Vrhovci, cesta XXXII",
        "Vrhovčeva ulica",
        "Vrhovnikova ulica",
        "Vrščajeva ulica",
        "Vrtača",
        "Vrtna ulica",
        "Vrtnarska cesta",
        "Vulčeva ulica",
        "Vurnikova ulica",
        "Vzajemna ulica",
        "Windischerjeva ulica",
        "Wolfova ulica",
        "Za čreslom",
        "Za Garažami",
        "Za gasilskim domom",
        "Za Gradom",
        "Za krajem",
        "Za ograjami",
        "Za opekarno",
        "Za partizanskim domom",
        "Za progo",
        "Za vasjo",
        "Zabretova ulica",
        "Zadnikarjeva ulica",
        "Zadobrovška cesta",
        "Zadružna ulica",
        "Zagrebška ulica",
        "Zajčeva pot",
        "Zajčevi dvori",
        "Zakotnikova ulica",
        "Zakrajškova ulica",
        "Zalaznikova ulica",
        "Zaletelova ulica",
        "Zaloška cesta",
        "Zapuška cesta",
        "Zarnikova ulica",
        "Zasavska cesta",
        "Zatišje",
        "Zavetiška ulica",
        "Zavoglje",
        "Završje",
        "Zbašnikova ulica",
        "Zdešarjeva cesta",
        "Zdravstvena pot",
        "Zelena pot",
        "Zelenova ulica",
        "Zeljarska ulica",
        "Zemljemerska ulica",
        "Zevnikova ulica",
        "Zidarjev štradon",
        "Ziherlova ulica",
        "Ziljska ulica",
        "Zlatek",
        "Znamenjska ulica",
        "Zofke Kvedrove ulica",
        "Zoisova cesta",
        "Zoletova ulica",
        "Zupanova ulica",
        "Zvezda",
        "Zvezdarska ulica",
        "Zvezna ulica",
        "Zvonarska ulica",
        "Žabarjeva ulica",
        "Žabjak",
        "Žalska ulica",
        "Žaucerjeva ulica",
        "Žebretova ulica",
        "Žeje",
        "Železna cesta",
        "Železnikarjeva ulica",
        "Žerjalova ulica",
        "Žibertova ulica",
        "Židankova ulica",
        "Židovska steza",
        "Židovska ulica",
        "Žigonova ulica",
        "Živaličeva ulica",
        "Živinozdravska ulica",
        "Žolgerjeva ulica",
        "Žorgova ulica",
        "Župančičeva ulica",

    )

    states = (
        'Pomurksa',
        'Podravska',
        'Koroška',
        'Savinjska',
        'Zasavska',
        'Spodnjeposavska',
        'Jugovyhodna Slovenija',
        'Osrednjeslovenska',
        'Gorenjska',
        'Notranjsko - kraška',
        'Goriška',
        'Obalno - kraška',
    )

    countries = (
        "Afganistan", "Islamska republika Afganistan", "Albanija", 
        "Republika Albanija", "Alžirija", "Ljudska demokratična republika Alžirija", 
        "Andora", "Kneževina Andora", "Angola", "Republika Angola", 
        "Antigva in Barbuda", "Argentina", "Argentinska republika", 
        "Armenija", "Republika Armenija", "Avstralija", "Avstrija", 
        "Republika Avstrija", "Azerbajdžan", "Azerbajdžanska republika", 
        "Bahami", "Zveza Bahami", "Bahrajn", "Država Bahrajn", "Bangladeš", 
        "Ljudska republika Bangladeš", "Barbados", "Belgija", 
        "Kraljevina Belgija", "Belize", "Belorusija", 
        "Republika Belorusija", "Benin", "Republika Benin", 
        "Bocvana", "Republika Bocvana", "Bolgarija", "Republika Bolgarija", 
        "Bolivija", "Republika Bolivija", "Bosna in Hercegovina", "Brazilija", 
        "Federativna republika Brazilija", "Brunej", "Država Brunej", 
        "Burkina Faso", "Burundi", "Republika Burundi", "Butan", 
        "Kraljevina Butan", "Ciper", "Republika Ciper", "Čad", 
        "Republika Čad", "Češka", "Češka republika", "Čile", 
        "Republika Čile", "Črna gora", "Republika Črna gora", 
        "Danska", "Kraljevina Danska", "Dominika", "Zveza Dominika", 
        "Dominikanska republika", "Džibuti", "Republika Džibuti", 
        "Egipt", "Arabska republika Egipt", "Ekvador", "Republika Ekvador", 
        "Ekvatorialna Gvineja", "Republika Ekvatorialna Gvineja", 
        "Eritreja", "Estonija", "Republika Estonija", "Etiopija", 
        "Fidži", "Republika Fidžijski otoki", "Filipini", "Republika Filipini", 
        "Finska", "Republika Finska", "Francija", "Francoska republika", 
        "Gabon", "Gabonska republika", "Gambija", "Republika Gambija", "Gana", 
        "Republika Gana", "Grčija", "Helenska republika", "Grenada", 
        "Gruzija", "Gvajana", "Republika Gvajana", "Gvatemala", "Republika Gvatemala", 
        "Gvineja", "Republika Gvineja", "Gvineja Bissau", "Republika Gvineja Bissau", 
        "Haiti", "Republika Haiti", "Honduras", "Republika Honduras", 
        "Hrvaška", "Republika Hrvaška", "Indija", "Republika Indija", 
        "Indonezija", "Republika Indonezija", "Irak", "Republika Irak", 
        "Iran", "Islamska republika Iran", "Irska", "Islandija", 
        "Republika Islandija", "Italija", "Italijanska republika", "Izrael", 
        "Država Izrael", "Jamajka", "Japonska", "Jemen", "Republika Jemen", 
        "Jordanija", "Hašemitska kraljevina Jordanija", "Južna Afrika", 
        "Republika Južna Afrika", "Južna Koreja", "Koreja, Republika", 
        "Kambodža", "Kraljevina Kambodža", "Kamerun", "Republika Kamerun", 
        "Kanada", "Katar", "Država Katar", "Kazahstan", "Republika Kazahstan", 
        "Kenija", "Republika Kenija", "Kirgizistan", "Kirgiška republika", 
        "Kiribati", "Kitajska", "Ljudska republika Kitajska", "Kolumbija", 
        "Republika Kolumbija", "Komori", "Islamska zvezna republika Komori", 
        "Kongo", "Republika Kongo", "Demokratična republika Kongo", 
        "Kostarika", "Republika Kostarika", "Kuba", "Republika Kuba", 
        "Kuvajt", "Država Kuvajt", "Laos", "Laoška ljudska demokratična republika", 
        "Latvija", "Republika Latvija", "Lesoto", "Kraljevina Lesoto", 
        "Libanon", "Libanonska republika", "Liberija", "Republika Liberija", 
        "Libija", "Libijska arabska džamahirija", 
        "Socialistična ljudska libijska arabska džamahirija", 
        "Lihtenštajn", "Kneževina Lihtenštajn", "Litva", "Republika Litva", 
        "Luksemburg", "Veliko vojvodstvo Luksemburg", "Madagaskar", 
        "Republika Madagaskar", "Madžarska", "Republika Madžarska", 
        "Makedonija", "Republika Makedonija", "Malavi", "Republika Malavi", 
        "Maldivi", "Republika Maldivi", "Malezija", "Mali", "Republika Mali", 
        "Malta", "Republika Malta", "Maroko", "Kraljevina Maroko", 
        "Marshallovi otoki", "Republika Marshallovi otoki", "Mauritius", 
        "Republika Mauritius", "Mavretanija", "Islamska republika Mavretanija", 
        "Mehika", "Združene mehiške države", "Mikronezija", "Združene države Mikronezije", 
        "Mjanmar", "Zveza Mjanmar", "Moldavija", "Moldavija, Republika", 
        "Monako", "Kneževina Monako", "Mongolija", "Mozambik", "Republika Mozambik", 
        "Namibija", "Republika Namibija", "Nauru", "Republika Nauru", "Nemčija", 
        "Zvezna republika Nemčija", "Nepal", "Kraljevina Nepal", "Niger", "Republika Niger", 
        "Nigerija", "Zvezna republika Nigerija", "Nikaragva", "Republika Nikaragva", 
        "Nizozemska", "Kraljevina Nizozemska", "Norveška", "Kraljevina Norveška", 
        "Nova Zelandija", "Oman", "Sultanat Oman", "Pakistan", 
        "Islamska republika Pakistan", "Palau", "Republika Palau", "Panama", 
        "Republika Panama", "Papua Nova Gvineja", "Paragvaj", "Republika Paragvaj", 
        "Peru", "Republika Peru", "Poljska", "Republika Poljska", "Portugalska", 
        "Portugalska republika", "Romunija", "Ruanda", "Republika Ruanda", "Rusija", 
        "Ruska federacija", "Saint Kitts in Nevis", "Saint Lucia", 
        "Saint Vincent in Grenadine", "Salomonovi otoki", "Salvador", 
        "Republika Salvador", "San Marino", "Republika San Marino", "Sao Tome in Principe", 
        "Demokratična republika Sao Tome in Principe", "Saudova Arabija", 
        "Kraljevina Saudova Arabija", "Sejšeli", "Republika Sejšeli", "Senegal", 
        "Republika Senegal", "Severna Koreja", "Demokratična ljudska republika Koreja", 
        "Sierra Leone", "Republika Sierra Leone", "Singapur", "Republika Singapur", "Sirija", 
        "Sirska arabska republika", "Slonokoščena obala", "Republika Slonokoščena obala", 
        "Slovaška", "Slovaška republika", "Slovenija", "Republika Slovenija", "Somalija", 
        "Somalska demokratična republika", "Srbija", "Republika Srbija", "Srednjeafriška republika", 
        "Sudan", "Republika Sudan", "Surinam", "Republika Surinam", "Svazi", "Kraljevina Svazi", 
        "Španija", "Kraljevina Španija", "Šrilanka", "Demokratična socialistična republika Šrilanka", 
        "Švedska", "Kraljevina Švedska", "Švica", "Švicarska konfederacija", "Tadžikistan", 
        "Republika Tadžikistan", "Tajska", "Kraljevina Tajska", "Tajvan", "Tajvan, Provinca Kitajske", 
        "Tanzanija", "Združena republika Tanzanija", "Togo", "Togoška republika", "Tonga", 
        "Kraljevina Tonga", "Trinidad in Tobago", "Republika Trinidad in Tobago", "Tunizija", 
        "Republika Tunizija", "Turčija", "Republika Turčija", "Turkmenistan", "Tuvalu", 
        "Uganda", "Republika Uganda", "Ukrajina", "Urugvaj", "Vzhodna republika Urugvaj", 
        "Uzbekistan", "Republika Uzbekistan", "Vanuatu", "Republika Vanuatu", "Vatikan", 
        "Sveti sedež (Vatikanska mestna država)", "Velika Britanija", "Združeno kraljestvo", 
        "Združeno kraljestvo Velike Britanije in Severne Irske", "Venezuela", 
        "Republika Venezuela", "Vietnam", "Socialistična republika Vietnam", 
        "Vzhodni Timor", "Demokratična republika Vzhodni Timor", "Zahodna Samoa", 
        "Samoa", "Neodvisna država Zahodna Samoa", "Zambija", "Republika Zambija", 
        "Združene države Amerike", "Združene države", "Združene države Amerike", 
        "Združeni arabski emirati", "Zelenortski otoki", "Republika Zelenortski otoki", 
        "Zimbabve", "Republika Zimbabve"    
    )

    @classmethod
    def city_name(cls):
        return cls.random_element(cls.cities)

    @classmethod
    def street_name(cls):
        return cls.random_element(cls.streets)

    @classmethod
    def state(cls):
        return cls.random_element(cls.states)
