name: Python Lint

on:
  push:
    tags-ignore:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: Lint with flake8
      run: tox
      env:
        TOXENV: flake8
    - name: Check manifest
      run: tox
      env:
        TOXENV: checkmanifest
    - name: isort
      run: tox
      env:
        TOXENV: isort
